const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {createAccounts}=require('../desktop/accounts.cjs');

test('account history reads all match pages within a fixed capture interval',async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dropzone-analysis-pages-')),owner='00000000-0000-4000-8000-000000000001',asOf=Date.UTC(2026,0,1),requests=[];
 const fetcher=async(url,options)=>{requests.push(url);if(url.includes('/token?'))return Response.json({access_token:'fixture',refresh_token:'fixture',expires_in:3600,user:{id:owner}});if(url.includes('/match_records?')){const offset=Number(new URL(url).searchParams.get('offset'));return Response.json(Array.from({length:offset===0?1000:2},(_,i)=>({match_id:'match-'+(offset+i),played_at:new Date(asOf-10000).toISOString(),won:true,stats:{PlaylistId:11,Goals:1}})));}return Response.json([]);};
 try{const accounts=createAccounts({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()},config:{url:'https://fixture.supabase.co',publishableKey:'sb_publishable_fixture'},fetcher});await accounts.command({action:'account-signin',email:'fixture@example.test',password:'fixture-long-password'});const result=await accounts.command({action:'account-stats',id:owner,asOf});assert.equal(result.records.length,1002);assert.equal(result.matches,1002);const pages=requests.filter(url=>url.includes('/match_records?')).map(url=>new URL(url));assert.equal(pages.length,2);assert.deepEqual(pages.map(u=>u.searchParams.get('offset')),['0','1000']);assert.ok(pages.every(u=>u.searchParams.getAll('played_at').includes('lte.'+new Date(asOf).toISOString())));assert.ok(pages.every(u=>u.searchParams.getAll('played_at').includes('gte.'+new Date(asOf-365*86400000).toISOString())));assert.ok(pages.every(u=>u.searchParams.get('owner')==='eq.'+owner));}finally{await fs.rm(directory,{recursive:true,force:true});}
});
test('Apex calls stay inside encrypted account boundary and use user Authorization on deployed function',async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dropzone-apex-auth-')),requests=[];
 const fetcher=async(url,options)=>{requests.push({url,options});return Response.json(url.includes('/token?')?{access_token:'fixture-user-token',refresh_token:'fixture-refresh',expires_in:3600,user:{id:'fixture-user'}}:url.includes('/profiles?')?[]:{configured:true,status:'validation-required',Authorization:'must-not-escape'});};
 try{const accounts=createAccounts({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()},config:{url:'https://fixture.supabase.co',publishableKey:'sb_publishable_fixture'},fetcher});
  assert.equal((await accounts.invokeApex({action:'status'})).status,'sign-in-required');assert.equal(requests.length,0);
  await accounts.command({action:'account-signin',email:'fixture@example.test',password:'fixture-long-password'});
  const result=await accounts.invokeApex({action:'status',Authorization:'renderer-token'});const call=requests.at(-1);
  assert.equal(call.url,'https://fixture.supabase.co/functions/v1/bright-api');assert.equal(call.options.headers.Authorization,'Bearer fixture-user-token');assert.equal(call.options.headers.apikey,'sb_publishable_fixture');assert.deepEqual(JSON.parse(call.options.body),{action:'status'});assert.doesNotMatch(JSON.stringify(result),/fixture-user-token|fixture-refresh|must-not-escape/);assert.equal(result.available,false);
 }finally{await fs.rm(directory,{recursive:true,force:true});}
});
test('accounts keep passwords and tokens out of renderer state and persist only encrypted sessions',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dropzone-account-'));const requests=[],config={url:'https://example.supabase.co',publishableKey:'sb_publishable_test_public_key'};const secure={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s).map(v=>v^73),decryptString:b=>Buffer.from(b).map(v=>v^73).toString()};const fetcher=async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify(url.includes('/token?')?{access_token:'secret-access',refresh_token:'secret-refresh',expires_in:3600,user:{id:'00000000-0000-4000-8000-000000000001',email:'qa@example.test'}}:url.includes('/profiles?')?[{handle:'qa_player'}]:null),{status:200});};try{const accounts=createAccounts({directory,safeStorage:secure,config,fetcher});await assert.rejects(accounts.command({action:'account-signup',email:'qa@example.test',password:'short',handle:'qa_player'}),/12 to 128/);const state=await accounts.command({action:'account-signin',email:'qa@example.test',password:'a-long-test-password'});assert.equal(state.profile.handle,'qa_player');assert.doesNotMatch(JSON.stringify(state),/secret-access|secret-refresh|a-long-test-password/);const bytes=await fs.readFile(path.join(directory,'account-session.bin'));assert.doesNotMatch(bytes.toString(),/secret-access|secret-refresh|a-long-test-password/);await accounts.command({action:'account-signout'});await assert.rejects(fs.access(path.join(directory,'account-session.bin')));await assert.rejects(accounts.command({action:'account-delete',confirm:'no'}),/DELETE/);const disabled=createAccounts({directory,safeStorage:secure,config:{url:config.url,publishableKey:'sb_secret_not_allowed'},fetcher});assert.equal((await disabled.command({action:'account-state'})).enabled,false);}finally{await fs.rm(directory,{recursive:true,force:true});}});

test('cloud playtime reads every page and uploads only for the current account',async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dropzone-time-'));const owner='00000000-0000-4000-8000-000000000001',source='00000000-0000-4000-8000-000000000002';const requests=[];
 const fetcher=async(url,options)=>{requests.push({url,options});const result=url.includes('/token?')?{access_token:'test',refresh_token:'test',expires_in:3600,user:{id:owner}}:url.includes('/profiles?')?[{id:owner,handle:'player',share_stats:true}]:url.includes('/player_playtime?')?Array.from({length:url.includes('offset=0')?1000:1},()=>({source,day:0,kind:'freeplay',seconds:30})):url.includes('/match_records?')?[]:null;return new Response(JSON.stringify(result));};
 try{const accounts=createAccounts({directory,safeStorage:{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()},config:{url:'https://example.supabase.co',publishableKey:'sb_publishable_test'},fetcher});await accounts.command({action:'account-signin',email:'qa@example.test',password:'long-test-password'});
 const result=await accounts.command({action:'account-stats',id:owner});assert.equal(result.playtime.length,1001);assert.equal(result.records.length,0);assert.ok(requests.some(r=>r.url.includes('player_playtime?')&&r.url.includes('offset=1000')));
 const records=[{day:0,kind:'freeplay',seconds:120}];await accounts.command({action:'account-upload-playtime',owner,source,records});assert.deepEqual(JSON.parse(requests.at(-1).options.body),{source_id:source,records});await assert.rejects(accounts.command({action:'account-upload-playtime',owner:source,source,records}),/Account changed/);await assert.rejects(accounts.command({action:'account-upload-playtime',owner,source,records:Array(101).fill({})}),/Invalid playtime/);
 }finally{await fs.rm(directory,{recursive:true,force:true});}
});
