'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {ApexPlayerProvider,ENDPOINT}=require('../core/apex-player.cjs');
const {normalizeNews,normalizeEsports}=require('../core/apex-content.cjs');
const snapshot=require('../app/data/apex/apex-content.json');
test('Apex official snapshot retains a sourced complete roster and each ability name without fake meta ranks',()=>{assert.equal(snapshot.catalog.legends.length,28);assert.equal(new Set(snapshot.catalog.legends.map(x=>x.name)).size,28);for(const row of snapshot.catalog.legends){assert.ok(['Assault','Controller','Recon','Skirmisher','Support'].includes(row.role));assert.ok(row.abilities.some(x=>x.type==='Tactical'));assert.ok(row.abilities.some(x=>x.type==='Passive'));assert.ok(row.abilities.some(x=>x.type==='Ultimate'));assert.equal(row.rank,undefined);}assert.equal(snapshot.catalog.legends.find(x=>x.name==='Axle').role,'Skirmisher');assert.ok(snapshot.news.every(x=>new URL(x.url).hostname==='www.ea.com'));assert.ok(snapshot.esports.every(x=>new URL(x.url).hostname==='algs.ea.com'));});
test('Apex imagery bytes match the actual publisher-source manifest',()=>{const manifest=require('../app/data/apex/image-sources.json');assert.equal(manifest.assets.length,22);for(const row of manifest.assets){const bytes=fs.readFileSync(path.join(__dirname,'../app',row.localPath));assert.equal(bytes.length,row.bytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),row.sha256);assert.ok(['drop-assets.ea.com','images.ctfassets.net'].includes(new URL(row.imageUrl).hostname));}});
test('Official news parsers fail closed on changed formats and preserve missing publication dates',()=>{assert.throws(()=>normalizeNews('<h1>Unrelated site</h1>'));assert.throws(()=>normalizeEsports('<a href="https://untrusted.invalid/en/news/fake"><h4>Fake</h4></a>'));const d=normalizeEsports('<a href="/en/news/event"><h4>Year 6 &amp; finals</h4></a>');assert.equal(d[0].title,'Year 6 & finals');assert.equal(d[0].publishedAt,null);});

test('Desktop Apex rechecks the account boundary and strips raw provider and credential fields',async()=>{const calls=[];const p=new ApexPlayerProvider({invoke:async body=>{calls.push(body);return {configured:true,status:'validation-required',key:'must-not-be-exposed',stats:{invented:10}};}});const results=await Promise.all([p.get(),p.get()]);assert.equal(calls.length,2);for(const result of results){assert.equal(result.available,false);assert.equal(result.status,'validation-required');assert.equal(result.key,undefined);assert.equal(result.stats,undefined);}assert.deepEqual(calls[0],{action:'status'});assert.match(ENDPOINT,/supabase.co\/functions\/v1\/bright-api$/);});
test('Desktop Apex never enables unknown response shapes or bypasses missing accounts',async()=>{const absent=await new ApexPlayerProvider().get();assert.equal(absent.status,'sign-in-required');for(const response of [{status:'unknown',secret:'private'},{status:'live',rawSecret:'private'}]){const p=new ApexPlayerProvider({invoke:async()=>response});const result=await p.get();assert.equal(result.available,false);assert.equal(result.status,'service-unavailable');assert.equal(result.rawSecret,undefined);}await assert.rejects(new ApexPlayerProvider().get([]),/Invalid/);await assert.rejects(new ApexPlayerProvider().get({action:'validate',platform:'PC',player:''}),/valid/);});

test('Desktop Apex retains only enumerated provider diagnostics and validated UID identity',async()=>{
 const calls=[],p=new ApexPlayerProvider({invoke:async body=>{calls.push(body);return{status:'provider-unavailable',configured:true,diagnostic:{stage:'provider',http:403,code:'provider-access-denied',raw:'private'},secret:'private'};}});
 const result=await p.get({action:'validate',platform:'PC',uid:'1000301388710',authorization:'private'});
 assert.deepEqual(calls,[{action:'validate',platform:'PC',uid:'1000301388710'}]);assert.deepEqual(result.diagnostic,{stage:'provider',code:'provider-access-denied',http:403});assert.equal(result.configured,true);assert.equal(result.secret,undefined);
 await assert.rejects(p.get({action:'validate',platform:'PC',uid:'1',player:'name'}));
});
