const {test}=require('node:test'),assert=require('node:assert/strict');
const {DEFAULTS,validateSettings}=require('../desktop/coaching-settings.cjs');
test('coaching settings validate shortcuts, limits and safe option values',()=>{assert.equal(validateSettings().toggleKey,'Control+Alt+C');assert.throws(()=>validateSettings({toggleKey:'D'}));assert.throws(()=>validateSettings({clearKey:DEFAULTS.toggleKey}));assert.throws(()=>validateSettings({thickness:99}));assert.throws(()=>validateSettings({color:'url(http://example.com)'}));assert.equal(validateSettings({toolbar:{x:4,y:-2}}).toolbar.x,1);assert.equal(validateSettings({autoClear:'timer',seconds:20}).seconds,20);});
test('drawing history is bounded; undo/redo and layer-aware clearing preserve objects',async()=>{const {DrawingBoard,MAX_OBJECTS,MAX_HISTORY}=await import('../app/coaching/drawing.js');const b=new DrawingBoard();const o=i=>({tool:'arrow',points:[{x:.1,y:.2},{x:.3,y:.4}],layer:i%2?'persistent':'temporary',id:i});for(let i=0;i<400;i++)b.add(o(i));assert.equal(b.objects.length,MAX_OBJECTS);assert.equal(b.undoStack.length,MAX_HISTORY);b.clear(true);assert.ok(b.objects.every(o=>o.layer==='persistent'));b.undo();assert.equal(b.objects.length,MAX_OBJECTS);b.redo();assert.ok(b.objects.every(o=>o.layer==='persistent'));b.clear();assert.equal(b.objects.length,0);b.undo();assert.ok(b.objects.length);});
test('timed clearing expires only marked objects and no stale history revives them',async()=>{const {DrawingBoard}=await import('../app/coaching/drawing.js');const b=new DrawingBoard();b.add({id:'temp',points:[],expires:10});b.add({id:'keep',points:[],expires:0});assert.equal(b.expire(9),false);assert.equal(b.expire(11),true);assert.deepEqual(b.objects.map(o=>o.id),['keep']);b.undo();assert.equal(b.objects.length,1);});
test('normalized drawings scale to HD, ultrawide and 4K without changing stored data',async()=>{const {drawObject}=await import('../app/coaching/drawing.js');const points=[];const ctx={save(){},restore(){},beginPath(){},moveTo(x,y){points.push([x,y]);},lineTo(){},stroke(){}};const o={tool:'line',color:'#fff',opacity:1,width:.004,points:[{x:.25,y:.5},{x:.75,y:.5}]};for(const [w,h]of [[1920,1080],[2560,1440],[3440,1440],[3840,2160]]){drawObject(ctx,o,w,h);assert.deepEqual(points.at(-1),[w/4,h/2]);}assert.equal(o.points[0].x,.25);});
const {EventEmitter}=require('node:events'),{PassThrough}=require('node:stream'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
test('overlay is lazy, releases input on exit, follows client bounds and rejects foreign IPC',async()=>{
 const {createCoachingOverlay}=require('../desktop/coaching-overlay.cjs');let win,processes=0,child,cropped;const frameImage='data:image/png;base64,aGVsbG8=';const keys=new Map(),handlers=new Map(),screen=new EventEmitter();screen.getDisplayMatching=()=>({id:7});screen.screenToDipRect=(_w,r)=>({x:r.x/1.5,y:r.y/1.5,width:r.width/1.5,height:r.height/1.5});
 class FakeWindow extends EventEmitter{constructor(){super();win=this;this.dead=false;this.visible=false;this.webContents=new EventEmitter();this.webContents.mainFrame={};this.webContents.send=()=>{};this.webContents.setWindowOpenHandler=()=>{};}removeMenu(){}setIgnoreMouseEvents(v){this.ignore=v;}setAlwaysOnTop(){}async loadFile(){}isDestroyed(){return this.dead;}setBounds(v){this.bounds=v;}setOpacity(v){this.opacity=v;}show(){this.visible=true;}focus(){}hide(){this.visible=false;}destroy(){this.dead=true;this.emit('closed');}}
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dz-coach-'));
 const c=createCoachingOverlay({BrowserWindow:FakeWindow,globalShortcut:{register:(k,fn)=>{if(k==='Alt+F9')return false;keys.set(k,fn);return true;},unregister:k=>keys.delete(k)},screen,ipcMain:{handle:(k,fn)=>handlers.set(k,fn),removeHandler:k=>handlers.delete(k)},directory,desktopCapturer:{getSources:async()=>[{display_id:'7',thumbnail:{isEmpty:()=>false,getSize:()=>({width:3840,height:2160}),crop:r=>{cropped=r;return {toDataURL:()=>frameImage};}}}]},nativeImage:{createFromDataURL:()=>({isEmpty:()=>false,toPNG:()=>Buffer.from('fixture')})},platform:'win32',spawnWindow:()=>{processes++;child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{child.killed=true;};return child;}});
 try{await c.command({action:'state'});assert.equal(win,undefined);assert.equal(processes,0);assert.equal(keys.size,1,'Only the toggle shortcut is reserved while off');await c.command({action:'shortcut-capture',active:true});assert.equal(keys.size,0,'Editing a shortcut must release the existing global keys');await c.command({action:'shortcut-capture',active:false});assert.equal(keys.size,1,'Leaving shortcut capture restores registration');await c.command({action:'toggle'});assert.equal(processes,1);assert.equal(win.ignore,true);child.stdout.write(JSON.stringify({x:150,y:300,width:1920,height:1080,monitor:{x:0,y:0,width:2560,height:1440}})+'\n');assert.equal(c.status().active,true);assert.equal(keys.size,2);assert.equal(win.visible,true);assert.equal(win.ignore,false);assert.deepEqual(win.bounds,{x:100,y:200,width:1280,height:720});
 child.stdout.write('{"suspended":true}\n');assert.equal(c.status().active,true);assert.equal(c.status().suspended,true);assert.equal(win.ignore,true);assert.equal(win.visible,false);assert.equal(keys.size,1);assert.equal(child.killed,undefined,'Focus loss keeps the observer alive');child.stdout.write('{"suspended":false}\n');assert.equal(c.status().suspended,false);assert.equal(win.ignore,false);assert.equal(win.visible,true);assert.equal(processes,1,'Resume reuses the window and observer');assert.equal(keys.size,2);
 const event={sender:win.webContents,senderFrame:win.webContents.mainFrame},draw=handlers.get('coaching-draw');const frame=await draw(event,{action:'frame'});assert.equal(frame.image,frameImage);assert.deepEqual(cropped,{x:225,y:450,width:2880,height:1620});assert.equal(win.opacity,1);await draw(event,{action:'save',image:frame.image});assert.equal((await fs.readdir(path.join(directory,'screenshots'))).length,1);const object={tool:'line',color:'#ffffff',opacity:1,width:.004,points:[{x:.1,y:.2},{x:.4,y:.5}],layer:'persistent'};await draw(event,{action:'annotations',objects:[object]});assert.equal(JSON.parse(await fs.readFile(path.join(directory,'coaching-annotations.json'),'utf8'))[0].layer,'persistent');await assert.rejects(c.command({action:'settings',settings:{toggleKey:'Alt+F9'}}),/already used/);assert.equal(c.status().settings.toggleKey,'Control+Alt+C');assert.ok(keys.has('Control+Alt+C'));
 child.stdout.write(JSON.stringify({x:-1920,y:0,width:1920,height:1080})+'\n');assert.equal(win.bounds.x,-1280);
 await assert.rejects(handlers.get('coaching-draw')({sender:{},senderFrame:{}},{action:'exit'}),/Untrusted/);
 await c.command({action:'exit'});assert.equal(win.ignore,true);assert.equal(win.visible,false);assert.equal(keys.size,1);assert.equal(c.status().active,false);await c.command({action:'toggle'});child.stderr.write('Test helper failure');child.emit('exit',1);assert.match(c.status().error,/Test helper failure/);assert.equal(c.status().starting,false);c.destroy();c.destroy();assert.equal(keys.size,0);assert.equal(handlers.size,0);
 }finally{c.destroy();await fs.rm(directory,{recursive:true,force:true});}
});
test('native observer emits parseable bounds JSON on a fresh Windows launch',{skip:process.platform!=='win32'},async()=>{
 const {execFileSync}=require('node:child_process');const directory=await fs.mkdtemp(path.join(os.tmpdir(),'dz-coach-native-'));
 try{const output=execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.resolve('desktop/coaching-window.ps1'),'-SelfTest'],{windowsHide:true,encoding:'utf8',timeout:15000,env:{...process.env,DZ_COACH_CACHE:directory}});assert.deepEqual(JSON.parse(output.trim()),{x:-3840,y:0,width:3840,height:2160,monitor:{x:-3840,y:0,width:3840,height:2160}});}finally{if(!path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep))throw Error('Unsafe test cleanup');await fs.rm(directory,{recursive:true,force:true});}
});

test('old shipped coaching shortcuts migrate without replacing custom bindings',()=>{const {migrateSettings}=require('../desktop/coaching-settings.cjs');assert.equal(migrateSettings({toggleKey:'Control+Shift+D'}).toggleKey,'Control+Alt+C');assert.equal(migrateSettings({toggleKey:'Alt+F10'}).toggleKey,'Alt+F10');});
