const {test}=require('node:test'),assert=require('node:assert/strict');
test('Encrypted workspace rejects wrong keys and tampering; repeated merges preserve one conflict copy',async()=>{
 const m=await import('../app/command-model.js'),c=await import('../app/command-crypto.js');const state=m.blankState();state.records=[m.cleanRecord({id:'same',kind:'note',game:'finals',title:'Plan',updatedAt:'2026-09-10T12:00:00Z',body:'Original'})];
 const key=c.b64(crypto.getRandomValues(new Uint8Array(32))),payload=await c.encryptWorkspace(state,key);assert.deepEqual(await c.decryptWorkspace(payload,key),state);assert.ok(!payload.includes('Original'));
 await assert.rejects(c.decryptWorkspace(payload,c.b64(crypto.getRandomValues(new Uint8Array(32)))));const bytes=c.unb64(payload);bytes[20]^=1;await assert.rejects(c.decryptWorkspace(c.b64(bytes),key));
 const changed={...state,records:[{...state.records[0],body:'Other device',updatedAt:'2026-09-11T12:00:00Z'}]};const merged=await c.mergeWorkspaces(state,changed);assert.equal(merged.records.length,2);assert.equal(merged.records.find(r=>r.id==='same').body,'Other device');assert.equal((await c.mergeWorkspaces(merged,state)).records.length,2);
});
test('Calendar round trip preserves time and escaped notes; unsupported recurrence and bad dates fail visibly',async()=>{
 const c=await import('../app/command-calendar.js');const records=[{id:'event',kind:'event',title:'Practice, squad',body:'First\nSecond; detail',source:'https://example.com/',data:{when:'2026-09-12T18:30:00Z'}}];const parsed=c.importCalendar(c.exportCalendar(records),'finals');assert.equal(parsed[0].data.when,'2026-09-12T18:30:00.000Z');assert.equal(parsed[0].body,records[0].body);assert.throws(()=>c.importCalendar(c.exportCalendar(records).replace('END:VEVENT','RRULE:FREQ=DAILY\r\nEND:VEVENT'),'finals'));assert.throws(()=>c.importCalendar(c.exportCalendar(records).replace('20260912T183000Z','20260230T183000Z'),'finals'));
});
test('Restore remaps media without overwriting old references and bounds decompression',async()=>{
 const b=await import('../app/command-backup.js'),m=await import('../app/command-model.js');const entries={[m.CENTER_KEY]:JSON.stringify({...m.blankState(),records:[{data:{mediaId:'old',imageId:'old'}}]})},file=new File(['video'],'clip.webm');const result=b.remapRestoredMedia(entries,[['old',file]]);assert.notEqual(result.files[0][0],'old');assert.equal(JSON.parse(result.entries[m.CENTER_KEY]).records[0].data.mediaId,result.files[0][0]);assert.equal(JSON.parse(entries[m.CENTER_KEY]).records[0].data.mediaId,'old');assert.throws(()=>b.remapRestoredMedia(entries,[['old',file],['old',file]]));const compressed=await new Response(new Blob(['x'.repeat(1000)]).stream().pipeThrough(new CompressionStream('gzip'))).blob();await assert.rejects(b.readBackupText(new File([compressed],'test.gz'),100));
});
test('Companion-only launch does not open a game; missing launchers cause no partial launch',async()=>{
 const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');const root=await fs.mkdtemp(path.join(os.tmpdir(),'dropzone-launch-test-'));try{await fs.mkdir(path.join(root,'command-center'));await fs.writeFile(path.join(root,'command-center','launchers.json'),JSON.stringify({'finals':'game.exe','finals-companion':'companion.exe'}));const opened=[];const service=require('../desktop/command-service.cjs').createCommandService({app:{getPath:()=>root},shell:{openPath:async p=>{opened.push(p);return '';}},dialog:{}});await service.command({action:'launch',game:'finals',launchGame:false,companion:true});assert.deepEqual(opened,['companion.exe']);await assert.rejects(service.command({action:'launch',game:'wardogs',launchGame:true,companion:true}));assert.equal(opened.length,1);}finally{const resolved=path.resolve(root);if(path.dirname(resolved)!==path.resolve(os.tmpdir())||!path.basename(resolved).startsWith('dropzone-launch-test-'))throw Error('Unsafe test cleanup path');await fs.rm(resolved,{recursive:true,force:true});}
});
