const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {GzwProvider,normalizeGzw,fetchDataset,DATASETS}=require('../core/gzw-provider.cjs');
const map=require('../app/data/gzw/map.json'),places=require('../app/data/gzw/locations.json');
const when='2026-09-04T10:13:08.157Z';
function raw(extra=false){return Object.fromEntries(DATASETS.map(name=>[name,{dataVersion:when,data:name==='keys'||name==='keycards'?[{id:'storage-key',name:'Storage Key',usage:'Unlocks a door'}]:[{id:'first-recon',name:'First Recon',vendor:'Handshake',location:'Kiu Vongsa , Nam Thaven , Pha Lang'},...(extra&&name==='tasks'?[{id:'new-mission',name:'New Mission',vendor:'Gunny',location:'Ban Pa'}]:[])]}]));}
const response=(dataset,extra=false)=>JSON.stringify({...raw(extra)[dataset],page:1,totalPages:1,total:raw(extra)[dataset].data.length});
function requestFor(extra=false){return async url=>response(new URL(url).pathname.split('/').at(-1),extra);}

test('GZW merges overlapping mission lists and key lists without losing classification',()=>{const d=normalizeGzw(raw());assert.equal(d.tasks.length,1);assert.equal(d.keys.length,1);assert.equal(d.tasks[0].types.length,5);assert.equal(d.sourceUpdatedAt,when);assert.ok(d.tasks[0].sourceUrl.includes('First_Recon'));assert.equal(d.tasks[0].objectives,undefined);});
test('GZW rejects incomplete or mixed-version data instead of replacing a complete snapshot',()=>{const r=raw();r.side_task.dataVersion='2026-09-05T10:13:08Z';assert.throws(()=>normalizeGzw(r),/changed during refresh/);r.side_task.dataVersion=when;r.keys.data=[];assert.throws(()=>normalizeGzw(r),/Incomplete/);});
test('GZW pagination fetches every page and rejects missing/duplicate records',async()=>{let calls=[];const request=async url=>{const p=Number(new URL(url).searchParams.get('page'));calls.push(p);return JSON.stringify({page:p,totalPages:2,total:2,dataVersion:when,data:[{id:'m'+p,name:'Mission '+p}]});};const d=await fetchDataset('tasks',request);assert.equal(d.data.length,2);assert.deepEqual(calls,[1,2]);await assert.rejects(fetchDataset('tasks',async url=>JSON.stringify({page:Number(new URL(url).searchParams.get('page')),totalPages:2,total:2,dataVersion:when,data:[{id:'same',name:'Mission'}]})),/duplicate/);});
test('GZW first request in a new process refreshes fresh disk data, and new entries need no app rebuild',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gzw-launch-'));try{const opts={cacheDir:dir,bundleDir:path.join(dir,'bundled')};const first=await new GzwProvider({...opts,requestFn:requestFor()}).get();const second=await new GzwProvider({...opts,requestFn:requestFor(true)}).get();assert.equal(first.tasks.length,1);assert.equal(second.tasks.length,2);assert.equal(second.cacheState,'live');}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('GZW failed refresh preserves tasks, source date, and last successful fetch',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gzw-offline-'));try{const opts={cacheDir:dir,bundleDir:path.join(dir,'bundled')};const first=await new GzwProvider({...opts,requestFn:requestFor()}).get();const offline=await new GzwProvider({...opts,requestFn:async()=>{throw Error('Connection lost');}}).get();assert.equal(offline.cacheState,'offline');assert.equal(offline.fetchedAt,first.fetchedAt);assert.equal(offline.sourceUpdatedAt,first.sourceUpdatedAt);assert.deepEqual(offline.tasks,first.tasks);assert.match(offline.error,/Connection lost/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('GZW concurrent loads share one network refresh',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'gzw-coalesce-'));try{let calls=0;const p=new GzwProvider({cacheDir:dir,bundleDir:dir,requestFn:async url=>{calls++;return requestFor()(url);}});await Promise.all([p.get(),p.get(),p.get({refresh:true})]);assert.equal(calls,DATASETS.length);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('Starter missions resolve only to the selected faction and island-wide missions are not guessed',async()=>{const m=await import('../app/gzw-model.js');const t={location:'Kiu Vongsa , Nam Thaven , Pha Lang'};for(const [f,r]of Object.entries(m.STARTER))assert.deepEqual(m.missionRegions(t,places.regions,f).map(x=>x.id),[r]);assert.deepEqual(m.missionRegions({location:'Lamang Island'},places.regions,'mithras'),[]);assert.deepEqual(m.missionRegions({location:'Pha Lang Airfield'},places.regions,'lamang').map(r=>r.id),['pha-lang-airfield']);assert.deepEqual(m.missionRegions({location:'Khonwan Village (East of Nam Thaven)'},places.regions,'mithras'),[]);});
test('Search, region, type and progress filters compose without including completed missions',async()=>{const m=await import('../app/gzw-model.js');const tasks=[{id:'a',name:'First Recon',vendor:'Handshake',location:'Starting town',types:['Main mission']},{id:'b',name:'Other Recon',vendor:'Gunny',location:'Ban Pa',types:['Side mission']}];const f={query:'RECON',vendor:'all',region:'nam-thaven',type:'Main mission',progress:'remaining',faction:'mithras',sort:'name'};assert.deepEqual(m.filterMissions(tasks,f,m.blankProfile(),places.regions).map(t=>t.id),['a']);assert.equal(m.filterMissions(tasks,f,{...m.blankProfile(),completed:['a']},places.regions).length,0);});
test('Map backups reject mismatched geometry, invalid pins, duplicate pins, and out-of-map routes',async()=>{const m=await import('../app/gzw-model.js');const p={...m.blankProfile(),pins:[{id:'p',x:170,y:140,name:'Rally',note:'Near the road',color:'green'}],route:[{x:170,y:140}]};const b={schema:1,game:'gzw',faction:'mithras',mapRevision:map.sha256,profile:p};assert.deepEqual(m.validateBackup(b,map).profile,p);assert.throws(()=>m.validateBackup({...b,mapRevision:'old'},map),/revision/);assert.throws(()=>m.validateProfile({...p,route:[{x:999,y:140}]},map));assert.throws(()=>m.validateProfile({...p,pins:[p.pins[0],p.pins[0]]},map),/Duplicate/);});
test('Routes and nearest LZs use game-grid scale with no traversal or time claim',async()=>{const m=await import('../app/gzw-model.js');assert.equal(m.routeDistance([{x:100,y:110},{x:103,y:114}]),500);const near=m.nearestLocations({x:170,y:140},[{id:'far',x:175,y:140},{id:'near',x:171,y:140}],1);assert.equal(near[0].id,'near');assert.equal(near[0].distance,100);});
test('Focusing a location leaves space for the open details panel',async()=>{const {GzwMap}=await import('../app/gzw-map.js'),m=await import('../app/gzw-model.js');const instance={width:1000,height:700,minScale:1,maxScale:100,map,stop(){},constrain(){},draw(){}};GzwMap.prototype.focus.call(instance,[{x:170,y:140}],360);const screen=m.project({x:170,y:140},instance.camera,1000,700);assert.ok(Math.abs(screen.x-320)<.01);assert.equal(screen.y,350);});
test('Every packaged map tile exists and falls within the source image',async()=>{for(const t of map.tiles){assert.ok(t.x>=0&&t.y>=0&&t.x+t.width<=map.width&&t.y+t.height<=map.height);assert.ok((await fs.stat(path.join(__dirname,'../app',t.asset))).size>0);}for(const p of [...places.regions,...places.locations])assert.ok(p.x>=map.bounds.minX&&p.x<=map.bounds.maxX&&p.y>=map.bounds.minY&&p.y<=map.bounds.maxY);});
