const {test}=require('node:test'),assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {createLaunchBehavior}=require('../desktop/launch-behavior.cjs');
const {createLiveTrackerLaunch,chooseBounds}=require('../desktop/live-tracker-launch.cjs');
const {coordinateStartup}=require('../desktop/startup.cjs');
function storage(initial){const files=new Map(initial?[['launch-behavior.json',JSON.stringify(initial)]]:[]);let writes=0;return {files,get writes(){return writes;},readFileSync:file=>{const text=files.get(require('node:path').basename(file));if(text===undefined)throw Object.assign(Error('missing'),{code:'ENOENT'});return text;},mkdirSync(){},writeFileSync(file,value){writes++;files.set(require('node:path').basename(file),value);},renameSync(from,to){files.set(require('node:path').basename(to),files.get(require('node:path').basename(from)));files.delete(require('node:path').basename(from));}};}
function prefs(initial){const disk=storage(initial);return {disk,value:createLaunchBehavior({directory:'isolated-test',platform:'win32',storage:disk})};}
test('both launch options default off; reads do not persist or touch Windows startup',()=>{const p=prefs();assert.deepEqual(p.value.status(),{available:true,startMinimized:false,openLiveTrackerOnSession:false,message:'Saved on this PC. Windows startup is controlled separately.'});p.value.command();assert.equal(p.disk.writes,0);});
test('options persist independently and session claims are bounded and survive app restart',()=>{const p=prefs();p.value.command({action:'set',key:'startMinimized',enabled:true});assert.equal(p.value.status().openLiveTrackerOnSession,false);assert.equal(p.value.claimSession('match'),false);p.value.command({action:'set',key:'openLiveTrackerOnSession',enabled:true});assert.equal(p.value.claimSession('match'),true);assert.equal(p.value.claimSession('match'),false);const reopened=createLaunchBehavior({directory:'isolated-test',platform:'win32',storage:p.disk});assert.equal(reopened.status().startMinimized,true);assert.equal(reopened.claimSession('match'),false);for(let i=0;i<100;i++)reopened.claimSession('session-'+i);assert.equal(JSON.parse(p.disk.files.get('launch-behavior.json')).handledSessions.length,64);assert.equal(reopened.status().openLiveTrackerOnSession,true);});
test('invalid options, corrupt settings and failed persistence cannot enable or auto-open',()=>{const p=prefs();for(const input of [{action:'set',key:'launchAtLogin',enabled:true},{action:'set',key:'startMinimized',enabled:'yes'},{action:'erase'}])assert.throws(()=>p.value.command(input),/Invalid/);p.disk.writeFileSync=()=>{throw Error('full');};assert.equal(p.value.command({action:'set',key:'startMinimized',enabled:true}).saved,false);assert.equal(p.value.status().startMinimized,false);const broken=storage();broken.readFileSync=()=>'{';const service=createLaunchBehavior({directory:'isolated',platform:'win32',storage:broken});assert.equal(service.status().available,false);assert.equal(service.claimSession('a'),false);assert.equal(broken.writes,0);});
test('minimized startup never shows or focuses and preserves single-window reveal/close behavior',()=>{const main=new EventEmitter();let minimized=0,revealed=0,ready=0,callback;main.isDestroyed=()=>false;main.minimize=()=>minimized++;main.show=()=>assert.fail('Must not show');main.focus=()=>assert.fail('Must not focus');main.webContents={send:()=>revealed++};coordinateStartup({main,startMinimized:true,onReveal:()=>ready++,schedule:fn=>{callback=fn;},cancel(){}});main.emit('ready-to-show');callback();assert.equal(minimized,1);assert.equal(revealed,1);assert.equal(ready,1);});
const displays=[{id:1,workArea:{x:0,y:0,width:1920,height:1040}},{id:2,workArea:{x:-1280,y:0,width:1280,height:984}}];
function launcher(options={}){
 const p=prefs({openLiveTrackerOnSession:true}),window=new EventEmitter(),screen=new EventEmitter(),calls=[];let clock=1000;
 Object.assign(window,{isDestroyed:()=>false,isVisible:()=>true,isMinimized:()=>false,isAlwaysOnTop:()=>false,getNormalBounds:()=>({x:100,y:100,width:1480,height:980}),setMinimumSize:(...args)=>calls.push(['minimum',...args]),setBounds:b=>calls.push(['bounds',b]),webContents:{send:(...args)=>calls.push(['send',...args])},showInactive:()=>calls.push(['inactive']),show:()=>assert.fail('No activating show'),restore:()=>assert.fail('No restore'),focus:()=>assert.fail('No focus'),setAlwaysOnTop:()=>assert.fail('No always-on-top'),...options.window});
 Object.assign(screen,{getAllDisplays:()=>displays,getPrimaryDisplay:()=>displays[0],...options.screen});
 const service=createLiveTrackerLaunch({window,screen,preferences:p.value,now:()=>clock,desktopCapturer:{getSources:async input=>{assert.deepEqual(input.thumbnailSize,{width:0,height:0});return options.sources||[];},...options.capturer}});
 const event=id=>({id,kind:'public',receivedAt:clock,startedAt:clock-200});
 return {service,window,screen,calls,p,event,time:value=>clock=value,ready(){service.windowReady();service.rendererReady();}};
}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('fresh session opens existing tracker without activation once; dismissal and restart retain claim',async()=>{const f=launcher();f.ready();f.service.session(f.event('one'));await settle();assert.equal(f.calls.filter(c=>c[0]==='inactive').length,1);assert.equal(f.calls.find(c=>c[0]==='send')[1],'open-live-tracker');assert.equal(f.calls.find(c=>c[0]==='bounds')[1].x,-1280);f.window.emit('minimize');for(let i=0;i<20;i++)f.service.session(f.event('one'));await settle();assert.equal(f.calls.filter(c=>c[0]==='inactive').length,1);f.service.session(f.event('next'));await settle();assert.equal(f.calls.filter(c=>c[0]==='inactive').length,2);f.service.destroy();assert.equal(f.screen.listenerCount('display-removed'),0);});
test('disabled option, stale events and non-session activity never show or reposition',async()=>{const f=launcher();f.ready();f.p.value.command({action:'set',key:'openLiveTrackerOnSession',enabled:false});f.service.session(f.event('off'));await settle();f.p.value.command({action:'set',key:'openLiveTrackerOnSession',enabled:true});f.service.session({id:'menu',kind:'menu',receivedAt:1000});f.service.session({id:'stale',kind:'public',receivedAt:-6000});await settle();assert.equal(f.calls.length,0);f.service.destroy();});
test('first-session event waits for both renderer and startup without a second startup show',async()=>{const f=launcher();f.service.session(f.event('initial'));f.service.rendererReady();await settle();assert.equal(f.calls.length,0);f.window.emit('minimize');f.service.windowReady();await settle();assert.equal(f.calls.filter(c=>c[0]==='inactive').length,1);f.service.destroy();});
test('pending open is cancelled by manual dismissal, disabling or destruction',async()=>{for(const action of ['hide','disable','destroy']){let complete;const f=launcher({capturer:{getSources:()=>new Promise(r=>complete=r)}});f.ready();f.service.session(f.event(action));if(action==='hide')f.window.emit('hide');if(action==='disable')f.p.value.command({action:'set',key:'openLiveTrackerOnSession',enabled:false});if(action==='destroy')f.service.destroy();complete([]);await settle();assert.equal(f.calls.length,0);f.service.destroy();}});
test('known game monitor is avoided; fallback and unplugged mixed-DPI layouts stay inside DIP work areas',async()=>{const bounds=chooseBounds(displays,1,{width:3800,height:2100},2);assert.deepEqual(bounds,{x:0,y:0,width:1920,height:1040});const small=[{id:4,workArea:{x:1600,y:-600,width:800,height:600}}];assert.deepEqual(chooseBounds(small,4,{width:1480,height:980}),{x:1600,y:-600,width:800,height:600});const f=launcher({sources:[{name:'Rocket League',display_id:'2'}]});f.ready();f.service.session(f.event('monitor'));await settle();assert.ok(f.calls.find(c=>c[0]==='bounds')[1].x>=0);f.screen.getAllDisplays=()=>small;f.screen.getPrimaryDisplay=()=>small[0];f.screen.emit('display-removed');assert.deepEqual(f.calls.filter(c=>c[0]==='bounds').at(-1)[1],{x:1600,y:-600,width:800,height:600});f.service.destroy();});
test('missing display metadata and lookup failures fall back without dialogs; Quick Panel stays untouched',async()=>{const f=launcher({capturer:{getSources:async()=>{throw Error('unavailable');}}});f.ready();f.service.session(f.event('fallback'));await settle();assert.equal(f.calls.filter(c=>c[0]==='inactive').length,1);f.service.destroy();const quick=launcher({window:{isAlwaysOnTop:()=>true}});quick.ready();quick.service.session(quick.event('quick'));await settle();assert.equal(quick.calls.length,0);quick.service.destroy();});
