const {test}=require('node:test'),assert=require('node:assert/strict');
const {createLoginStartup}=require('../desktop/login-startup.cjs');
function fixture(options={}){
 let value={openAtLogin:false,executableWillLaunchAtLogin:false,launchItems:[]};const writes=[],reads=[];
 const app={isPackaged:true,getLoginItemSettings:o=>{reads.push(o);return value;},setLoginItemSettings:o=>{writes.push(o);value={openAtLogin:o.openAtLogin,executableWillLaunchAtLogin:o.enabled,launchItems:[{name:o.name,scope:'user',enabled:o.enabled}]};},...options.app};
 return {service:createLoginStartup({app,platform:'win32',installed:true,execPath:'C:\\Program Files\\Dropzone\\Dropzone.exe',...options}),writes,reads,set:v=>value=v};
}
test('startup is off by default; reads do not register or persist anything',()=>{const f=fixture();assert.equal(f.service.command().enabled,false);assert.equal(f.service.command({action:'status'}).available,true);assert.equal(f.writes.length,0);});
test('explicit opt-in and opt-out use the same installed path and query actual OS state',()=>{const f=fixture();assert.equal(f.service.command({action:'set',enabled:true}).enabled,true);assert.equal(f.service.command().enabled,true);assert.equal(f.service.command({action:'set',enabled:false}).enabled,false);assert.equal(f.writes.length,2);for(const o of [...f.reads,...f.writes]){assert.equal(o.path,'C:\\Program Files\\Dropzone\\Dropzone.exe');assert.deepEqual(o.args,[]);}assert.equal(f.writes[0].name,'com.dropzone.desktop');});
test('development, portable and other platforms cannot register startup',()=>{for(const options of [{installed:false},{app:{isPackaged:false}},{platform:'linux'}]){const f=fixture(options);assert.equal(f.service.command({action:'set',enabled:true}).available,false);assert.equal(f.writes.length,0);assert.equal(f.reads.length,0);}});
test('Windows Task Manager disabled entry is reflected without silently enabling it',()=>{const f=fixture();f.set({openAtLogin:true,executableWillLaunchAtLogin:true,launchItems:[{name:'com.dropzone.desktop',scope:'user',enabled:false}]});assert.equal(f.service.command().enabled,false);assert.match(f.service.command().message,/Disabled in Windows/);assert.equal(f.writes.length,0);});
test('invalid renderer inputs and OS errors cannot create arbitrary entries',()=>{const f=fixture();assert.throws(()=>f.service.command({action:'set',enabled:'true',path:'other.exe'}),/Invalid/);assert.throws(()=>f.service.command({action:'other'}),/Invalid/);assert.equal(f.writes.length,0);const blocked=fixture({app:{getLoginItemSettings(){throw Error('Denied');}}});assert.equal(blocked.service.command({action:'set',enabled:true}).available,false);assert.equal(blocked.writes.length,0);});
