'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {unpack,normalizeMarkers,GzwMarkersProvider}=require('../core/gzw-markers.cjs');
const {normalizeSiege,normalizeGuides,SiegeProvider}=require('../core/siege-provider.cjs');
const fixture=require('./fixtures/gzw-authorized.json'),siege=require('./fixtures/siege-official.json'),guide=require('../app/data/siege/siege-guides.json');
test('Authorized markers retain exact source coordinates, layer separation, all LZ names and faction objectives',()=>{const d=normalizeMarkers(fixture);assert.equal(d.counts.lz,55);const lz=d.markers.find(p=>p.sourceId===608);assert.ok(Math.abs(lz.x-190.032053241727)<1e-10);assert.ok(Math.abs(lz.y-131.3167556184605)<1e-10);assert.equal(lz.name,'Juliett 4');assert.ok(d.markers.some(p=>p.category===18));assert.ok(d.markers.some(p=>p.category===40));assert.ok(d.markers.some(p=>p.category===45));assert.ok(d.objectives.some(p=>p.faction==='mithras'));assert.equal(d.sourceUpdatedAt,null);assert.ok(d.markers.every(p=>!Object.hasOwn(p,'author')));});
test('Unapproved records are excluded; broken coordinates and duplicate IDs reject a full map refresh',()=>{const raw=structuredClone(fixture);raw.raw.markers['1'].markersArray[0].is_approved=false;assert.equal(normalizeMarkers(raw).counts.lz,54);raw.raw.markers['1'].markersArray[1].lng=Infinity;assert.throws(()=>normalizeMarkers(raw),/coordinates/);const dup=structuredClone(fixture);dup.raw.markers['1'].markersArray.push(dup.raw.markers['1'].markersArray[0]);assert.throws(()=>normalizeMarkers(dup),/Duplicate/);});
test('Remote map decoder cannot execute code, follow cyclic references or create prototype keys',()=>{assert.deepEqual(JSON.parse(JSON.stringify(unpack({type:'result',result:'[{"name":1,"coords":2},"Test",[3,4],7,8]'}))),{name:'Test',coords:[7,8]});for(const result of ['[{"__proto__":1},{}]','[{"self":0}]','[["Function","alert(1)"]]'])assert.throws(()=>unpack({type:'result',result}));assert.throws(()=>unpack({type:'error',result:'[]'}));});
test('Siege keeps ranked maps, attack/defense, chart population patch, and PC/console distinct',()=>{const d=normalizeSiege(siege);assert.equal(d.operators.length,78);assert.equal(d.maps.length,14);assert.equal(d.operators.find(o=>o.id==='ace').side,'attack');assert.equal(d.operators.find(o=>o.id==='noor').side,'defense');assert.ok(!d.maps.some(m=>m.id==='house'));assert.equal(d.analysis.charts.length,8);assert.ok(d.analysis.charts.every(c=>c.dataPatch==='Y11S2.3'));assert.equal(d.patch,'Y11S3');for(const platform of ['pc','console'])for(const side of ['attack','defense'])assert.equal(d.analysis.charts.filter(c=>c.platform===platform&&c.side===side).length,2);});
test('Every map recommendation names five distinct operators on the correct side; rates match exact chart URLs',()=>{const d=normalizeSiege(siege),g=normalizeGuides(guide);for(const map of d.maps){const entry=g.maps[map.id];assert.ok(entry);for(const side of ['attack','defense']){assert.equal(new Set(entry[side].map(p=>p.id)).size,5);assert.ok(entry[side].every(p=>d.operators.some(o=>o.id===p.id&&o.side===side)));}}for(const b of g.bans)assert.ok(d.analysis.charts.some(c=>c.kind==='bans'&&c.url===b.chartUrl&&c.platform===b.platform&&c.side===b.side));const wrong=structuredClone(guide);wrong.bans[0].rate=101;assert.throws(()=>normalizeGuides(wrong));});
test('Wrong-game announcements and untrusted catalog images cannot become Siege data',()=>{const bad=structuredClone(siege);bad.news=JSON.stringify({appnews:{appid:2479810,newsitems:[]}});assert.throws(()=>normalizeSiege(bad));assert.throws(()=>normalizeSiege({...siege,operators:siege.operators.replaceAll('staticctf.ubisoft.com','untrusted.example')}));});
test('Siege refreshes in a new process and offline fallback preserves the last successful snapshot',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'siege-test-'));try{let calls=0;const requestFn=async u=>{calls++;return u.includes('/operators')?siege.operators:u.includes('/maps')?siege.maps:siege.news;};const a=await new SiegeProvider({cacheDir:dir,bundleDir:dir,requestFn}).feed.get();const b=await new SiegeProvider({cacheDir:dir,bundleDir:dir,requestFn}).feed.get();assert.equal(calls,6);assert.equal(b.cacheState,'live');const offline=await new SiegeProvider({cacheDir:dir,bundleDir:dir,requestFn:async()=>{throw new Error('offline');}}).feed.get();assert.equal(offline.fetchedAt,b.fetchedAt);assert.equal(offline.analysis.publishedAt,a.analysis.publishedAt);assert.equal(offline.cacheState,'offline');}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('New map process checks even a recent disk snapshot, with offline markers and unknown publication date preserved',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'markers-test-'));try{const d={...normalizeMarkers(fixture),schema:1,feed:'gzw-markers',fetchedAt:'2026-09-07T01:00:00.000Z'};await fs.writeFile(path.join(dir,'gzw-markers.json'),JSON.stringify(d));let calls=0;const p=new GzwMarkersProvider({cacheDir:dir,bundleDir:dir,requestFn:async()=>{calls++;throw new Error('offline');}});const got=await p.get();assert.equal(calls,1);assert.equal(got.fetchedAt,d.fetchedAt);assert.equal(got.sourceUpdatedAt,null);assert.equal(got.counts.lz,55);assert.equal(got.cacheState,'offline');}finally{await fs.rm(dir,{recursive:true,force:true});}});

test('Map-only missions stay accessible without replacing existing progress IDs or duplicating objectives',async()=>{const {mergeMappedMissions,normal}=await import('../app/gzw-model.js');const d=require('../app/data/gzw/gzw-data.json'),m=require('../app/data/gzw/gzw-markers.json');const merged=mergeMappedMissions(d.tasks,m.objectives);assert.equal(merged.length,320);for(const task of d.tasks)assert.equal(merged.find(t=>t.id===task.id),task);for(const marker of m.objectives)assert.ok(merged.some(t=>normal(t.name)===normal(marker.taskName)));assert.equal(new Set(merged.map(t=>t.id)).size,merged.length);assert.deepEqual(mergeMappedMissions(merged,m.objectives),merged);});
