const {test}=require('node:test');const assert=require('node:assert/strict');
const {PlaytimeTracker}=require('../core/rocket-league-playtime.cjs');
function setup(){let now=0;const saved=[];const tracker={match:{id:'a',players:[{PrimaryId:'me',TeamNum:0},{PrimaryId:'other',TeamNum:1}],game:{PlaylistId:11}}};const timer=new PlaytimeTracker({now:()=>now,save:rows=>{saved.push(...structuredClone(rows));return true;}});return {tracker,timer,saved,tick(ms=1000,identity='me'){now+=ms;timer.sample(tracker,identity);},total(kind){timer.flush();return saved.filter(r=>!kind||r.kind===kind).reduce((n,r)=>n+r.seconds,0);}};}
test('playtime separates ranked, casual, private and freeplay, including unfinished sessions',()=>{const s=setup();for(const [id,kind] of [[11,'ranked'],[2,'casual'],[6,'private'],[9,'freeplay'],[73,'freeplay']]){s.tracker.match.id=kind+id;s.tracker.match.game.PlaylistId=id;s.tick();s.tick();s.tick();}assert.equal(s.total('ranked'),2);assert.equal(s.total('casual'),2);assert.equal(s.total('private'),2);assert.equal(s.total('freeplay'),4);});
test('playtime excludes menus, replays, pauses, ended games, unknown modes and missing players',()=>{const s=setup();s.tick();s.tick();assert.equal(s.total(),1);for(const flag of ['paused','ended']){s.tracker.match[flag]=true;s.tick();s.tick();s.tracker.match[flag]=false;}s.tracker.replaying=true;s.tick();s.tick();s.tracker.replaying=false;s.tracker.match.game.bReplay=true;s.tick();s.tick();s.tracker.match.game.bReplay=false;s.tracker.match.game.PlaylistId=999;s.tick();s.tick();s.tracker.match.game.PlaylistId=11;s.tick(1000,'absent');s.tick(1000,'absent');s.tracker.match=null;s.tick();assert.equal(s.total(),1);});
test('no time is extrapolated across gaps, resets, identity changes or disabled recording',()=>{const s=setup();s.tick();s.tick();s.tick(60000);s.timer.reset();s.tick();s.tick(1000,'other');s.tick();s.timer.sample(s.tracker,'me',false);s.tick();assert.equal(s.total(),1);s.tick();assert.equal(s.total(),2);});
test('failed writes are retained and successful flushes cannot duplicate time',()=>{let now=0,fail=true,total=0;const p=new PlaytimeTracker({now:()=>now,save:rows=>{if(fail)return false;total+=rows.reduce((s,r)=>s+r.seconds,0);return true;}}),t={match:{id:'f',game:{PlaylistId:9},players:[{PrimaryId:'me',TeamNum:0}]}};p.sample(t,'me');now=1000;p.sample(t,'me');p.reset();assert.equal(p.pending.size,1);fail=false;p.flush();p.flush();assert.equal(total,1);});
test('time spanning midnight is assigned to both days',()=>{let now=86400000-1000;const saved=[];const p=new PlaytimeTracker({now:()=>now,save:rows=>{saved.push(...rows);return true;}}),t={match:{id:'f',game:{PlaylistId:9},players:[{PrimaryId:'me',TeamNum:0}]}};p.sample(t,'me');now+=2000;p.sample(t,'me');p.flush();assert.deepEqual(saved.map(r=>[r.day,r.seconds]),[[0,1],[86400000,1]]);});

test('personal playtime follows match filters while Freeplay stays separate and old matches add no time',async()=>{
 const {JSDOM}=require('jsdom');const dom=new JSDOM('',{url:'http://localhost'});global.window=dom.window;global.document=dom.window.document;global.localStorage=dom.window.localStorage;
 const {playerProfileUI}=await import('../app/rocket-league-player-profile.js');
 const data={profile:{handle:'me'},records:[],playtime:[{day:Date.now(),kind:'ranked',seconds:3600},{day:Date.now(),kind:'casual',seconds:600},{day:Date.now(),kind:'freeplay',seconds:120},{day:Date.now()-100*86400000,kind:'freeplay',seconds:9000}]};
 const ranked=playerProfileUI(data,{personal:true,kind:'ranked',days:30});assert.match(ranked,/Ranked match time<\/dt><dd>1h 0m/);assert.match(ranked,/Freeplay time<\/dt><dd>2m 0s/);assert.match(ranked,/Your next match starts the story/);
 assert.match(playerProfileUI(data,{personal:true,days:30}),/Casual & ranked match time<\/dt><dd>1h 10m/);
 assert.match(playerProfileUI(data,{personal:false}),/aria-label="Time played"/);assert.match(playerProfileUI(data,{personal:false,kind:'casual',days:30}),/Casual match time<\/dt><dd>10m 0s/);
});

test('retained scoreboard players do not accumulate time after leaving the live roster',()=>{const s=setup();s.tick();s.tick();s.tracker.presentPlayers=[];s.tick();s.tick();assert.equal(s.total(),1);});
