const {test}=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');

test('coaching preferences capture shortcuts only in their field and preserve saved settings',async()=>{
 const dom=new JSDOM('<main></main><div id="toast"></div>',{url:'http://localhost'});Object.assign(global,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,FormData:dom.window.FormData,Event:dom.window.Event});
 global.MutationObserver=dom.window.MutationObserver;let submitted,listener,captureCalls=[];
 window.rift={coaching:async q=>{if(q.action==='shortcut-capture')captureCalls.push(q.active);if(q.action==='settings'){submitted=q.settings;return {settings:q.settings};}return {settings:{enabled:true,toggleKey:'Alt+F9',clearKey:'Control+Alt+Backspace',color:'#ffffff',tool:'arrow',thickness:6,opacity:.7,autoClear:'manual',seconds:21,rememberPosition:true,screenshots:true}};},onCoaching:callback=>{listener=callback;}};
 const ui=await import('../app/coaching-settings.js');await ui.loadCoaching();document.querySelector('main').innerHTML=ui.coachingSettings();
 const form=document.querySelector('form'),shortcut=form.querySelector('[data-coach-hotkey=toggleKey]');assert.equal(shortcut.value,'Alt + F9');assert.equal(form.elements.tool.value,'arrow');assert.equal(form.elements.thickness.type,'range');assert.equal(form.elements.opacity.type,'range');assert.equal(form.querySelector('[data-coach-delay]').hidden,true);
 shortcut.focus();const invalid=new window.KeyboardEvent('keydown',{key:'d',code:'KeyD',bubbles:true,cancelable:true});shortcut.dispatchEvent(invalid);assert.equal(form.elements.toggleKey.value,'Alt+F9');assert.equal(invalid.defaultPrevented,true);
 shortcut.dispatchEvent(new window.KeyboardEvent('keydown',{key:'c',code:'KeyC',ctrlKey:true,altKey:true,bubbles:true,cancelable:true}));assert.equal(form.elements.toggleKey.value,'Control+Alt+C');assert.equal(shortcut.value,'Ctrl + Alt + C');assert.notEqual(document.activeElement,shortcut);
 for(let i=0;i<12;i++)await Promise.resolve();assert.deepEqual(captureCalls,[true,false]);
 const outside=new window.KeyboardEvent('keydown',{key:'c',code:'KeyC',ctrlKey:true,altKey:true,bubbles:true,cancelable:true});document.body.dispatchEvent(outside);assert.equal(outside.defaultPrevented,false);
 form.querySelector('[data-coach-color="#65bbff"]').click();assert.equal(form.elements.color.value,'#65bbff');assert.equal(form.querySelector('[data-coach-color="#65bbff"]').getAttribute('aria-pressed'),'true');assert.equal(form.querySelector('[data-coach-color="#ffffff"]').getAttribute('aria-pressed'),'false');
 form.elements.opacity.value='.45';form.elements.opacity.dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(form.querySelector('[data-coach-value=opacity]').textContent,'45%');
 form.elements.autoClear.value='timer';form.elements.autoClear.dispatchEvent(new window.Event('change',{bubbles:true}));assert.equal(form.querySelector('[data-coach-delay]').hidden,false);
 form.elements.enabled.checked=false;form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await Promise.resolve();await Promise.resolve();assert.equal(submitted.enabled,false);assert.equal(Number(submitted.opacity),0.45);assert.equal(submitted.toggleKey,'Control+Alt+C');assert.equal(submitted.seconds,'21');assert.match(form.querySelector('[role=status]').textContent,/saved/);
 listener({active:true,settings:submitted});assert.ok(document.querySelector('[data-coach=toggle] svg'));assert.equal(document.querySelector('[data-coach-label]').textContent,'Drawing active');assert.equal(document.querySelector('[data-coach=toggle]').getAttribute('aria-pressed'),'true');
 assert.equal(ui.hotkeyFromEvent({key:'Tab',ctrlKey:true}),null);assert.equal(ui.hotkeyFromEvent({key:'Backspace',ctrlKey:true,altKey:true}),'Control+Alt+Backspace');assert.equal(ui.hotkeyFromEvent({key:'F9',altKey:true}),'Alt+F9');dom.window.close();
});

test('friend cards separate requests, filter locally, and never fetch or invent player statistics',async()=>{
 const dom=new JSDOM('<main></main>',{url:'http://localhost'});Object.assign(global,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,FormData:dom.window.FormData,Event:dom.window.Event});
 const ui=await import('../app/rocket-league-accounts.js');let actions=[];
 const rows=[{id:'1',handle:'backpost',display_name:'Back Post',accepted:true},{id:'2',handle:'orange',accepted:true},{id:'3',handle:'blue',accepted:true},{id:'4',handle:'striker',accepted:true},{id:'5',handle:'requester',incoming:true,accepted:false}];
 const call=async q=>{actions.push(q.action);return q.action==='account-state'?{enabled:true,user:{id:'me',email:'me@example.test'},profile:{handle:'me'}}:rows;};
 await ui.loadAccounts(call);await ui.accountAction({dataset:{account:'friends-tab',tab:'friends'}},call);document.querySelector('main').innerHTML=ui.accountsUI();
 assert.equal(document.querySelectorAll('.rl-player-card').length,4);assert.equal(document.querySelectorAll('.rl-player-card-actions [data-account=stats]').length,4);assert.doesNotMatch(document.body.textContent,/requester|online|Win rate|Sign out|Delete account/);assert.deepEqual(actions,['account-state','account-friends']);
 const search=document.querySelector('[data-friend-search]');search.value='back post';search.dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(document.querySelectorAll('.rl-player-card:not([hidden])').length,1);search.value='none';search.dispatchEvent(new window.Event('input',{bubbles:true}));assert.equal(document.querySelector('.rl-friend-search-empty').hidden,false);assert.deepEqual(actions,['account-state','account-friends']);
 await ui.accountAction({dataset:{account:'friends-tab',tab:'requests'}},call);document.querySelector('main').innerHTML=ui.accountsUI();assert.equal(document.querySelectorAll('.rl-player-card').length,1);assert.match(document.body.textContent,/requester/);assert.ok(document.querySelector('[data-account=accept]'));assert.equal(document.querySelector('[data-account=stats]'),null);
 document.querySelector('main').innerHTML=ui.accountsUI('account');assert.ok(document.querySelector('#rl-account-profile'));assert.ok(document.querySelector('[data-account-share]'));assert.ok(document.querySelector('#rl-account-delete'));assert.equal(document.querySelector('.rl-friends-grid'),null);dom.window.close();
});
