const {test}=require('node:test');
const assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const {aggregate}=require('../core/rocket-league-model.cjs');
test('tracker UI renders supported data, filters and details and releases its subscription',async()=>{
 const dom=new JSDOM('<div id="hub-app"></div><div id="toast"></div>',{url:'http://localhost/',pretendToBeVisual:true});global.window=dom.window;global.document=dom.window.document;global.localStorage=dom.window.localStorage;global.FormData=dom.window.FormData;
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const match={id:'m1',startedAt:1,status:'complete',winner:0,players:[{Name:'<Truck>',PrimaryId:'Epic|1|0',TeamNum:0,Goals:2,Assists:1,Saves:3,Shots:5,Score:612}],game:{Teams:[{TeamNum:0,Score:3},{TeamNum:1,Score:2}],TimeSeconds:102,Arena:'Stadium_P',PlaylistId:11},events:[]};
 const a=aggregate([match],'Epic|1|0'),s={status:'live',match:{...match,status:undefined},settings:{identity:'Epic|1|0',tracking:true},dataRevision:1};const calls=[];let subscription,disposed=false;
 window.rift={rocketLeague:async input=>{calls.push(input);if(input.action==='setup-check')return {installations:[{file:'C:/RocketLeague/TAGame/Config/TAStatsAPI.ini',ready:false}]};if(input.action==='setup-enable')return {installations:[{file:'C:/RocketLeague/TAGame/Config/TAStatsAPI.ini',ready:true}],result:{changed:true,backup:'test.bak'}};if(input.action==='cloud-records')return [{match_id:'m1',played_at:new Date().toISOString(),won:true,stats:{Goals:2,Shots:5,Saves:3}}];if(input.action==='state')return s;if(input.action==='analytics')return {career:a,filtered:a,recent:a,session:a};if(input.action==='history')return {total:1,matches:[match]};if(input.action==='detail')return match;return {};},onRocketLeague:callback=>{subscription=callback;return ()=>{disposed=true;};}};
 let transitions=0;global.matchMedia=()=>({matches:false});document.startViewTransition=callback=>{transitions++;const done=Promise.resolve().then(callback);return {updateCallbackDone:done,finished:done,skipTransition(){}};};
 const ui=await import('../app/rocket-league-ui.js');await ui.mountRocketLeague();assert.match(document.body.textContent,/1:42/);assert.equal(document.querySelector('Truck'),null);assert.match(document.body.textContent,/<Truck>/);
 document.querySelector('#rl-profile-toggle').click();assert.ok(document.querySelector('.rl-profile-collapsed'));assert.equal(document.querySelector('#rl-profile-toggle').getAttribute('aria-expanded'),'false');document.querySelector('#rl-profile-toggle').click();assert.equal(document.querySelector('.rl-profile-collapsed'),null);
 const wait=()=>new Promise(r=>setImmediate(r));await wait();assert.ok(document.querySelector('dialog[open]'),'First visit opens setup');assert.match(document.querySelector('dialog').textContent,/YOUR NEXT LEVEL/);document.querySelector('[data-setup=start]').click();assert.match(document.querySelector('dialog').textContent,/Your game is coming through/);assert.equal(document.querySelector('[data-setup=next]'),null,'Setup uses one status screen');document.querySelector('[data-setup=finish]').click();assert.equal(document.querySelector('dialog'),null);ui.leaveRocketLeague();await ui.mountRocketLeague();assert.equal(document.querySelector('dialog'),null,'Completed guide stays dismissed');document.querySelector('[data-rl-view=settings]').click();await wait();document.querySelector('[data-rl=tutorial]').click();await wait();assert.ok(document.querySelector('dialog[open]'),'Settings reopens guide');document.querySelector('[data-setup=close]').click();document.querySelector('[data-rl-view="personal"]').click();await wait();assert.match(document.body.textContent,/MY PROFILE/);assert.ok(document.querySelector('.rl-player-banner'));assert.ok(document.querySelector('svg'));assert.equal(document.querySelector('[data-account="profile-period"][data-days="30"]').getAttribute('aria-pressed'),'true');document.querySelector('[data-personal][data-tab="performance"]').click();await wait();assert.match(document.body.textContent,/Per-match averages/);assert.ok(document.querySelector('.rl-social-workspace'));
 const graph=document.querySelector('svg');subscription({...s,match:{...match,game:{...match.game,TimeSeconds:101}}});assert.equal(document.querySelector('svg'),graph,'Telemetry must not rebuild performance charts');
 document.querySelector('[data-rl-view="history"]').click();await wait();document.querySelector('[data-rl-match]').click();await wait();assert.doesNotMatch(document.body.textContent,/Stadium_P|Playlist 11/);assert.match(document.body.textContent,/Ranked · Doubles 2v2/);
 document.querySelector('[data-rl-view=live]').click();await wait();subscription({...s,match:null,lastMatch:{...match,ended:true},status:'connected'});assert.match(document.querySelector('#rl-content').textContent,/POST-MATCH BREAKDOWN/);assert.match(document.querySelector('#rl-content').textContent,/Victory/);subscription({...s,match:{...match,id:'next',status:undefined,ended:false}});assert.doesNotMatch(document.querySelector('#rl-content').textContent,/POST-MATCH BREAKDOWN/);assert.equal(document.querySelector('#rl-player'),null);assert.equal(document.querySelector('[data-rl-view=session]'),null);assert.equal(document.querySelector('[data-rl-view=replay]'),null);
 assert.ok(transitions>=4,'Tracker tabs and profile tabs use shared page transitions');ui.leaveRocketLeague();assert.equal(disposed,true);assert.deepEqual(calls.at(-1),{action:'visible',value:false});dom.window.close();
});
