const {test}=require('node:test'),assert=require('node:assert/strict');
const {MatchTracker}=require('../core/rocket-league-model.cjs');
const {createSessionEdges}=require('../core/rocket-league-session-edge.cjs');
function setup(){let clock=1000;const tracker=new MatchTracker({now:()=>clock}),edges=createSessionEdges({now:()=>clock}),events=[];return {tracker,edges,events,time:n=>clock=n,send(Event,Data){const msg={Event,Data};tracker.ingest(msg);const edge=edges.ingest(msg,tracker);if(edge)events.push(edge);return edge;}};}
const state=(id,playlist=11,extra={})=>({MatchGuid:id,Players:[{Name:'Fixture',PrimaryId:'fixture',TeamNum:0}],Game:{PlaylistId:playlist,TimeSeconds:300,...extra}});
function start(f,id,playlist=11){f.send('MatchCreated',{MatchGuid:id});f.send('UpdateState',state(id,playlist));f.time((f.tracker.match?.startedAt||1000)+150);return f.send('UpdateState',state(id,playlist));}
test('real start followed by fresh playable updates emits once for freeplay/private/public, independent of recording',()=>{for(const [playlist,kind] of [[9,'freeplay'],[73,'freeplay'],[6,'private'],[2,'public'],[11,'public']]){const f=setup();const edge=start(f,'one',playlist);assert.equal(edge.kind,kind);for(let i=0;i<100;i++)f.send('UpdateState',state('one',playlist));f.send('MatchInitialized',{MatchGuid:'one'});assert.equal(f.events.length,1);f.send('MatchDestroyed',{MatchGuid:'one'});f.time(5000);assert.equal(start(f,'next',playlist).id,'next');assert.equal(f.events.length,2);}});
test('process/menu presence, empty/unknown states and malformed packets do not create session starts',()=>{const f=setup();f.send('ProcessDetected',{});f.send('MatchCreated',{MatchGuid:'menu'});f.send('UpdateState',{MatchGuid:'menu',Players:[],Game:{PlaylistId:0}});f.time(1200);f.send('UpdateState',{MatchGuid:'menu',Players:[],Game:{PlaylistId:11}});f.send('MatchInitialized',null);assert.equal(f.events.length,0);});
test('a state-only active session is not a new start, including late repeated creation after connection',()=>{const f=setup();f.send('UpdateState',state('already-playing'));f.send('MatchInitialized',{MatchGuid:'already-playing'});f.time(1200);f.send('UpdateState',state('already-playing'));assert.equal(f.events.length,0);});
test('reconnect and stale starts cannot reopen; next genuinely fresh match still can',()=>{const f=setup();start(f,'one');f.edges.disconnect();f.send('MatchCreated',{MatchGuid:'one'});f.time(5000);f.send('UpdateState',state('one'));assert.equal(f.events.length,1);f.send('MatchDestroyed',{MatchGuid:'one'});f.time(6000);f.send('MatchCreated',{MatchGuid:'old'});f.time(17000);f.send('UpdateState',state('old'));f.time(18000);f.send('UpdateState',state('old'));assert.equal(f.events.length,1);f.send('MatchDestroyed',{MatchGuid:'old'});f.time(20000);start(f,'fresh');assert.equal(f.events.length,2);});
test('replay, winning screen and duplicated packets cannot trigger a fresh-session edge',()=>{for(const extra of [{bReplay:true},{bHasWinner:true}]){const f=setup();f.send('MatchCreated',{MatchGuid:'one'});f.send('UpdateState',state('one',11,extra));f.time(1200);f.send('UpdateState',state('one',11,extra));assert.equal(f.events.length,0);}const f=setup();f.send('ReplayCreated',{FileName:'fixture'});start(f,'replay');assert.equal(f.events.length,0);const g=setup();g.send('MatchCreated',{MatchGuid:'burst'});for(let i=0;i<50;i++)g.send('UpdateState',state('burst'));assert.equal(g.events.length,0);});
test('disconnect before confirmation clears pending start; JSON-string Stats API data is supported',()=>{const f=setup();f.send('MatchInitialized',JSON.stringify({MatchGuid:'one'}));f.send('UpdateState',JSON.stringify(state('one')));f.edges.disconnect();f.time(1200);f.send('UpdateState',JSON.stringify(state('one')));assert.equal(f.events.length,0);f.send('MatchDestroyed',{MatchGuid:'one'});f.time(2000);f.send('MatchInitialized',JSON.stringify({MatchGuid:'two'}));f.send('UpdateState',JSON.stringify(state('two')));f.time(2200);f.send('UpdateState',JSON.stringify(state('two')));assert.equal(f.events[0].id,'two');});
test('unchanged or backward frame numbers do not confirm freshness when supplied by telemetry',()=>{const f=setup();f.send('MatchCreated',{MatchGuid:'frames'});f.send('UpdateState',state('frames',9,{Frame:25}));f.time(1300);f.send('UpdateState',state('frames',9,{Frame:25}));f.time(1500);f.send('UpdateState',state('frames',9,{Frame:23}));assert.equal(f.events.length,0);f.time(1600);f.send('UpdateState',state('frames',9,{Frame:26}));assert.equal(f.events.length,1);});
