const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {normalizeOperator,OperatorProfiles}=require('../core/siege-operator.cjs');
const dir=path.join(__dirname,'../app/data/siege');
const html=content=>`<script>window.__PRELOADED_STATE__ = ${JSON.stringify({ContentfulGraphQl:{'OperatorDetailsContainer-example':{content}}})};</script>`;
const fixture=()=>({header:{operatorName:'Example',side:true,roles:['support'],armor:2,speed:2,difficulty:1,operatorImage:{url:'https://staticctf.ubisoft.com/portrait.png'},operatorIcon:{url:'https://staticctf.ubisoft.com/icon.png'},realName:'Example Name'},biography:'',loadout:[{title:'Example weapon',weaponType:'primary',weaponImage:{url:'https://staticctf.ubisoft.com/weapon.png'}}]});
test('operator profiles keep official facts when the narrative biography is absent',()=>{const d=normalizeOperator(html(fixture()),'example');assert.equal(d.biography.realName,'Example Name');assert.equal(d.health,2);assert.equal(d.side,'attack');assert.equal(d.loadout[0].category,'primary');assert.equal(d.sourceUrl.endsWith('/example'),true);});
test('operator profiles reject missing equipment, mismatched pages and unsafe assets',()=>{const d=fixture();d.loadout=[];assert.throws(()=>normalizeOperator(html(d),'example'),/incomplete/);assert.throws(()=>normalizeOperator(html(fixture()),'different'),/incomplete/);const bad=fixture();bad.header.operatorImage.url='https://evil.example/image.png';assert.throws(()=>normalizeOperator(html(bad),'example'),/artwork/);assert.throws(()=>new OperatorProfiles({}).get('../secrets'),/Invalid operator/);});
test('a failed live operator check preserves the bundled equipment and successful check date',async()=>{const saved=JSON.parse(fs.readFileSync(path.join(dir,'operator-noor.json')));const provider=new OperatorProfiles({bundleDir:dir,cacheDir:path.join(dir,'.missing-test-cache'),requestFn:async()=>{throw Error('Offline');}});const result=await provider.get('noor');assert.equal(result.cacheState,'offline');assert.equal(result.fetchedAt,saved.fetchedAt);assert.deepEqual(result.loadout,saved.loadout);assert.equal(result.error,'Offline');});
test('every bundled operator has complete equipment, a summary and local official artwork',()=>{
 const catalog=JSON.parse(fs.readFileSync(path.join(dir,'operator-catalog.json'))),assets=JSON.parse(fs.readFileSync(path.join(dir,'operator-assets.json'))),summaries=JSON.parse(fs.readFileSync(path.join(dir,'operator-summaries.json')));
 assert.ok(catalog.operators.length>=78);assert.equal(new Set(catalog.operators.map(o=>o.id)).size,catalog.operators.length);
 for(const c of catalog.operators){const p=JSON.parse(fs.readFileSync(path.join(dir,'operator-'+c.id+'.json')));assert.equal(p.id,c.id);assert.ok(p.biography);assert.ok(p.loadout.length);assert.ok(summaries[c.id]?.ability);for(const url of [c.image,c.icon,p.image,...p.loadout.map(w=>w.image)].filter(Boolean)){assert.ok(assets[url],`${c.id}: missing image mapping`);assert.ok(fs.existsSync(path.join(__dirname,'../app',assets[url])),`${c.id}: missing artwork file`);}}
});
