import {DrawingBoard,drawObject,hitObject,MAX_POINTS} from './drawing.js';
const $=id=>document.getElementById(id),bridge=window.coach,board=new DrawingBoard(),canvas=$('board'),draft=$('draft'),ctx=canvas.getContext('2d'),dctx=draft.getContext('2d');
let settings={},active=false,tool='pencil',color='#ffffff',thickness=4,opacity=1,layer='temporary',stroke=null,eraseBefore=null,textPoint=null,frame=0,expiryTimer=0,noticeTimer=0,drag=null,ratio=1,capturing=false,persistTimer=0,persistedObjects=null,lastPersistent=[];
const tools=[['pencil','Pencil','P','M4 20l4-1L20 7l-3-3L5 16Z'],['arrow','Arrow','A','M4 20L20 4M8 4h12v12'],['ellipse','Circle','C','M21 12a9 7 0 1 1-18 0 9 7 0 1 1 18 0'],['box','Box','B','M4 5h16v14H4Z'],['line','Line','L','M4 20L20 4'],['text','Text','T','M4 5h16M12 5v15M8 20h8'],['eraser','Stroke eraser','E','M3 14l9-10 9 8-8 9H9ZM8 9l9 8M13 21h8']];
$('tools').innerHTML=tools.map(([id,name,key,path])=>`<button data-tool="${id}" aria-label="${name}" title="${name} · ${key}"><svg viewBox="0 0 24 24"><path d="${path}"/></svg></button>`).join('');
const colors=[['Blue','#62bfff'],['Orange','#ffa143'],['White','#ffffff'],['Red','#ff5864'],['Green','#4de49b'],['Yellow','#ffe05a']];
for(const [name,value]of colors){const b=document.createElement('button');b.title=name;b.setAttribute('aria-label',name);b.dataset.color=value;b.style.background=value;$('colors').append(b);}
function notice(message){$('notice').textContent=message;$('notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.remove('show'),1600);}
function controls(){document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tool===tool));document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.color===color));$('undo').disabled=!board.undoStack.length;$('redo').disabled=!board.redoStack.length;$('thickness').value=thickness;$('opacity').value=opacity*100;$('custom').value=color;}
function persist(){clearTimeout(persistTimer);persistTimer=0;void bridge.command({action:'annotations',objects:board.objects.filter(o=>o.layer==='persistent')}).catch(e=>notice(e.message));}
function render(){if(!eraseBefore&&board.objects!==persistedObjects){persistedObjects=board.objects;const next=board.objects.filter(o=>o.layer==='persistent');if(next.length!==lastPersistent.length||next.some((o,i)=>o!==lastPersistent[i])){lastPersistent=next;clearTimeout(persistTimer);persistTimer=setTimeout(persist,350);}}ctx.clearRect(0,0,innerWidth,innerHeight);for(const o of board.objects)drawObject(ctx,o,innerWidth,innerHeight);controls();scheduleExpiry();}
function renderDraft(){frame=0;dctx.clearRect(0,0,innerWidth,innerHeight);if(stroke)drawObject(dctx,stroke,innerWidth,innerHeight);}
function invalidate(){if(!frame)frame=requestAnimationFrame(renderDraft);}
function resize(){ratio=settings.lowResource==='low'?1:Math.min(devicePixelRatio||1,2);for(const c of [canvas,draft]){c.width=Math.round(innerWidth*ratio);c.height=Math.round(innerHeight*ratio);c.getContext('2d').setTransform(ratio,0,0,ratio,0,0);}render();renderDraft();placeToolbar();}
function placeToolbar(){const t=$('toolbar'),p=settings.rememberPosition?settings.toolbar:null;t.style.left=Math.round(Math.max(8,Math.min(innerWidth-t.offsetWidth-8,(p?.x??.02)*innerWidth)))+'px';t.style.top=Math.round(Math.max(8,Math.min(innerHeight-t.offsetHeight-8,(p?.y??.12)*innerHeight)))+'px';placeOptions();}
function placeOptions(){const r=$('toolbar').getBoundingClientRect();$('settings').style.left=Math.max(8,Math.min(innerWidth-238,r.right+10))+'px';$('settings').style.top=Math.max(8,Math.min(innerHeight-410,r.top))+'px';}
function scheduleExpiry(){clearTimeout(expiryTimer);if(!active)return;const deadlines=board.objects.map(o=>o.expires).filter(Boolean);if(deadlines.length)expiryTimer=setTimeout(()=>{board.expire(Date.now());render();},Math.max(10,Math.min(...deadlines)-Date.now()));}
function point(e){return {x:Math.max(0,Math.min(1,e.clientX/innerWidth)),y:Math.max(0,Math.min(1,e.clientY/innerHeight))};}
function object(p){return {tool,color,width:thickness/Math.min(innerWidth,innerHeight),opacity,layer,points:[p],expires:layer==='temporary'&&settings.autoClear==='timer'?Date.now()+settings.seconds*1000:0};}
function erase(e){const index=board.objects.findLastIndex(o=>hitObject(ctx,o,e.clientX*ratio,e.clientY*ratio,innerWidth,innerHeight));if(index>=0){board.objects=board.objects.filter((_,i)=>i!==index);render();}}
draft.addEventListener('pointerdown',e=>{if(!active||e.button!==0||capturing)return;$('settings').hidden=true;clearTimeout(expiryTimer);const p=point(e);if(tool==='text'){textPoint=p;$('text-entry').hidden=false;$('text-entry').style.left=Math.min(e.clientX,innerWidth-270)+'px';$('text-entry').style.top=Math.min(e.clientY,innerHeight-60)+'px';$('text-entry').querySelector('input').focus();return;}draft.setPointerCapture(e.pointerId);if(tool==='eraser'){eraseBefore=board.objects;erase(e);}else{stroke=object(p);invalidate();}});
draft.addEventListener('pointermove',e=>{if(eraseBefore){erase(e);return;}if(!stroke)return;const events=e.getCoalescedEvents?.()||[e];for(const ev of events){const p=point(ev),last=stroke.points.at(-1);if(tool!=='pencil')stroke.points=[stroke.points[0],p];else if(stroke.points.length<MAX_POINTS&&Math.hypot((p.x-last.x)*innerWidth,(p.y-last.y)*innerHeight)>1.5)stroke.points.push(p);}invalidate();});
function finish(){if(stroke){board.add(stroke);stroke=null;render();invalidate();}if(eraseBefore){const next=board.objects;board.objects=eraseBefore;if(next!==eraseBefore)board.commit(next);eraseBefore=null;render();}}
draft.addEventListener('pointerup',finish);draft.addEventListener('pointercancel',finish);
$('text-entry').addEventListener('submit',e=>{e.preventDefault();const input=$('text-entry').querySelector('input'),text=input.value.trim();if(text&&textPoint)board.add({...object(textPoint),tool:'text',text});input.value='';$('text-entry').hidden=true;textPoint=null;render();draft.focus();});
function clear(){finish();board.clear();render();}
async function exit(){if(persistTimer)persist();active=false;stroke=null;eraseBefore=null;if(frame)cancelAnimationFrame(frame);frame=0;clearTimeout(expiryTimer);$('text-entry').hidden=true;$('settings').hidden=true;await bridge.command({action:'exit'});}
async function capture(){if(capturing)return;finish();capturing=true;try{const {image}=await bridge.command({action:'frame'}),img=new Image();img.src=image;await img.decode();const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const context=c.getContext('2d');context.drawImage(img,0,0);for(const o of board.objects)drawObject(context,o,c.width,c.height);await bridge.command({action:'save',image:c.toDataURL('image/png')});notice('ANNOTATED SCREENSHOT SAVED');if(settings.autoClear==='screenshot'){board.clear(true);render();}}catch(e){notice(e.message);}finally{capturing=false;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tool){finish();tool=b.dataset.tool;controls();}if(b.dataset.color){color=b.dataset.color;controls();}});
$('undo').onclick=()=>{finish();board.undo();render();};$('redo').onclick=()=>{finish();board.redo();render();};$('clear').onclick=clear;$('capture').onclick=capture;$('exit').onclick=exit;
$('options').onclick=()=>{$('settings').hidden=!$('settings').hidden;$('options').setAttribute('aria-expanded',!$('settings').hidden);placeOptions();};
$('thickness').oninput=e=>thickness=Number(e.target.value);$('opacity').oninput=e=>opacity=Number(e.target.value)/100;$('custom').oninput=e=>{color=e.target.value;controls();};$('layer').onchange=e=>layer=e.target.value;
$('preset').onchange=e=>{const presets={rotation:['arrow','#62bfff',5],player:['ellipse','#ffa143',4],ball:['arrow','#ffffff',3],pass:['line','#4de49b',4],danger:['box','#ff5864',5]};const preset=presets[e.target.value];if(preset){[tool,color,thickness]=preset;controls();}e.target.value='';};
$('grip').onpointerdown=e=>{drag={x:e.clientX-$('toolbar').offsetLeft,y:e.clientY-$('toolbar').offsetTop};e.target.setPointerCapture(e.pointerId);};
$('grip').onpointermove=e=>{if(!drag)return;const t=$('toolbar');t.style.left=Math.max(8,Math.min(innerWidth-t.offsetWidth-8,e.clientX-drag.x))+'px';t.style.top=Math.max(8,Math.min(innerHeight-t.offsetHeight-8,e.clientY-drag.y))+'px';placeOptions();};
$('grip').onpointerup=async()=>{if(!drag)return;drag=null;const t=$('toolbar');let x=t.offsetLeft;if(x<36)x=8;if(x>innerWidth-t.offsetWidth-36)x=innerWidth-t.offsetWidth-8;settings.toolbar={x:x/innerWidth,y:t.offsetTop/innerHeight};placeToolbar();try{await bridge.command({action:'settings',settings:{toolbar:settings.toolbar}});}catch(e){notice(e.message);}};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();void exit();return;}if(e.target.matches('input,select'))return;const k=e.key.toLowerCase();if(e.ctrlKey&&['z','y','s'].includes(k)){e.preventDefault();if(k==='s')void capture();else{finish();k==='y'||e.shiftKey?board.redo():board.undo();render();}return;}if(e.key==='Delete'){e.preventDefault();clear();return;}const found=tools.find(t=>t[2].toLowerCase()===k);if(found){finish();tool=found[0];controls();}});
bridge.onClear(()=>{if(active)clear();});bridge.onSettings(s=>{settings=s;controls();placeToolbar();});bridge.onMode(value=>{active=typeof value==='object'?value.active:value;document.body.classList.toggle('activate',active);if(active){if(!value.resume){tool=settings.tool||'pencil';color=settings.color||'#ffffff';thickness=settings.thickness||4;opacity=settings.opacity||1;}board.expire(Date.now());resize();notice(value.replay?'REPLAY COACHING · ESC TO EXIT':'COACH MODE · ESC TO EXIT');}else{if(persistTimer)persist();clearTimeout(expiryTimer);if(frame)cancelAnimationFrame(frame);frame=0;stroke=null;eraseBefore=null;$('settings').hidden=true;$('text-entry').hidden=true;}});
window.addEventListener('resize',()=>{if(active)resize();});const initial=await bridge.command({action:'state'});settings=initial.settings;board.objects=initial.annotations||[];persistedObjects=board.objects;lastPersistent=board.objects;controls();
