'use strict';
const {SourceCache,requestText}=require('./source-cache.cjs');
const SOURCES={legends:'https://help.ea.com/en/articles/apex-legends/abilities/',news:'https://www.ea.com/games/apex-legends/apex-legends/news',esports:'https://algs.ea.com/en/news'};
function nextData(html){const match=html.match(/<script id="__NEXT_DATA__" type="application\/json">([\s\S]*?)<\/script>/);if(!match)throw new Error('Official page format changed.');return JSON.parse(match[1]).props.pageProps;}
const text=node=>node?.value||node?.content?.map(text).join('')||'';
function abilityNames(body){const result=[];function walk(node){if(node.nodeType==='paragraph'){const value=text(node).trim();const m=value.match(/^(Tactical|Passive|Ultimate|Second Passive):\s*(.+?)\.?$/);if(m)result.push({type:m[1],name:m[2]});}for(const child of node.content||[])walk(child);}walk(JSON.parse(body));return result;}
function normalizeLegends(html){const d=nextData(html).pageData,legends=[];for(const section of d.section.items){if(!/^(Assault|Controller|Recon|Skirmisher|Support) Legends$/.test(section.title))continue;const role=section.title.split(' ')[0];for(const block of section.objects)for(const faq of block.data.faqs||[]){const body=faq.answers.find(a=>a.type==='TextBlock')?.data.body;if(body)legends.push({name:faq.question.trim(),role,abilities:abilityNames(body)});}}
 const newest=d.section.items.find(s=>s.title.includes('newest'));const body=newest?.objects.find(o=>o.type==='TextBlock')?.data.body;const description=body?text(JSON.parse(body)):'';const name=description.match(/^([\w -]+) is the newest/)?.[1];if(name&&!legends.some(l=>l.name===name)){const role=description.match(/\b(?:a|an) (Assault|Controller|Recon|Skirmisher|Support) Legend/)?.[1];if(!role)throw new Error('New legend class was not supplied.');const segment=newest.objects.find(o=>o.type==='SegmentBlock')?.data.segments.find(s=>s.segmentButton==='Abilities');legends.push({name,role,abilities:segment?abilityNames(segment.objects[0].data.body):[]});}
 if(legends.length<20||new Set(legends.map(l=>l.name)).size!==legends.length||legends.some(l=>!l.abilities.length))throw new Error('Official legend catalog is incomplete.');return{sourceUrl:SOURCES.legends,updatedAt:d.articleTitle.lastUpdated,legends:legends.sort((a,b)=>a.name.localeCompare(b.name))};}
function normalizeNews(html){const d=nextData(html).initialNewsData,seen=new Set(),articles=[];for(const row of [d.featured,...d.items].filter(Boolean)){if(seen.has(row.slug)||!/^[a-z0-9-]+$/.test(row.slug)||!row.title||!Number.isFinite(Date.parse(row.publishingDate)))continue;seen.add(row.slug);articles.push({title:row.title,publishedAt:row.publishingDate,url:SOURCES.news+'/'+row.slug,imageUrl:row.image?.ar16X9||null});}if(!articles.length)throw new Error('Official news index is empty.');return articles.slice(0,16);}
const plain=s=>s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#x27;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
function normalizeEsports(html){const articles=[],seen=new Set();for(const match of html.matchAll(/<a\b[^>]*href="(\/en\/news\/[a-z0-9-]+)"[^>]*>([\s\S]*?)<\/a>/g)){if(seen.has(match[1]))continue;const body=match[2],title=body.match(/<h[234]\b[^>]*>([\s\S]*?)<\/h[234]>/)?.[1];if(!title)continue;seen.add(match[1]);const date=body.match(/<time\b[^>]*datetime="([^"]+)"/)?.[1]||null;articles.push({title:plain(title),url:'https://algs.ea.com'+match[1],publishedAt:date,imageUrl:body.match(/<img\b[^>]*src="([^"]+)"/)?.[1]?.replace(/^\/\//,'https://')||null});}if(!articles.length)throw new Error('Official ALGS news format changed.');return articles.slice(0,12);}
function normalizeContent(raw){return{source:'EA / Respawn and ALGS official pages',sourceUrl:SOURCES.news,catalog:normalizeLegends(raw.legends),news:normalizeNews(raw.news),esports:normalizeEsports(raw.esports)};}
class ApexContentProvider{constructor(options){const request=options.requestFn||requestText;this.feed=new SourceCache({...options,id:'apex-content',url:SOURCES.news,requestFn:async()=>Object.fromEntries(await Promise.all(Object.entries(SOURCES).map(async([key,url])=>[key,await request(url)]))),normalize:normalizeContent,validate:d=>d.catalog?.legends?.length>=20&&d.news?.length>0&&d.esports?.length>0});}get(options={}){if(!options||typeof options!=='object'||Array.isArray(options))throw new Error('Invalid Apex content request.');return this.feed.get(options.refresh===true||options.refresh==='true');}}
module.exports={ApexContentProvider,SOURCES,normalizeContent,normalizeLegends,normalizeNews,normalizeEsports};
