'use strict';
const JSON5=require('json5');
const SOURCE='https://wardogservers.com/';
function parse(html){const m=html.match(/node_ids:\s*\[[^\]]*\],\s*data:\s*([\s\S]*?),\s*form: null/);if(!m)throw Error('Server source format changed.');const d=JSON5.parse(m[1])[1]?.data;if(!Array.isArray(d?.page)||!Number.isInteger(d.total)||!d.meta?.fetchedAt||d.failure)throw Error('Server directory unavailable.');const rows=d.page.map(s=>{if(typeof s.id!=='string'||typeof s.name!=='string'||!Number.isFinite(s.players)||!Number.isFinite(s.max))throw Error('Invalid server record.');return {id:s.id,code:s.code,name:s.name,official:s.official,region:s.region,players:s.players,max:s.max,reserved:s.reserved,locked:s.locked,map:s.variant,mode:s.experience,rulesets:s.rulesets};});return {rows,total:d.total,totals:d.totals,all:d.all,facets:d.facets,meta:d.meta};}
class ServersProvider{
 constructor({fetcher=fetch}={}){this.fetcher=fetcher;this.cache=new Map();this.pending=new Map();}
 async get(input={}){const params=new URLSearchParams();for(const k of ['q','region','type','ruleset','map','hideEmpty','hideFull','password','sort','dir','page']){if(typeof input[k]==='string'&&input[k].length<=120)params.set(k,input[k]);}const key=params.toString(),cached=this.cache.get(key);if(cached&&Date.now()-cached.checked<60000)return cached.data;if(this.pending.has(key))return this.pending.get(key);const task=this.load(key,cached).finally(()=>this.pending.delete(key));this.pending.set(key,task);return task;}
 async load(key,cached){try{const r=await this.fetcher(SOURCE+'?'+key,{signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('Source returned '+r.status);let html='';for await(const c of r.body){html+=Buffer.from(c).toString('utf8');if(html.length>3000000)throw Error('Response too large.');}const d=parse(html),data={...d,source:SOURCE,stale:!!d.meta.stale||Date.now()-Date.parse(d.meta.fetchedAt)>180000};if(this.cache.size>=40)this.cache.delete(this.cache.keys().next().value);this.cache.set(key,{checked:Date.now(),data});return data;}catch{return cached?{...cached.data,stale:true,error:'Refresh failed. Showing the previous snapshot.'}:{rows:[],error:'The live server directory could not be retrieved. Try again shortly.',stale:true};}}
}
module.exports={ServersProvider,parse};
