import {e,opts,date} from './shared.js';
import context from './data/apex/meta-context.json' with {type:'json'};

const classes=['Assault','Controller','Recon','Skirmisher','Support'];
const source=(key,label)=>{const item=context.sources[key];return item?`<button class="source-link" data-hub-source="${e(item.url)}">${e(label||item.label)} <span aria-hidden="true">↗</span></button>`:'';};
// Crop supplied EA artwork in CSS; retain originals and attribution.
const portrait=(name,art)=>{const image=art?.legends?.find(row=>row.name===name);return image?`<span class="am-portrait" aria-hidden="true"><img src="${e(image.localPath)}" alt="" loading="lazy"></span>`:`<span class="am-portrait am-portrait-missing" aria-hidden="true">${e(name.slice(0,1))}</span>`;};
const presence=count=>Number((count/context.event.denominator*100).toFixed(1))+'%';

export function apexMetaRoster(data,art,{query='',role='all'}={}){
 return (data?.catalog?.legends||[]).map(row=>{
  const name=String(row.name||'').trim(),image=art?.legends?.find(item=>item.name===name);
  // EA Help still assigns Ash/Revenant older classes; use the character index.
  return {...row,name,role:image?.role||row.role,art:image,identity:context.identity[name]||'See the documented abilities below.',abilities:Array.isArray(row.abilities)?row.abilities:[]};
 }).filter(row=>(role==='all'||row.role===role)&&(!query||[row.name,row.role,row.identity,...row.abilities.map(a=>a.name)].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())));
}
function roleDetails(row){return `<details><summary>Utility & tradeoff</summary><dl><div><dt>Offers</dt><dd>${e(row.strength)}</dd></div><div><dt>Consider</dt><dd>${e(row.tradeoff)}</dd></div></dl>${source(row.source)}${row.source==='patch'?source('abilities'):''}</details>`;}
function balanceBrief(art){
 return `<section class="am-section am-overview" aria-labelledby="am-balance"><header class="am-section-heading"><div><span class="am-kicker">September 15 midseason update</span><h2 id="am-balance">What changed this split</h2></div>${source('patch','Patch notes')}</header><div class="am-balance-list">${context.balance.slice(0,3).map(row=>{const role=context.roles.find(role=>role.name===row.name);return `<article class="am-balance am-role" data-legend="${e(row.name)}">${portrait(row.name,art)}<div><span class="am-kicker">${e(row.direction)}</span><h3>${e(row.name)}</h3><p>${e(row.summary)}</p>${role?roleDetails(role):''}</div></article>`;}).join('')}</div><div class="am-other-balance">${context.balance.slice(3).map(row=>`<div><strong>${e(row.name)}</strong><p>${e(row.summary)}</p></div>`).join('')}</div></section>`;
}
function lineup(names,art){return `<div class="am-lineup">${names.map(name=>`<div>${portrait(name,art)}<strong>${e(name)}</strong></div>`).join('')}</div>`;}
function competitiveContext(art){
 const event=context.event;
 return `<section class="am-section am-event" aria-labelledby="am-compositions"><header class="am-section-heading"><div><span class="am-kicker">${e(event.scope)} · ${date(event.playedAt)}</span><h2 id="am-compositions">Teams at the Americas finals</h2><p>${e(event.name)} · ${e(event.season)}. Played before the September 15 balance update.</p></div>${source('algs','Event data')}</header><div class="am-compositions">${event.compositions.map(row=>`<article class="am-composition">${lineup(row.legends,art)}<div class="am-composition-purpose"><p>${e(row.purpose)}</p><details><summary>Use & tradeoff</summary><p>${e(row.tradeoff)}</p>${source('abilities','Kit reference')}</details></div><div class="am-composition-count"><strong>${presence(row.occurrences)}</strong><span>of team-match lineups</span></div></article>`).join('')}</div><div class="am-presence-heading"><h3>Legend presence in this event</h3><span>Team-match selections</span></div><div class="am-presence">${event.legends.map(row=>`<div>${portrait(row.name,art)}<span><strong>${e(row.name)}</strong><b>${presence(row.occurrences)}</b></span></div>`).join('')}</div><details class="am-method"><summary>Counts, bans & source methodology</summary><p>${e(event.method)} These are not ranked pick rates. Current post-patch strength and ranked pick rates remain unverified.</p><p>${event.teams} teams × ${event.matches} matches = ${event.denominator} team-matches. ${event.legends.map(row=>`${e(row.name)}: ${row.occurrences} / ${event.denominator} team-matches`).join('; ')}.</p><p>Lineup counts: ${event.compositions.map(row=>`${e(row.legends.join(' / '))}: ${row.occurrences} / ${event.denominator}`).join('; ')}. The lineup purpose and tradeoffs describe documented kits, not measured performance.</p><p>Reviewed ${date(context.reviewedAt)}. The statistics provider labels this region “North America”; the official competition is Americas.</p><div>${source('algs')}${source('event')}${source('rules')}</div></details></section>`;
}
function directory(data,art,query,role){
 const roster=apexMetaRoster(data,art,{query,role});
 return `<section class="am-section am-directory operators-page" aria-labelledby="am-directory"><header class="am-section-heading"><div><h2 id="am-directory">All legends</h2><p>Choose a legend to explore their kit.</p></div><span class="am-count" role="status">${roster.length} legends</span></header><div class="am-directory-tools"><label><span class="sr-only">Find a legend or ability</span><input id="apex-query" type="search" placeholder="Find a legend, role or ability" value="${e(query)}"></label><label><span class="sr-only">Legend class</span><select id="apex-role">${opts([['all','All classes'],...classes.map(c=>[c,c])],role)}</select></label></div><div class="am-directory-list operator-grid" aria-label="Legend roster">${roster.map(row=>`<button type="button" class="operator-card am-legend-banner" data-apex-legend-open="${e(row.name)}" aria-label="View ${e(row.name)} abilities"><span class="operator-portrait">${row.art?`<img src="${e(row.art.localPath)}" alt="" loading="lazy">`:''}</span><span class="operator-card-shade"></span><span class="operator-card-info"><strong>${e(row.name)}</strong><small class="am-legend-class">${e(row.role)}</small></span><span class="operator-card-arrow" aria-hidden="true">↗</span></button>`).join('')||'<p class="am-empty" role="status">No legends match. Clear the search or choose another class.</p>'}</div><details class="am-directory-sources"><summary>Roster sources & coverage</summary><p>All ${data?.catalog?.legends?.length||0} legends in the supplied official roster. Classes and artwork: EA character index, checked ${date(art?.checkedAt)}. Ability names: EA Help, updated ${date(data?.catalog?.updatedAt)}.</p><p>EA Help still lists older classes for Ash and Revenant; displayed classes follow the character index. Dated patch notes take precedence over older ability descriptions.</p><div>${source('classes')}${source('abilities')}${source('patch')}</div></details></section>`;
}
function legendDetail(row,data){
 const utility=context.roles.find(item=>item.name===row.name);
 return `<section class="am-legend-detail"><button class="source-link am-directory-back" data-apex-legend-back>← All legends</button><div class="am-legend-hero"><div class="am-legend-art">${row.art?`<img src="${e(row.art.localPath)}" alt="${e(row.name)}">`:''}</div><div><span class="am-kicker">${e(row.role)}</span><h2>${e(row.name)}</h2><p class="am-legend-purpose">${e(row.identity)}</p><dl class="am-abilities">${row.abilities.map(ability=>`<div><dt>${e(ability.type)}</dt><dd>${e(ability.name)}</dd></div>`).join('')}</dl>${utility?`<p>${e(utility.strength)}</p><p class="am-legend-tradeoff"><strong>Tradeoff:</strong> ${e(utility.tradeoff)}</p>`:''}<button class="source-link" data-hub-source="${e(row.art?.sourceUrl||data?.catalog?.sourceUrl||context.sources.classes.url)}">Full legend guide on EA ↗</button></div></div><div class="am-detail-sources">${source('abilities','Ability reference')}${source('patch','Current balance notes')}</div></section>`;
}
const guideViews=[['picks','Recommended'],['teams','Team ideas'],['directory','All legends'],['evidence','Patch & data']];
function recommended(art,roster){
 return `<section class="am-recommendations" aria-labelledby="am-picks-title"><header class="am-guide-intro"><h2 id="am-picks-title">Choose your next legend</h2><p>Three picks for this split. Start with the job you want to do.</p></header><div class="am-picks">${context.recommendations.map(pick=>{
  const role=context.roles.find(row=>row.name===pick.name),legend=roster.find(row=>row.name===pick.name);
  return `<article class="am-pick" data-legend="${e(pick.name)}">${portrait(pick.name,art)}<div class="am-pick-name"><span>${e(legend?.role||role.purpose)}</span><h3>${e(pick.name)}</h3></div><div class="am-pick-copy"><h4>${e(pick.purpose)}</h4><p>${e(pick.reason)}</p><details><summary>Play it well</summary><p>${e(pick.use)}</p><p><strong>Watch for:</strong> ${e(role.tradeoff)}</p><div>${source('patch','Balance notes')}${source('abilities','Abilities')}</div></details></div></article>`;
 }).join('')}</div><div class="am-guide-next"><p>Editorial picks based on the September 15 balance update and documented kits.</p><button class="source-link" data-apex-meta-view="teams">Build a team around your pick <span aria-hidden="true">→</span></button></div></section>`;
}
function suggestedTeams(art){
 return `<section aria-labelledby="am-teams-title"><header class="am-guide-intro"><h2 id="am-teams-title">Give every teammate a job</h2><p>Suggested lineups built around complementary abilities.</p></header><div class="am-team-ideas">${context.compositions.map(row=>`<article class="am-team-idea">${lineup(row.legends,art)}<div><h3>${e(row.name)}</h3><p>${e(row.purpose)}</p><details><summary>When to use it</summary><p>${e(row.useCase)}</p><p><strong>Tradeoff:</strong> ${e(row.tradeoff)}</p><p>${e(row.strength)}</p><div>${row.sources.map(key=>source(key)).join('')}</div></details></div></article>`).join('')}</div><p class="am-guide-footnote">Editorial team ideas, not measured win-rate rankings. Historical tournament lineups are in Patch & data.</p></section>`;
}
function evidence(art){
 return `<div class="am-evidence"><details class="am-pick-method"><summary>How we choose the recommendations</summary><p>We recommend Conduit for shield support, Fuse for explosive pressure and Catalyst for holding space because the September 15 update strengthens or streamlines those jobs. These are editorial choices based on documented kits, not a statistical ranking. The September 13 event below predates the patch and does not determine these picks.</p><p>Reviewed ${date(context.reviewedAt)}. No verified post-patch ranked win-rate comparison is included.</p>${source('design','Developer reasoning')}${source('patch','Full balance notes')}</details>${balanceBrief(art)}<details class="am-history"><summary>Historical ALGS lineups <span>September 13 · before the patch</span></summary>${competitiveContext(art)}</details></div>`;
}
export function renderApexMeta({data,art,query='',role='all',view='picks',selectedLegend=null}){
 const selected=guideViews.some(([id])=>id===view)?view:'picks',roster=apexMetaRoster(data,art);
 const legend=selectedLegend&&roster.find(row=>row.name===selectedLegend);
 const content=selected==='directory'&&legend?legendDetail(legend,data):selected==='teams'?suggestedTeams(art):selected==='directory'?directory(data,art,query,role):selected==='evidence'?evidence(art):recommended(art,roster);
 return `<div class="apex-meta" data-meta-view="${selected}"><header class="am-heading"><div><span class="hub-eyebrow">${e(context.season)}</span><h1>Legends & Meta</h1></div><span>Reviewed ${date(context.reviewedAt)}</span></header><nav class="am-guide-nav" aria-label="Legend guide sections">${guideViews.map(([id,label])=>`<button type="button" data-apex-meta-view="${id}" aria-pressed="${selected===id}">${label}</button>`).join('')}</nav>${content}</div>`;
}
