import {e,dateTime} from './shared.js';
// Internal Dropzone display contract. No upstream field guessing lives here.
const platforms={PC:'PC / EA',PS4:'PlayStation',X1:'Xbox',SWITCH:'Nintendo Switch'};
const text=(value,max=100)=>typeof value==='string'?value.trim().slice(0,max):'';
const asset=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&['apexlegendsstatus.com','api.apexlegendsstatus.com','cdn.apexlegendsstatus.com','api.mozambiquehe.re'].includes(u.hostname)&&/\.(png|jpg|jpeg|webp)$/i.test(u.pathname)?u.origin+u.pathname:null;}catch{return null;}};
const number=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null;
export function playerProfile(value){
 if(value?.schema!==1||!text(value.identity?.name)||!/^\d{1,20}$/.test(value.identity?.uid||'')||!platforms[value.identity?.platform])return null;
 const metric=row=>text(row?.label)&&number(row?.value)!==null?{label:text(row.label),value:row.value}:null;
 const ranks=Array.isArray(value.ranks)?value.ranks.slice(0,3).flatMap(row=>text(row?.mode)&&text(row?.name)?[{mode:text(row.mode),name:text(row.name),score:number(row.score),division:number(row.division),emblem:asset(row.emblem),season:text(row.season)}]:[]):[];
 return {schema:1,identity:{name:text(value.identity.name,64),uid:value.identity.uid,platform:value.identity.platform},level:number(value.level),prestige:number(value.prestige),banner:asset(value.banner),metrics:(Array.isArray(value.metrics)?value.metrics:[]).slice(0,8).map(metric).filter(Boolean),selectedLegend:text(value.selectedLegend),checkedAt:Number.isFinite(Date.parse(value.checkedAt))?value.checkedAt:null,ranks,legends:(Array.isArray(value.legends)?value.legends:[]).slice(0,40).flatMap(row=>text(row?.name)?[{name:text(row.name),trackers:(Array.isArray(row.trackers)?row.trackers:[]).slice(0,12).map(metric).filter(Boolean)}]:[])};
}
export function renderPlayerProfile(profile,art,favorite=false){
 const seasonLabel=value=>{const match=/^br_ranked_s(\d+)_s(\d+)$/.exec(value||'');return match?`Season ${match[1]} · Split ${match[2]}`:'';};
 const portrait=name=>art.legends.find(row=>row.name.toLowerCase()===name.toLowerCase())?.localPath;
 const banner=portrait(profile.selectedLegend)||profile.banner,identity=profile.identity;
 return `<section class="apex-profile" aria-label="Player profile"><div class="apex-profile-overview"><header class="apex-profile-banner">${banner?`<img src="${e(banner)}" alt="${e(profile.selectedLegend)}" class="apex-profile-art">`:''}<div class="apex-profile-identity"><span class="apex-game-label">${e(platforms[identity.platform])}</span><h2>${e(identity.name)}</h2><p>${profile.level!==null?`Level ${profile.level.toLocaleString()}${profile.prestige?` · Prestige ${profile.prestige}`:''} · `:''}${profile.selectedLegend?e(profile.selectedLegend):'Player profile'}</p><small class="apex-player-id">Player UID ${e(identity.uid)}</small><button class="apex-favorite" data-apex-favorite aria-pressed="${favorite}">${favorite?'★ Favorited':'☆ Favorite'}</button></div></header><div class="apex-profile-body"><div class="apex-section-heading"><h3>Ranked overview</h3><span>${profile.checkedAt?'Checked '+dateTime(profile.checkedAt):'Check time unavailable'}</span></div><div class="apex-summary"><div class="apex-ranks">${profile.ranks.map(rank=>`<section class="apex-rank">${rank.emblem?`<img src="${e(rank.emblem)}" alt="" class="apex-rank-emblem">`:''}<div><span>${e(rank.mode)}${seasonLabel(rank.season)?` · ${e(seasonLabel(rank.season))}`:''}</span><strong>${e(rank.name)}${rank.division?` ${rank.division}`:''}</strong>${rank.score!==null?`<p><b>${rank.score.toLocaleString()}</b> RP</p>`:''}</div></section>`).join('')||'<p class="apex-empty">The provider did not supply a current rank.</p>'}</div>${profile.metrics.length?`<dl class="apex-career-metrics">${profile.metrics.map(m=>`<div><dt>${e(m.label)}</dt><dd>${m.value.toLocaleString()}</dd></div>`).join('')}</dl>`:''}</div></div></div><div class="apex-tracker-section"><div class="apex-section-heading"><h3>Legend trackers</h3><span>Available equipped trackers</span></div><p class="apex-tracker-note">These are the trackers returned by the provider. They may cover different periods and do not represent a complete career total.</p><div class="apex-profile-legends">${profile.legends.filter(l=>l.trackers.length).map(l=>`<section class="apex-profile-legend">${portrait(l.name)?`<img src="${e(portrait(l.name))}" alt="">`:''}<div><h4>${e(l.name)}</h4><dl>${l.trackers.map(t=>`<div><dt>${e(t.label)}</dt><dd>${t.value.toLocaleString()}</dd></div>`).join('')}</dl></div></section>`).join('')||'<p class="apex-empty">No legend trackers were supplied for this player.</p>'}</div></div></section>`;
}
