import {$,api,e,opts,date,dateTime,stored,persist} from './shared.js';
import {sourceStatus} from './source-status.js';
import {playerProfile,renderPlayerProfile} from './apex-profile.js';
import bundle from './data/apex/apex-content.json' with {type:'json'};
import art from './data/apex/legend-art.json' with {type:'json'};
import balance from './data/apex/balance-context.json' with {type:'json'};
let active=false,revision=0,lookupRevision=0,data=bundle,page='overview',query='',role='all',loading=false,searching=false;
let service={available:false,status:'setup-required',message:'Player lookup requires secure provider configuration.'};
let profile=null,lookupMessage='',playerName='',platform='PC',historyTab='recent',identifierMode='name';
let cooldownUntil=0,cooldownTimer=null;
const canLookup=()=>service.available&&!searching&&Date.now()>=cooldownUntil;
const platformNames={PC:'PC / EA',PS4:'PlayStation',X1:'Xbox',SWITCH:'Nintendo Switch'};
const historyKey='dropzone-apex-players-v1';
function history(){const value=stored(historyKey,{});const clean=rows=>(Array.isArray(rows)?rows:[]).filter(r=>typeof r?.name==='string'&&r.name.length<=64&&/^\d{1,20}$/.test(r.uid)&&platformNames[r.platform]).slice(0,20);return {recent:clean(value?.recent),favorites:clean(value?.favorites)};}
const same=(a,b)=>a.uid===b.uid&&a.platform===b.platform;
function remember(identity){const saved=history();saved.recent=[identity,...saved.recent.filter(row=>!same(row,identity))].slice(0,12);try{persist(historyKey,saved);}catch{lookupMessage='Player loaded. This device could not save recent players.';}}
export function leaveApex(){active=false;++revision;++lookupRevision;searching=false;}
export async function mountApex(view){page=({'apex-legends':'legends','apex-news':'news','apex-esports':'esports'})[view]||'overview';active=true;render();await refresh();}
async function refresh(force=false){
 const ticket=++revision;loading=true;render();
 const results=await Promise.allSettled([api.apexContent({refresh:force}),api.apexPlayer({action:'status'})]);
 if(!active||ticket!==revision)return;
 const content=results[0];if(content.status==='fulfilled'&&content.value.catalog?.legends?.length&&content.value.news?.length)data=content.value;else data={...data,error:content.reason?.message||content.value?.error||'Official content could not be checked.'};
 service=results[1].status==='fulfilled'?results[1].value:{available:false,status:'service-unavailable',message:'Player service could not be reached. Try again later.'};loading=false;render();
}
function articleRows(rows){return rows.map(article=>({...article,image:article.image||[...bundle.news,...bundle.esports].find(saved=>saved.url===article.url)?.image})).map(article=>`<button class="apex-article" data-hub-source="${e(article.url)}">${article.image?`<img src="${e(article.image)}" alt="" loading="lazy">`:''}<span class="apex-article-copy"><strong>${e(article.title)}</strong><small>${article.publishedAt?date(article.publishedAt):'ALGS · Official news'}</small></span><span class="apex-article-arrow" aria-hidden="true">↗</span></button>`).join('');}
function recentPlayers(){const saved=history(),rows=saved[historyTab];return `<section class="apex-recent"><div class="apex-history-tabs" aria-label="Saved player lists"><button data-apex-history="recent" aria-pressed="${historyTab==='recent'}">Recent players</button><button data-apex-history="favorites" aria-pressed="${historyTab==='favorites'}">Favorites</button></div>${rows.length?`<div class="apex-recent-list">${rows.map(row=>`<button data-apex-uid="${e(row.uid)}" data-apex-platform="${e(row.platform)}" ${!canLookup()?'disabled':''}><strong>${e(row.name)}</strong><span>${e(platformNames[row.platform])}</span><span aria-hidden="true">↗</span></button>`).join('')}</div>`:`<p class="apex-empty">${historyTab==='recent'?'Players you look up will appear here.':'Favorite a player from their profile to keep them here.'}</p>`}</section>`;}
function overview(){const canSearch=canLookup();return `<section class="apex-search-stage${profile?' has-profile':''}" style="--apex-scene:url('${e(bundle.cover)}')"><div class="apex-search-content"><span class="apex-game-label">APEX LEGENDS</span><h1>Find your player</h1><form class="apex-player-form" aria-label="Apex player lookup"><label><span class="sr-only">Platform</span><select id="apex-platform" name="platform">${opts([['PC','PC / EA'],['PS4','PlayStation'],['X1','Xbox']],platform)}</select></label><label><span class="sr-only">${identifierMode==='uid'?'Player UID':'Player name'}</span><input name="player" autocomplete="off" maxlength="${identifierMode==='uid'?20:64}" inputmode="${identifierMode==='uid'?'numeric':'text'}" value="${e(playerName)}" placeholder="${identifierMode==='uid'?'Enter player UID':'Enter your EA or platform name'}" ${!service.available?'disabled':''}></label><button type="submit" class="hub-button" ${!canSearch?'disabled':''}>${searching?'Searching…':'Find player'}</button></form><p class="apex-search-help">${identifierMode==='uid'?'Use the exact player UID for the selected platform.':'PC players: use your linked EA name. Steam display names may identify a different account.'} <button type="button" class="source-link" data-apex-identifier>${identifierMode==='uid'?'Search by name':'Search by UID'}</button></p></div></section><div class="apex-overview-columns"><div class="apex-player-section">${lookupMessage?`<p class="apex-lookup-state" role="status">${e(lookupMessage)}</p>`:''}${!service.available?`<div class="apex-service-state" role="status"><strong>${service.status==='sign-in-required'?'Sign in to look up a player':'Player lookup unavailable'}</strong><p>${e(service.message||'The player service could not be reached.')}</p><button class="source-link" data-apex-refresh ${loading?'disabled':''}>${loading?'Checking…':'Check connection'}</button></div>`:''}${profile?renderPlayerProfile(profile,art,history().favorites.some(row=>same(row,profile.identity))):''}${recentPlayers()}<div class="apex-player-attribution"><button class="source-link" data-hub-source="https://apexlegendsstatus.com">Data provided by Apex Legends Status ↗</button><span>Unofficial provider · Match history is unavailable.</span></div></div><aside class="apex-overview-feed"><section><div class="apex-section-heading"><h2>Latest from EA</h2><button class="source-link" data-apex-page="news">All news ↗</button></div>${articleRows(data.news.slice(0,3))}</section><section><div class="apex-section-heading"><h2>ALGS</h2><button class="source-link" data-apex-page="esports">Esports ↗</button></div>${articleRows(data.esports.slice(0,2))}</section></aside></div>`;}
function balanceBrief(){return `<section class="apex-balance" aria-label="Reviewed balance changes"><header><div><span class="hub-eyebrow">BALANCE BRIEF</span><h2>${e(balance.title)}</h2><p>${date(balance.publishedAt)} update · Reviewed ${date(balance.checkedAt)}</p></div><button class="source-link" data-hub-source="${e(balance.sourceUrl)}">Read patch notes ↗</button></header><dl>${balance.changes.map(change=>`<div><dt>${e(change.name)}</dt><dd>${e(change.summary)}</dd></div>`).join('')}</dl><p class="apex-balance-note">Selected official changes, not a statistical tier ranking. Check newer patch notes before choosing a team.</p></section>`;}
function legends(){
 const roster=data.catalog.legends.map(l=>{const image=art.legends.find(row=>row.name===l.name.trim());return {...l,name:l.name.trim(),role:image?.role||l.role,art:image};});
 const list=roster.filter(l=>(role==='all'||l.role===role)&&(!query||`${l.name} ${l.role} ${l.abilities.map(a=>a.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())));
 return `<header class="game-simple-heading"><div><span class="hub-eyebrow">APEX LEGENDS</span><h1>Legends & Meta</h1><p>Find your class and compare each legend’s abilities.</p></div><button class="source-link" data-hub-source="https://www.ea.com/games/apex-legends/apex-legends/news">Balance updates ↗</button></header>${balanceBrief()}<div class="apex-legend-tools"><label><span class="sr-only">Find a legend</span><input id="apex-query" type="search" placeholder="Find a legend or ability" value="${e(query)}"></label><label><span class="sr-only">Class</span><select id="apex-role">${opts([['all','All classes'],...['Assault','Controller','Recon','Skirmisher','Support'].map(x=>[x,x])],role)}</select></label><span>${list.length} legends</span></div><div class="apex-legends">${list.map(l=>`<article class="apex-legend">${l.art?`<img class="apex-legend-art" src="${e(l.art.localPath)}" alt="${e(l.name)}" loading="lazy">`:''}<div class="apex-legend-copy"><header><h2>${e(l.name)}</h2><span>${e(l.role)}</span></header><dl>${l.abilities.map(a=>`<div><dt>${e(a.type)}</dt><dd>${e(a.name)}</dd></div>`).join('')}</dl><button class="source-link" data-hub-source="${e(l.art?.sourceUrl||data.catalog.sourceUrl)}">Explore ${e(l.name)} ↗</button></div></article>`).join('')||'<p class="apex-empty" role="status">No legends match. Clear your search or choose another class.</p>'}</div><div class="apex-catalog-note"><p>Classes and artwork: EA character index, checked ${date(art.checkedAt)}. Abilities: EA Help, updated ${date(data.catalog.updatedAt)}. These pages do not supply statistical meta rankings.</p><button class="source-link" data-hub-source="${e(data.catalog.sourceUrl)}">Ability reference ↗</button></div>`;
}
function news(){const isNews=page==='news';return `<section class="apex-news-list"><header class="game-simple-heading"><div><span class="hub-eyebrow">${isNews?'EA / RESPAWN':'COMPETITIVE APEX'}</span><h1>${isNews?'News & updates':'Apex Legends Global Series'}</h1><p>${isNews?'Patch notes, game updates and announcements from the developers.':'Official tournament announcements and event information.'}</p></div><button class="source-link" data-hub-source="${isNews?'https://www.ea.com/games/apex-legends/apex-legends/news':'https://algs.ea.com/en'}">${isNews?'EA news':'Schedule & results'} ↗</button></header><div class="apex-editorial-grid">${articleRows(isNews?data.news:data.esports)}</div>${!isNews?'<p class="apex-catalog-note">The ALGS index does not supply publication dates. Open an article for event details.</p>':''}</section>`;}
function render(){
 if(!active)return;const inputFocused=document.activeElement?.id==='apex-query',selection=inputFocused?[document.activeElement.selectionStart,document.activeElement.selectionEnd]:null;
 $('#hub-app').innerHTML=`<main class="hub-main apex-page" data-apex-view="${page}" style="--apex-scene:url('${e(bundle.cover)}')">${page==='overview'?overview():page==='legends'?legends():news()}<footer class="apex-attribution"><div class="apex-source-actions">${sourceStatus({label:loading?'Checking official pages':'Official content · '+date(data.fetchedAt),tone:data.error?'warning':'neutral',detail:data.error||'EA Help, EA news and ALGS pages. The roster includes official EA character artwork.'})}<button class="source-link" data-apex-refresh ${loading?'disabled':''}>Refresh official content</button></div>Game content and artwork © EA / Respawn. Official pages checked ${dateTime(data.fetchedAt)}. ${data.cacheState==='offline'||data.error?'Showing the last saved snapshot.':''}</footer></main>`;
 if(selection){const input=$('#apex-query');input.focus({preventScroll:true});input.setSelectionRange(...selection);}
}
async function lookup(identity){
 if(!canLookup())return;
 const ticket=++lookupRevision;searching=true;profile=null;lookupMessage='Looking up player…';render();
 try{
  const result=await api.apexPlayer({action:'lookup',...identity});if(!active||ticket!==lookupRevision)return;
  const next=result.status==='ready'?playerProfile(result.profile):null;
  if(next){profile=next;playerName=identifierMode==='uid'?next.identity.uid:next.identity.name;platform=next.identity.platform;lookupMessage='';remember(next.identity);}
  else{
   lookupMessage=result.message||'No validated player result was returned. Check the name and platform.';
   if(result.status==='sign-in-required')service={...service,...result,available:false};
   if(result.status==='rate-limited'){
    const wait=Math.min(300,Math.max(2,Number(result.retryAfter)||2));cooldownUntil=Date.now()+wait*1000;
    clearTimeout(cooldownTimer);cooldownTimer=setTimeout(()=>{cooldownUntil=0;if(active)render();},wait*1000);
   }
  }
 }catch{if(active&&ticket===lookupRevision)lookupMessage='The player service could not be reached. Try again shortly.';}
 finally{if(active&&ticket===lookupRevision){searching=false;render();}}
}
 document.addEventListener('click',event=>{if(!active)return;const button=event.target.closest('button');if(!button)return;if('apexIdentifier'in button.dataset){identifierMode=identifierMode==='name'?'uid':'name';playerName='';render();document.querySelector('.apex-player-form input')?.focus();return;}if('apexRefresh'in button.dataset)refresh(true);if(button.dataset.apexHistory){historyTab=button.dataset.apexHistory;render();}if(button.dataset.apexUid)lookup({uid:button.dataset.apexUid,platform:button.dataset.apexPlatform});if('apexFavorite'in button.dataset&&profile){const saved=history(),identity=profile.identity;saved.favorites=saved.favorites.some(row=>same(row,identity))?saved.favorites.filter(row=>!same(row,identity)):[identity,...saved.favorites].slice(0,20);try{persist(historyKey,saved);}catch{lookupMessage='This device could not save favorites.';}render();}});
 document.addEventListener('input',event=>{if(!active)return;if(event.target.id==='apex-query'){query=event.target.value;render();}if(event.target.matches('.apex-player-form input'))playerName=event.target.value;});
 document.addEventListener('change',event=>{if(!active)return;if(event.target.id==='apex-role'){role=event.target.value;render();}if(event.target.id==='apex-platform')platform=event.target.value;});
 document.addEventListener('submit',event=>{if(active&&event.target.closest('.apex-player-form')){event.preventDefault();if(!playerName.trim()){lookupMessage='Enter your EA or platform name.';render();return;}if(identifierMode==='uid'&&!/^\d{1,20}$/.test(playerName.trim())){lookupMessage='Enter a numeric player UID, up to 20 digits.';render();return;}lookup({[identifierMode==='uid'?'uid':'player']:playerName.trim(),platform});}});
 document.addEventListener('error',event=>{if(event.target.matches?.('.apex-page img'))event.target.hidden=true;},true);
 window.addEventListener('tbb-sources-updated',()=>{if(active&&!loading)refresh();});
