import {validatePrerequisites} from './workflow-model.js';
import {CENTER_KEY,blankState,cleanState,cleanRecord} from './command-model.js';
let state;
export function getState(){if(!state){const raw=localStorage.getItem(CENTER_KEY);try{state=raw?cleanState(JSON.parse(raw)):blankState();}catch{if(raw)localStorage.setItem('dropzone-command-recovery',raw);state=blankState();state.preferences.recoveryMessage='The previous workspace could not be read. Its original data was preserved in your backup under dropzone-command-recovery.';}}return state;}
export function saveState(next){const clean=cleanState(next);localStorage.setItem(CENTER_KEY,JSON.stringify(clean));state=clean;window.dispatchEvent(new Event('dropzone-command-change'));return state;}
export function saveRecord(record){const s=getState(),previous=s.records.find(r=>r.id===record.id),data={...record.data};if(s.activeSession&&record.kind!=='session'){const session=s.records.find(r=>r.id===s.activeSession);if(session?.game===record.game)data.sessionIds=[...new Set([...(previous?.data.sessionIds||[]),...(data.sessionIds||[]),s.activeSession])].slice(-100);}const r=cleanRecord({...record,data,updatedAt:new Date().toISOString()});validatePrerequisites(r,s.records);return saveState({...s,records:[r,...s.records.filter(x=>x.id!==r.id)]});}
export function removeRecord(id){const s=getState();return saveState({...s,records:s.records.filter(r=>r.id!==id),activeSession:s.activeSession===id?null:s.activeSession});}
export function resetMemory(){state=null;}
let database;
function db(){return database??=new Promise((resolve,reject)=>{const req=indexedDB.open('dropzone-media',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function mediaPut(id,file){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export async function mediaGet(id){const database=await db();return new Promise((resolve,reject)=>{const req=database.transaction('files').objectStore('files').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function mediaEntries(){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('files'),keys=tx.objectStore('files').getAllKeys(),values=tx.objectStore('files').getAll();tx.oncomplete=()=>resolve(keys.result.map((key,i)=>[key,values.result[i]]));tx.onerror=()=>reject(tx.error);});}
export async function mediaRemove(id){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export function download(name,data,type='application/json'){const blob=data instanceof Blob?data:new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
