import {initExtras,bindCalculators,calculatorNavigation,accessPresetFields,applyGameAccess} from './workspace-extras.js';
import {teamFields,planningFields,planningValues,bindPlanning,planningDetails,teamDetails} from './game-planning.js';
import {openSessionSetup,finishSession,sessionOverview,recapDetails,setupDashboard} from './session-workflow.js';
import {searchWorkspace,challengeGroups} from './workflow-model.js';
import {$,api,e,toast,opts} from './shared.js';
import {APP_VERSION} from './version.js';
import {TYPES,GAMES,cleanRecord,pack,unpack,shareCode,readCode,mergeRecords,goalStatus,teamCoverage,safeLink} from './command-model.js';
import {getState,saveState,saveRecord,removeRecord,mediaPut,mediaGet,mediaRemove,download} from './command-store.js';
import {toolsView,toolsAction,disposeTools,startBackgroundTools,applyAccess} from './command-tools.js';
import {openBoard,disposeBoard} from './command-board.js';

const labels={build:'Builds',strategy:'Playbooks',team:'Squad',note:'Notebook',goal:'Goals',routine:'Practice',clip:'Clips',settings:'Settings',event:'Calendar',performance:'Performance',tools:'Calculators',data:'Backup & packs',feedback:'Feedback',session:'History'};
let pairingCards=null,pairingTimer,editorDraft;
const navButton=([id,label])=>`<button data-tab="${id}" aria-current="${id===tab?'page':'false'}">${label}</button>`;
function sessionNav(){const items=Object.entries(labels);const primary=['build','strategy','team','note','goal','roster'];return items.filter(([k])=>primary.includes(k)).map(navButton).join('')+`<details><summary>More tools</summary><div>${items.filter(([k])=>!primary.includes(k)).map(navButton).join('')}</div></details>`;}
function goalGroups(){const groups=challengeGroups(entries('goal').filter(r=>!goalStatus(r,getState().records).missing.length));return `<details class="cc-panel cc-checklist-group"><summary>Goals you can work on together</summary><p class="cc-muted">Groups match the game, mode, map and weapon restrictions you entered. Check each objective’s conditions in game; blank restrictions mean any.</p>${groups.map((group,i)=>`<div class="cc-goal-group"><b>Session group ${i+1}</b>${group.map(r=>`<p>${button('open',e(r.title),`data-id="${r.id}"`)} · ${e(r.data.challengeAction||'No action condition recorded')}</p>`).join('')}</div>`).join('')||'<p>No available unfinished goals. Complete prerequisites or add a goal.</p>'}</details>`;}
let games=[],navigate,active=false,tab='build',filter='all',query='',selected=new Set(),dialog,roomTimer,detectTimer,reminderTimer,practiceTimer,practiceEnd=0,practiceRecord;
const names=()=>Object.fromEntries(games.map(g=>[g.id,g.name]));
const gameOptions=(selected,all=false)=>opts([...(all?[['all','All games']]:[]),...games.filter(g=>GAMES.includes(g.id)).map(g=>[g.id,g.name])],selected);
const entries=kind=>searchWorkspace(getState().records.filter(r=>(!kind||r.kind===kind)&&(filter==='all'||r.game===filter)),query);
const actions=(html)=>`<div class="cc-actions">${html}</div>`;
const button=(action,label,attrs='')=>`<button data-cc="${action}" ${attrs}>${label}</button>`;
const empty=message=>`<div class="cc-empty">${message}</div>`;
export function initCommandCenter(list,route){games=list;navigate=route;applyAccess();startBackgroundTools();initExtras();
 $('.rail-main').insertAdjacentHTML('beforeend','<button class="rail-link" data-route="command" title="Game tools" aria-label="Game tools"><span aria-hidden="true">◈</span><span>Game tools</span></button>');
 document.body.insertAdjacentHTML('beforeend','<dialog id="cc-dialog" class="cc-dialog"></dialog>');dialog=$('#cc-dialog');dialog.addEventListener('close',()=>{disposeTools();disposeBoard();clearInterval(practiceTimer);});
 reminderTimer=setInterval(()=>{const s=getState();if(!s.preferences.reminders)return;const now=Date.now();for(const r of s.records.filter(r=>r.kind==='event')){const time=Date.parse(r.data.when);if(time>=now&&time-now<15*60000&&sessionStorage.getItem('cc-reminded-'+r.id)!==r.data.when){sessionStorage.setItem('cc-reminded-'+r.id,r.data.when);toast(`${r.title} starts at ${new Date(time).toLocaleTimeString()}`);}}},30000);
 detectTimer=setInterval(async()=>{if(!api.command||!getState().preferences.detectGame||document.hidden)return;try{const d=await api.command({action:'detect'});const id=d.games[0];if(id&&getState().preferences.detected!==id){const s=getState();saveState({...s,preferences:{...s.preferences,detected:id}});toast(names()[id]+' detected. Your game tools are ready.');if(getState().preferences.autoWorkspace)navigate('command',id);}}catch{}},30000);
 window.addEventListener('beforeunload',()=>{clearInterval(reminderTimer);clearInterval(detectTimer);clearInterval(roomTimer);});
 document.addEventListener('keydown',ev=>{if(ev.key==='/'&&ev.ctrlKey&&!dialog.open){ev.preventDefault();navigate('command');setTimeout(()=>$('#cc-search')?.focus(),0);}});
 window.addEventListener('dropzone-command-change',()=>{applyAccess();if(pairingCards&&api.command){clearTimeout(pairingTimer);pairingTimer=setTimeout(async()=>{try{const records=getState().records.filter(r=>pairingCards.includes(r.id));await api.command({action:'room-update-cards',cards:records.map(r=>({title:r.title,kind:r.kind,body:r.body+(r.data.equipment?'\n'+r.data.equipment:'')}))});}catch{}},250);}});
}
export const preferredGames=()=>getState().favorites;
export function mountCommandCenter(game=null,view=null){active=true;filter=GAMES.includes(game)?game:GAMES.includes(filter)?filter:getState().favorites[0]||'wardogs';tab=view&&labels[view]?view:'build';applyGameAccess(filter);render();}
export function leaveCommandCenter(){active=false;disposeTools();disposeBoard();if(dialog?.open)dialog.close();}
function card(r){const goal=r.kind==='goal'?goalStatus(r,getState().records):null;return `<article class="cc-card"><span class="cc-tag">${e(names()[r.game]||r.game)} / ${e(r.kind)}</span><h3>${e(r.title)}</h3><p>${e(r.body.slice(0,210))}${r.body.length>210?'…':''}</p>${r.patch?`<span class="cc-badge">${e(r.patch)}</span>`:''}${goal?`<div class="cc-progress"><span style="width:${goal.percent}%"></span></div><small>${e(r.data.current||0)} / ${e(r.data.total||1)}${goal.missing.length?' · Prerequisites incomplete':''}</small>`:''}<p class="cc-muted">${new Date(r.updatedAt).toLocaleDateString()}${r.source?' · Source linked':' · Personal entry'}</p>${actions(button('open','Open',`data-id="${r.id}"`)+button('edit','Edit',`data-id="${r.id}"`)+button('share','Share',`data-id="${r.id}"`)+`<label class="cc-check"><input type="checkbox" data-select="${r.id}" ${selected.has(r.id)?'checked':''}>Pack</label>`)}</article>`;}
function library(){const kind=tab==='routine'?'routine':tab;let list=entries(kind);if(tab==='event')list.sort((a,b)=>Date.parse(a.data.when)-Date.parse(b.data.when));return `${tab==='session'?`<section class="cc-panel"><h2>Optional session tracking</h2><p class="cc-muted">Keep a checklist and recap for this game when you want them.</p>${actions(button(getState().activeSession?'end-session':'start-session',getState().activeSession?'Finish & recap':'Start session'))}${sessionOverview(getState().records.find(r=>r.id===getState().activeSession&&r.game===filter))}</section>`:''}${tab==='goal'?goalGroups():''}${tab==='event'?`<p class="cc-muted">Local calendar in your timezone. Import one-time events from an .ics file, or export to your calendar app. Reminders run while Dropzone is open.</p>${actions(button('calendar-import','Import calendar')+button('calendar-export','Export calendar'))}`:''}${tab==='team'?`<section class="cc-panel"><h2>Plan together</h2><p class="cc-muted">Share a portable pack with any friend, or host an editable draft on your local network. Pairing starts only when you choose it.</p>${actions(button('pair','Host second screen & draft')+button('sync-draft','Save latest paired draft'))}<p id="cc-room" role="status" class="cc-remote-state"></p></section>`:''}${tab==='routine'?`<p class="cc-muted">Practice scores are entered by you. No game memory is read. Start a routine to run its timer and record a benchmark.</p>${actions(button('starter-routines','Add practice starters'))}`:''}${tab==='clip'?'<p class="cc-muted">Import a local clip or save a video link. Keep timestamped notes, attach it to a build, and export a selected segment.</p>':''}${tab==='performance'?'<p class="cc-muted">Import frame-time CSV data from your capture tool to compare runs. Dropzone does not inject an FPS overlay into your game.</p>':''}<div class="cc-grid">${list.map(card).join('')||empty('Nothing saved here yet. Add an entry to get started.')}</div>`;}
function render(){if(!active)return;disposeTools();if(window.location.protocol!=='file:'){const url=new URL(window.location.href);url.searchParams.set('game','command');url.searchParams.set('context',filter);url.searchParams.set('view',tab);window.history.replaceState(null,'',url);}$('#hub-app').innerHTML=`<main class="hub-main cc-page"><header class="cc-head"><div><span class="cc-tag">${e(names()[filter]||'DROPZONE')} / YOUR TOOLS</span><h1>${e(labels[tab]||'Game tools')}</h1><p>Your saved setups and tools for ${e(names()[filter]||'this game')}.</p></div>${actions(button('new','＋ Add entry',`data-kind="${TYPES.includes(tab)?tab:'note'}"`))}</header><nav class="cc-nav" aria-label="Game tools">${sessionNav()}</nav><div class="cc-toolbar"><label>Game<select id="cc-game">${gameOptions(filter)}</select></label><label class="cc-search">Search your workspace<input id="cc-search" value="${e(query)}" placeholder="Search plans, notes, tags… (Ctrl /)"></label>${actions(button('pack-selected','Share selected'+(selected.size?' · '+selected.size:''))+button('import-pack','Import pack or code'))}</div><div id="cc-content">${getState().preferences.recoveryMessage?'<p class="cc-warning">'+e(getState().preferences.recoveryMessage)+'</p>':''}${['tools','data','settings','feedback'].includes(tab)?toolsView(tab,{entries,gameOptions,filter,button,actions}):library()}</div></main>`;if(tab==='tools'){$('#cc-content').insertAdjacentHTML('afterbegin',calculatorNavigation(filter));bindCalculators(filter);}if(tab==='settings'&&filter!=='all')$('#cc-content').insertAdjacentHTML('beforeend',accessPresetFields(filter));if(tab==='settings')$('#cc-content').insertAdjacentHTML('beforeend',`<h2>Saved settings profiles</h2><div class="cc-grid">${entries('settings').map(card).join('')}</div>`);}
function show(content){disposeTools();disposeBoard();dialog.innerHTML=content;if(!dialog.open)dialog.showModal();}
function closeButton(){return '<button type="button" data-cc="close">Close</button>';}
function input(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${e(value??'')}" ${extra}></label>`;}
function textArea(name,label,value=''){return `<label class="cc-wide">${label}<textarea name="${name}">${e(value)}</textarea></label>`;}
function edit(record={kind:'note',game:filter==='all'?'wardogs':filter,title:'',data:{}}){editorDraft=record;const d=record.data||{},kind=record.kind;let fields='';
 if(kind==='goal')fields=input('current','Progress',d.current||0,'number','min="0" step="any"')+input('total','Target',d.total||1,'number','min="1" step="any"')+input('cost','Unlock budget / cost (optional)',d.cost,'number','min="0"')+input('deadline','Target date',d.deadline,'date');
 if(kind==='routine')fields=input('minutes','Duration (minutes)',d.minutes||10,'number','min="1" max="180"')+input('metric','Benchmark label',d.metric||'Successful repetitions');
 if(kind==='event')fields=input('when','Date & time (your timezone)',d.when?localDate(d.when):'','datetime-local','required')+input('availability','Squad availability / timezone notes',d.availability);
 if(kind==='settings')fields=input('dpi','DPI',d.dpi,'number','min="1"')+input('sensitivity','Sensitivity',d.sensitivity,'number','min="0.0001" step="any"')+input('resolution','Resolution',d.resolution)+input('audio','Audio devices / volume',d.audio)+textArea('binds','Keybinds & graphics settings',d.binds);
 if(kind==='build')fields=input('pick','Weapon / character',d.pick)+input('mode','Mode / matchup',d.mode)+textArea('equipment','Equipment / attachments / situational alternatives',d.equipment)+textArea('metrics','Comparable numbers: one label=value per line',Object.entries(d.metrics||{}).map(([k,v])=>k+'='+v).join('\n'))+input('measurement','Data basis',d.measurement||'Personal measurements; not verified game stats');
 if(kind==='team')fields=teamFields(record,input);
 if(kind==='clip')fields=input('start','Segment start (seconds)',d.start||0,'number','min="0" step="0.1"')+input('end','Segment end (seconds)',d.end||0,'number','min="0" step="0.1"')+'<label>Local video (optional)<input name="media" type="file" accept="video/*"></label>';
 if(kind==='performance')fields=input('setup','Settings / hardware snapshot',d.setup)+'<label>Frame-time CSV (optional)<input name="csv" type="file" accept=".csv,.txt"></label>'+textArea('samples','Or paste frame times in milliseconds (one per line)',d.samples?.join('\n')||'');
 fields+=planningFields(record,{input,textArea})+'<label class="cc-wide">Attach screenshots (optional)<input name="screenshots" type="file" accept="image/png,image/jpeg,image/webp" multiple></label>';
 show(`<form id="cc-editor" data-id="${e(record.id||'')}" data-kind="${kind}"><header><h2>${record.id?'Edit':'New'} ${e(kind)}</h2>${closeButton()}</header><div class="cc-form-grid"><label>Type<select name="kind" ${record.id?'disabled':''}>${opts(TYPES.filter(k=>!['practice','session'].includes(k)).map(k=>[k,labels[k]||k]),kind)}</select></label><label>Game<select name="game">${gameOptions(record.game)}</select></label>${input('title','Name',record.title,'text','required maxlength="120"')}${input('tags','Tags',record.tags)}${textArea('body',kind==='strategy'?'Round plan, callouts & utility placements':kind==='note'?'Notes / what worked / what to change':'Details',record.body)}${fields}${input('source','Source or video URL (HTTPS)',record.source,'url')}${input('patch','Game patch / reviewed date',record.patch)}<label class="cc-wide">Link related entries (Ctrl / Cmd to select several)<select name="links" multiple>${getState().records.filter(r=>r.id!==record.id).slice(0,200).map(r=>`<option value="${r.id}" ${record.links?.includes(r.id)?'selected':''}>${e(r.title)} · ${e(r.kind)}</option>`).join('')}</select></label></div><p id="cc-form-error" role="alert"></p>${actions('<button type="submit">Save '+e(kind)+'</button>'+closeButton())}</form>`);bindPlanning($('#cc-editor'),record);
}
const localDate=s=>{const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
async function openRecord(r){
 if(r.kind==='strategy'){show(`<header><h2>${e(r.title)}</h2>${closeButton()}</header>${actions(button('edit','Edit plan',`data-id="${r.id}"`)+button('share','Share',`data-id="${r.id}"`)+button('related-note','Add linked note',`data-id="${r.id}"`)+button('delete','Delete',`data-id="${r.id}"`))}<p>${e(r.body)}</p>${planningDetails(r)}${r.data.slots?.length?teamDetails(r):''}<div id="cc-board-host"></div><div id="cc-attachments" class="cc-attachments"></div>`);await openBoard(r,$('#cc-board-host'));await toolsAction('show-attachments',{record:r});return;}
 const links=getState().records.filter(x=>r.links.includes(x.id));let detail='';
 if(r.kind==='goal'){const status=goalStatus(r,getState().records);detail=`<p class="cc-stat">${Math.round(status.percent)}%</p><p>${status.missing.length?'Prerequisites: '+e(status.missing.map(x=>x.title).join(', ')):'No incomplete linked prerequisites.'}</p>${button('progress','Record progress',`data-id="${r.id}"`)}`;}
 if(r.kind==='team')detail=teamDetails(r)+actions(button('pair','Host this draft',`data-id="${r.id}"`));
 if(r.kind==='routine'){detail=`<p>${e(r.data.minutes||10)} minutes · ${e(r.data.metric||'Score')}</p>${actions(button('practice-start','Start timer',`data-id="${r.id}"`))}<div id="cc-practice"></div><h3>Benchmarks</h3>${getState().records.filter(x=>x.kind==='practice'&&x.links.includes(r.id)).slice(0,15).map(x=>`<p>${new Date(x.updatedAt).toLocaleDateString()} · ${e(x.data.score)} ${e(r.data.metric||'')}</p>`).join('')}`;}
 if(r.kind==='settings')detail=`<table class="cc-table">${Object.entries(r.data).filter(([k])=>k!=='backupId').map(([k,v])=>`<tr><th>${e(k)}</th><td>${e(v)}</td></tr>`).join('')}</table>${r.data.backupId?actions(button('restore-file','Restore backed-up file',`data-id="${r.id}"`)+button('undo-file','Undo last restore',`data-id="${r.id}"`)):''}`;
 if(r.kind==='build')detail=`<p>${e(r.data.pick)} · ${e(r.data.mode)}</p><p>${e(r.data.equipment)}</p><small>${e(r.data.measurement)}</small>${actions(button('compare','Compare builds',`data-id="${r.id}"`))}`;
 if(r.kind==='clip')detail=`<video id="cc-video" class="cc-video" controls playsinline></video><p>Segment ${e(r.data.start||0)}–${e(r.data.end||0)} seconds. Timestamp your observations in the notes.</p><div id="cc-clip-tools"></div>`;
 if(r.kind==='performance')detail=await toolsAction('performance-record',{record:r});
 if(r.kind==='session')detail=recapDetails(r)+`<p>Started ${e(r.data.startedAt)}<br>Finished ${e(r.data.endedAt||'Still running')}</p><p>What worked: ${e(r.data.worked||'Not recorded')}</p><p>Change next time: ${e(r.data.change||'Not recorded')}</p>`;
 show(`<header><h2>${e(r.title)}</h2>${closeButton()}</header><span class="cc-tag">${e(names()[r.game])} / ${e(r.kind)}</span><p style="white-space:pre-wrap">${e(r.body)}</p>${detail}${planningDetails(r)}<div id="cc-attachments" class="cc-attachments"></div>${r.source?actions(button('source','Open source ↗',`data-url="${e(r.source)}"`)):''}<h3>Related entries</h3>${actions(links.map(x=>button('open',e(x.title),`data-id="${x.id}"`)).join(''))}${actions(button('edit','Edit',`data-id="${r.id}"`)+button('related-note','Add linked note',`data-id="${r.id}"`)+button('share','Share',`data-id="${r.id}"`)+button('delete','Delete',`data-id="${r.id}"`))}`);
 await toolsAction('show-attachments',{record:r});
 if(r.kind==='clip')await toolsAction('clip-open',{record:r});
}
function previewPack(value){const items=unpack(value);show(`<header><h2>Review content pack</h2>${closeButton()}</header><p>${items.length} entries. Import creates new copies; existing work stays intact. Links are not opened and files are not executed.</p><div class="cc-list">${items.map(r=>`<p>${e(r.title)} · ${e(r.kind)} · ${e(names()[r.game])}</p>`).join('')}</div>${actions(button('confirm-import','Import copies'))}`);$('#cc-dialog [data-cc="confirm-import"]').onclick=()=>{const s=getState();saveState({...s,records:mergeRecords(s.records,items)});dialog.close();render();toast('Pack imported.');};}
function snapshot(record){const s=getState(),team=record?.kind==='team'?record:entries('team')[0],cards=s.records.filter(r=>(selected.size?selected.has(r.id):(filter==='all'||r.game===filter))&&['build','note','strategy','goal','routine'].includes(r.kind)).slice(0,40);return {title:team?.title||'Dropzone session',game:team?.game||(filter==='all'?'':filter),cardIds:cards.map(r=>r.id),cards:cards.map(r=>({title:r.title,kind:r.kind,body:r.body+(r.data.equipment?'\n'+r.data.equipment:'')})),slots:team?.data.slots||[]};}
async function action(name,el){const r=getState().records.find(x=>x.id===el?.dataset.id),ctx={record:r,filter,show,button,actions,render,gameOptions,dialog,navigate,games};
 if(name==='close'){disposeTools();disposeBoard();dialog.close();return;}
 if(name==='new')return edit({kind:el.dataset.kind||'note',game:filter==='all'?'wardogs':filter,data:{}});
 if(name==='edit')return edit(r);
 if(name==='related-note')return edit({kind:'note',game:r.game,title:r.title+' · notes',links:[r.id],data:{map:r.data.map||'',...(r.data.location?{location:r.data.location}:{})}});
 if(name==='open')return openRecord(r);
 if(name==='game'){filter=el.dataset.game;tab='build';render();return;}
 if(name==='navigate'){dialog.close();return navigate(el.dataset.route);}
 if(name==='source'){if(safeLink(el.dataset.url))return api.command?api.command({action:'open-link',url:el.dataset.url}):api.openSource(el.dataset.url);return;}
 if(name==='delete'){show(`<h2>Delete ${e(r.title)}?</h2><p>This removes this entry and its imported media. Other entries stay intact.</p>${actions(button('confirm-delete','Delete')+closeButton())}`);$('[data-cc="confirm-delete"]').onclick=async()=>{for(const id of [r.data.mediaId,r.data.imageId,...(r.data.attachments||[]).map(a=>a.id),...(r.data.boards||[]).map(a=>a.imageId)].filter(Boolean)){if(!getState().records.some(x=>x.id!==r.id&&[x.data.mediaId,x.data.imageId,...(x.data.attachments||[]).map(a=>a.id),...(x.data.boards||[]).map(a=>a.imageId)].includes(id)))await mediaRemove(id);}removeRecord(r.id);dialog.close();render();};return;}
 if(name==='share'||name==='pack-selected'){const records=name==='share'?[r]:getState().records.filter(r=>selected.has(r.id));if(!records.length)throw Error('Select entries using their Pack checkbox first.');const value=pack(records);show(`<header><h2>Share ${records.length} entries</h2>${closeButton()}</header><p>Copy this code into Discord or send the exported pack. Local media stays on your PC; clip notes and links are included.</p><textarea id="cc-code" readonly></textarea>${actions(button('copy-code','Copy code')+button('export-pack','Export pack'))}`);try{$('#cc-code').value=shareCode(value);}catch{$('#cc-code').value='Large pack: use Export pack.';}$('[data-cc="copy-code"]').onclick=()=>api.copy($('#cc-code').value).then(()=>toast('Copied.'));$('[data-cc="export-pack"]').onclick=()=>download('dropzone-pack.json',value);return;}
 if(name==='import-pack'){show(`<header><h2>Import a content pack</h2>${closeButton()}</header><p>Import a file or paste a DZ1 share code. You will review the entries before importing.</p><input id="cc-pack-file" type="file" accept=".json"><textarea id="cc-pack-code" placeholder="DZ1.…"></textarea>${button('read-pack','Review code')}`);$('#cc-pack-file').onchange=async ev=>{try{const f=ev.target.files[0];if(f.size>10000000)throw Error('Pack exceeds 10 MB.');previewPack(JSON.parse(await f.text()));}catch(err){toast(err.message);}};$('[data-cc="read-pack"]').onclick=()=>{try{previewPack(readCode($('#cc-pack-code').value));}catch(err){toast(err.message);}};return;}
 if(name==='setup-dashboard')return setupDashboard(ctx);
 if(name==='start-session')return openSessionSetup(ctx);
 if(name==='end-session')return finishSession(ctx);
 if(name==='progress'){show(`<form id="cc-progress-form" data-id="${r.id}"><h2>${e(r.title)}</h2>${input('current','New progress',r.data.current||0,'number','min="0" step="any" required')}<button>Save progress</button>${closeButton()}</form>`);return;}
 if(name==='starter-routines'){const game=filter==='all'?'wardogs':filter;for(const [title,minutes,body,metric]of [['Aim consistency',10,'Choose a repeatable drill in your game or aim trainer. Keep the same sensitivity and difficulty. Record successful hits.','Successful hits'],['Map recall',5,'Pick one map. Recall callouts and routes without opening a guide, then check your answers.','Correct callouts'],['Utility practice',10,'Choose one saved playbook. Repeat its utility sequence in a practice environment and record clean attempts.','Clean attempts']])saveRecord({kind:'routine',game,title,body,data:{minutes,metric}});render();return;}
 if(name==='practice-start'){practiceRecord=r;practiceEnd=Date.now()+Math.max(1,Number(r.data.minutes)||10)*60000;clearInterval(practiceTimer);const paint=()=>{const host=$('#cc-practice');if(!host)return;const secs=Math.max(0,Math.ceil((practiceEnd-Date.now())/1000));host.innerHTML=`<p class="cc-timer">${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}</p>${button('practice-finish','Finish & record')}`;if(!secs)clearInterval(practiceTimer);};practiceTimer=setInterval(paint,1000);paint();return;}
 if(name==='practice-finish'){clearInterval(practiceTimer);show(`<form id="cc-practice-form"><h2>Record benchmark</h2>${input('score',e(practiceRecord.data.metric||'Score'),'','number','min="0" step="any" required')}${textArea('body','Conditions and notes')}<button>Save result</button>${closeButton()}</form>`);return;}
 if(name==='pair'){if(!api.command)throw Error('Pairing is available in the Windows app.');show(`<header><h2>Pair your phone or squad</h2>${closeButton()}</header><p>Shares the selected cards (or current game’s cards) and this draft over your local network. Anyone with the link can read the cards and edit draft slots. Use a trusted network. Pairing expires after eight hours.</p>${actions(button('pair-start','Start pairing')+button('pair-stop','Stop pairing'))}<p id="cc-pair-status" class="cc-remote-state" role="status"></p>`);$('[data-cc="pair-start"]').onclick=async()=>{try{const shared=snapshot(r);const status=await api.command({action:'room-start',snapshot:shared});pairingCards=shared.cardIds;$('#cc-pair-status').textContent=status.urls.length?'Open on a device on the same network:\n'+status.urls.join('\n'):'No local-network address found. Connect to Wi-Fi or Ethernet.';}catch(err){toast(err.message);}};$('[data-cc="pair-stop"]').onclick=async()=>{await api.command({action:'room-stop'});pairingCards=null;$('#cc-pair-status').textContent='Pairing stopped. Links no longer work.';};return;}
 if(name==='sync-draft'){if(!api.command)throw Error('Available in the Windows app.');const d=await api.command({action:'room-read'});if(!d.snapshot.slots.length)throw Error('No paired draft.');saveRecord({kind:'team',game:GAMES.includes(d.snapshot.game)?d.snapshot.game:filter==='all'?'wardogs':filter,title:d.snapshot.title+' · paired draft',data:{slots:d.snapshot.slots}});render();return;}
 if(name==='restore-file'||name==='undo-file'){const result=await api.command({action:name==='restore-file'?'settings-restore':'settings-undo',id:r.data.backupId});toast(result.canceled?'No settings changed.':'Settings operation complete.');return;}
 return toolsAction(name,ctx);
}
document.addEventListener('click',ev=>{if(ev.target.closest('[data-manage-games]')){setupDashboard({show,games,render:()=>window.dispatchEvent(new Event('dropzone-favorites-change'))});return;}const b=ev.target.closest('[data-cc],[data-tab]');if(!b||(!active&&!dialog?.contains(b)))return;if(b.dataset.tab){tab=b.dataset.tab;query='';render();return;}if(['confirm-import','confirm-delete','copy-code','export-pack','read-pack','pair-start','pair-stop'].includes(b.dataset.cc))return;Promise.resolve(action(b.dataset.cc,b)).catch(err=>toast(err.message));});
document.addEventListener('change',ev=>{if(!active)return;const t=ev.target;if(t.id==='cc-game'){filter=t.value;applyGameAccess(filter);if(tab==='roster'&&!['valorant','rivals'].includes(filter))tab='build';render();}if(t.dataset.favorite){const s=getState();saveState({...s,favorites:t.checked?[...new Set([...s.favorites,t.dataset.favorite])]:s.favorites.filter(g=>g!==t.dataset.favorite)});render();}if(t.dataset.select){t.checked?selected.add(t.dataset.select):selected.delete(t.dataset.select);}if(['kind','game'].includes(t.name)&&t.closest('#cc-editor')){const f=t.closest('form'),v=Object.fromEntries(new FormData(f));edit({...editorDraft,kind:v.kind||f.dataset.kind,game:v.game,title:v.title,body:v.body,tags:v.tags,source:v.source,patch:v.patch,links:new FormData(f).getAll('links'),data:t.name==='game'?{map:'',checklist:editorDraft.data?.checklist||[]}:editorDraft.data||{}});}});
let searchTimer;document.addEventListener('input',ev=>{if(ev.target.id==='cc-search'){query=ev.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const caret=ev.target.selectionStart;render();$('#cc-search').focus();$('#cc-search').setSelectionRange(caret,caret);},200);}});
document.addEventListener('submit',async ev=>{if(!ev.target.id.startsWith('cc-'))return;ev.preventDefault();const f=ev.target,values=Object.fromEntries(new FormData(f));try{
 if(f.id==='cc-editor'){
  const old=getState().records.find(r=>r.id===f.dataset.id),kind=f.dataset.kind,data={...(editorDraft?.data||old?.data||{})};
  for(const key of ['pick','mode','equipment','measurement','metric','binds','audio','resolution','setup','availability','deadline'])if(key in values)data[key]=String(values[key]).slice(0,16000);
  for(const key of ['current','total','cost','minutes','dpi','sensitivity','start','end'])if(values[key]!=='undefined'&&values[key]!==undefined&&values[key]!==''){const num=Number(values[key]);if(!Number.isFinite(num)||num<0)throw Error('Numbers must be finite and nonnegative.');data[key]=num;}
  if(values.when){if(!Number.isFinite(Date.parse(values.when)))throw Error('Choose a valid date.');data.when=new Date(values.when).toISOString();}
  if(kind==='build'){data.metrics={};for(const line of String(values.metrics||'').split('\n').filter(Boolean)){const [k,v]=line.split('=');if(!k?.trim()||!Number.isFinite(Number(v))||v==='')throw Error('Use metric=value, one per line.');data.metrics[k.trim().slice(0,80)]=Number(v);}}
  Object.assign(data,planningValues(f,{kind,game:values.game,data}));
  if(kind==='performance')Object.assign(data,await toolsAction('parse-performance',{values,form:f}));
  if(values.source&&!safeLink(values.source))throw Error('Source links must use HTTPS.');
  const id=old?.id||crypto.randomUUID();if(values.media?.size){if(!values.media.type.startsWith('video/')||values.media.size>500*1024*1024)throw Error('Choose a video under 500 MB.');data.mediaId=crypto.randomUUID();data.mediaName=values.media.name;await mediaPut(data.mediaId,values.media);}
  const screenshots=new FormData(f).getAll('screenshots').filter(file=>file.size);if(screenshots.length+(data.attachments?.length||0)>12)throw Error('Use up to 12 screenshots per entry.');for(const file of screenshots){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15000000)throw Error('Screenshots must be PNG/JPEG/WebP under 15 MB.');const mediaId=crypto.randomUUID();await mediaPut(mediaId,file);data.attachments=[...(data.attachments||[]),{id:mediaId,name:file.name,type:file.type}];}
  saveRecord({id,kind,game:values.game,title:values.title,body:values.body,tags:values.tags,source:values.source,patch:values.patch,links:new FormData(f).getAll('links'),data});
 }else if(f.id==='cc-session'){
  if(getState().activeSession)throw Error('Finish your current session before starting another.');
  if(values.launch||values.companion)await api.command({action:'launch',game:values.game,launchGame:!!values.launch,companion:!!values.companion});
  const id=crypto.randomUUID();saveRecord({id,kind:'session',game:values.game,title:values.title,data:{startedAt:new Date().toISOString()}});saveState({...getState(),activeSession:id});filter=values.game;dialog.close();if(values.tool==='game'){navigate(values.game);return;}tab=values.tool;
 }else if(f.id==='cc-recap'){const r=getState().records.find(r=>r.id===f.dataset.id);saveRecord({...r,data:{...r.data,endedAt:new Date().toISOString(),worked:values.worked,change:values.change}});saveState({...getState(),activeSession:null});tab='session';
 }else if(f.id==='cc-progress-form'){const r=getState().records.find(r=>r.id===f.dataset.id),current=Number(values.current);if(!Number.isFinite(current)||current<0)throw Error('Enter valid progress.');saveRecord({...r,data:{...r.data,current}});
 }else if(f.id==='cc-practice-form')saveRecord({kind:'practice',game:practiceRecord.game,title:practiceRecord.title,body:values.body,links:[practiceRecord.id],data:{score:Number(values.score),durationMinutes:practiceRecord.data.minutes}});
 else return;
 dialog.close();render();toast('Saved on this PC.');
 }catch(err){const error=f.querySelector('#cc-form-error');if(error)error.textContent=err.message;else toast(err.message);}});
export const commandSearch=()=>getState().records.filter(r=>GAMES.includes(r.game)).map(r=>({id:'command',game:r.game,label:r.title+' / '+r.kind,recordId:r.id}));
window.addEventListener('dropzone-open-record',ev=>{const r=getState().records.find(r=>r.id===ev.detail);if(r){filter=r.game;tab=labels[r.kind]?r.kind:'build';active=true;render();openRecord(r);}});

document.addEventListener('change',ev=>{if(ev.target.dataset.recordCheck){const r=getState().records.find(r=>r.id===ev.target.dataset.recordId);if(r)saveRecord({...r,data:{...r.data,checklist:r.data.checklist.map(x=>x.id===ev.target.dataset.recordCheck?{...x,done:ev.target.checked}:x)}});}});
