import {api,e,toast} from './shared.js';
import {getState,saveState} from './command-store.js';
import {b64,unb64,encryptWorkspace,decryptWorkspace,mergeWorkspaces} from './command-crypto.js';
const KEY='dropzone-workspace-connection';
const request=input=>api.workspace?api.workspace(input):fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}).then(async r=>{const data=await r.json();if(!r.ok||data.error)throw Error(data.error||'Workspace service not published yet.');return data;});
function saved(){try{return JSON.parse(localStorage.getItem(KEY));}catch{return null;}}
function code(c){return 'DZS1.'+c.id+'.'+c.token+'.'+c.key;}
function decode(value){const [prefix,id,token,key,...tail]=value.trim().split('.');if(prefix!=='DZS1'||tail.length||!/^[a-f0-9-]{36}$/.test(id)||!/^[a-f0-9]{64}$/.test(token)||unb64(key).length!==32)throw Error('Paste the complete DZS1 sync code.');return {id,token,key,version:null};}
export function openSync({show,button,actions,render}){
 show(`<header><h2>Private workspace sync</h2>${button('close','Close')}</header><p>Sync the session center’s builds, notes, goals and plans across PCs. Data is encrypted on your device before upload. Anyone with the sync code can read, change or delete this workspace. Local video files and launcher paths are not uploaded.</p><p class="cc-warning">The sync backend is prepared locally but has not been published. Public connections will become available only after the website update is approved.</p><textarea id="cc-sync-code" placeholder="DZS1.…"></textarea>${actions(button('sync-create','Create encrypted workspace')+button('sync-connect','Connect with code')+button('sync-pull','Download & review')+button('sync-push','Upload my changes')+button('sync-delete','Delete remote workspace'))}<p id="cc-sync-status" role="status"></p>`);
 const $=id=>document.getElementById(id);let connection=saved(),remote=null;if(connection)$('cc-sync-code').value=code(connection);const status=text=>$('cc-sync-status').textContent=text;
 const run=fn=>async()=>{try{await fn();}catch(err){status(err.message);}};
 document.querySelector('[data-cc="sync-create"]').onclick=run(async()=>{const key=b64(crypto.getRandomValues(new Uint8Array(32))),result=await request({action:'create',payload:await encryptWorkspace(getState(),key)});connection={...result,key};localStorage.setItem(KEY,JSON.stringify(connection));$('cc-sync-code').value=code(connection);status('Created. Save this code on your other PC. The server cannot recover a lost encryption key.');});
 document.querySelector('[data-cc="sync-connect"]').onclick=run(async()=>{const next=decode($('cc-sync-code').value),result=await request({action:'get',id:next.id,token:next.token});await decryptWorkspace(result.payload,next.key);connection={...next,version:null};localStorage.setItem(KEY,JSON.stringify(connection));status('Connected. Download and review before uploading from this device.');});
 document.querySelector('[data-cc="sync-pull"]').onclick=run(async()=>{if(!connection)throw Error('Connect first.');const result=await request({action:'get',id:connection.id,token:connection.token});remote=await decryptWorkspace(result.payload,connection.key);status(`Downloaded ${remote.records.length} entries. Matching IDs are compared by saved time; conflicting copies are preserved.`);const confirm=document.createElement('button');confirm.textContent='Merge downloaded entries';$('cc-sync-status').append(document.createElement('br'),confirm);confirm.onclick=run(async()=>{saveState(await mergeWorkspaces(getState(),remote));connection.version=result.version;localStorage.setItem(KEY,JSON.stringify(connection));status('Merged. Upload when you are ready.');});});
 document.querySelector('[data-cc="sync-push"]').onclick=run(async()=>{if(!connection||connection.version===null)throw Error('Download and merge first to protect the other device’s changes.');const result=await request({action:'put',id:connection.id,token:connection.token,version:connection.version,payload:await encryptWorkspace(getState(),connection.key)});connection.version=result.version;localStorage.setItem(KEY,JSON.stringify(connection));status('Encrypted workspace uploaded. Stored for 30 days from this upload.');});
 document.querySelector('[data-cc="sync-delete"]').onclick=()=>{if(!connection)return;status('This deletes the remote copy for every code holder. Local records stay on this PC.');const confirm=document.createElement('button');confirm.textContent='Confirm delete remote copy';$('cc-sync-status').append(document.createElement('br'),confirm);confirm.onclick=run(async()=>{await request({action:'delete',id:connection.id,token:connection.token});localStorage.removeItem(KEY);connection=null;$('cc-sync-code').value='';status('Remote workspace deleted.');});};
}
