import {e,toast} from './shared.js';
import {mediaGet,mediaPut,saveRecord,download} from './command-store.js';
let cleanup=()=>{};
export function disposeBoard(){cleanup();cleanup=()=>{};}
export async function openBoard(record,host){
 disposeBoard();let shapes=structuredClone(record.data.shapes||[]),undo=[],tool='point',drag=null,image=null,alive=true,floor=record.data.floor||'Main',imageRequest=0;
 host.innerHTML=`<div class="cc-toolbar"><label>Floor / layer<input id="cc-board-floor" list="cc-board-floors" value="${e(floor)}" maxlength="60"><datalist id="cc-board-floors">${[...new Set([floor,...(record.data.boards||[]).map(b=>b.floor),...shapes.map(s=>s.floor).filter(Boolean)])].map(f=>`<option value="${e(f)}">`).join('')}</datalist></label><label>Placement<select id="cc-board-category"><option value="position">Position</option><option value="reinforcement">Reinforcement / hatch</option><option value="utility">Utility</option><option value="rotate">Rotate / fallback</option></select></label><label>Assigned player<select id="cc-board-owner"><option value="">Unassigned</option>${(record.data.slots||[]).map(s=>`<option value="${e(s.name||s.pick)}">${e(s.name||s.pick)}</option>`).join('')}</select></label><label>Marker<select id="cc-board-tool"><option value="point">Numbered position</option><option value="arrow">Arrow</option><option value="box">Area box</option></select></label><label>Label<input id="cc-board-label" maxlength="60" placeholder="Breach / smoke / rotate…"></label><label>Own map or reference image<input id="cc-board-file" type="file" accept="image/png,image/jpeg,image/webp"></label></div><p class="cc-muted">Planning sketch. Position markers are relative to your image, not calibrated world coordinates. Use imagery you have permission to use.</p><canvas class="cc-board" width="1200" height="750" id="cc-board" tabindex="0" aria-label="Tactics drawing board"></canvas><div class="cc-actions"><button id="cc-board-undo">Undo</button><button id="cc-board-clear">Clear markers</button><button id="cc-board-export">Export image</button></div><p id="cc-board-status" role="status"></p>`;
 const canvas=host.querySelector('canvas'),ctx=canvas.getContext('2d'),label=host.querySelector('#cc-board-label');
 function draw(preview){ctx.clearRect(0,0,1200,750);ctx.fillStyle='#11241c';ctx.fillRect(0,0,1200,750);if(image)ctx.drawImage(image,0,0,1200,750);else{ctx.strokeStyle='#244234';ctx.lineWidth=1;for(let x=0;x<1200;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,750);ctx.stroke();}for(let y=0;y<750;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1200,y);ctx.stroke();}}
 [...shapes,...(preview?[preview]:[])].filter(s=>(s.floor||record.data.floor||'Main')===floor).forEach((s,i)=>{const x=s.x*1200,y=s.y*750,x2=s.x2*1200,y2=s.y2*750;const color=({reinforcement:'#ffc876',utility:'#8ed5ff',rotate:'#dfa3ff'})[s.category]||'#d9efac';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=4;if(s.type==='point'){ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#102116';ctx.font='bold 17px sans-serif';ctx.fillText(String(i+1),x-5,y+6);}else if(s.type==='box'){ctx.fillStyle='#cfeca333';ctx.fillRect(x,y,x2-x,y2-y);ctx.strokeRect(x,y,x2-x,y2-y);}else{ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y,x2-x);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-20*Math.cos(a-.4),y2-20*Math.sin(a-.4));ctx.lineTo(x2-20*Math.cos(a+.4),y2-20*Math.sin(a+.4));ctx.closePath();ctx.fill();}const caption=[s.owner,s.label].filter(Boolean).join(' · ');if(caption){ctx.font='bold 19px sans-serif';const width=ctx.measureText(caption).width;ctx.fillStyle='#0a1913df';ctx.fillRect(x+20,y-24,width+14,28);ctx.fillStyle='#fff';ctx.fillText(caption,x+27,y-4);}});
 }
 const point=ev=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))};};
 function save(){try{saveRecord({...record,data:{...record.data,shapes}});record={...record,data:{...record.data,shapes}};host.querySelector('#cc-board-status').textContent='Saved on this PC.';}catch(err){toast(err.message);}}
 function remember(){undo.push(structuredClone(shapes));if(undo.length>30)undo.shift();}
 canvas.onpointerdown=ev=>{if(ev.button!==0)return;canvas.setPointerCapture(ev.pointerId);const p=point(ev);drag={type:tool,floor,category:host.querySelector('#cc-board-category').value,owner:host.querySelector('#cc-board-owner').value,...p,x2:p.x,y2:p.y,label:label.value};};
 canvas.onpointermove=ev=>{if(!drag)return;const p=point(ev);drag.x2=p.x;drag.y2=p.y;draw(drag);};
 canvas.onpointerup=()=>{if(!drag)return;if(shapes.length>=100){drag=null;toast('A board supports 100 markers.');return;}remember();shapes.push(drag);drag=null;save();draw();};canvas.onpointercancel=()=>{drag=null;draw();};
 host.querySelector('#cc-board-tool').onchange=ev=>tool=ev.target.value;
 host.querySelector('#cc-board-undo').onclick=()=>{if(undo.length){shapes=undo.pop();save();draw();}};
 host.querySelector('#cc-board-clear').onclick=()=>{remember();shapes=shapes.filter(s=>(s.floor||record.data.floor||'Main')!==floor);save();draw();};
 host.querySelector('#cc-board-export').onclick=()=>canvas.toBlob(blob=>download('dropzone-playbook.png',blob),'image/png');
 async function loadFloor(){const request=++imageRequest;image?.close();image=null;draw();const id=record.data.boards?.find(b=>b.floor===floor)?.imageId||((floor===(record.data.floor||'Main'))?record.data.imageId:null);if(!id)return;const file=await mediaGet(id);if(!file||!alive||request!==imageRequest)return;const bitmap=await createImageBitmap(file);if(!alive||request!==imageRequest){bitmap.close();return;}image=bitmap;draw();}
 host.querySelector('#cc-board-floor').onchange=async ev=>{floor=ev.target.value.trim()||'Main';drag=null;await loadFloor();};
 host.querySelector('#cc-board-file').onchange=async ev=>{try{const currentFloor=floor,request=++imageRequest,file=ev.target.files[0];if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15000000)throw Error('Choose a PNG, JPEG or WebP under 15 MB.');const bitmap=await createImageBitmap(file);if(!alive||request!==imageRequest){bitmap.close();return;}const imageId=crypto.randomUUID();await mediaPut(imageId,file);if(!alive||request!==imageRequest){bitmap.close();return;}image?.close();image=bitmap;record.data.boards=[...(record.data.boards||[]).filter(b=>b.floor!==currentFloor),{floor:currentFloor,imageId}];save();draw();}catch(err){toast(err.message);}};
 cleanup=()=>{alive=false;imageRequest++;image?.close();};draw();await loadFloor();
}
