import {saveAccessPreset,bindClipMoments} from './workspace-extras.js';
import {importCalendar,exportCalendar} from './command-calendar.js';
import {readBackupText,remapRestoredMedia} from './command-backup.js';
import {openSync} from './command-sync.js';
import {$,api,e,toast,opts} from './shared.js';
import {APP_VERSION} from './version.js';
import {CENTER_KEY,GAMES,sensitivity,performanceSummary,compareMetrics,backupStorage,validateBackup,restoreStorage,pack} from './command-model.js';
import {getState,saveState,saveRecord,mediaGet,mediaEntries,mediaPut,download,resetMemory} from './command-store.js';
let disposers=[];export function disposeTools(){for(const fn of disposers)try{fn();}catch{}disposers=[];}
const heading=(title,body)=>`<h2>${title}</h2><p class="cc-muted">${body}</p>`;
const inp=(id,label,value='',type='text')=>`<label>${label}<input id="${id}" type="${type}" value="${e(value)}"></label>`;
export function applyAccess(){const p=getState().preferences;document.body.classList.toggle('cc-access-contrast',!!p.contrast);document.body.classList.toggle('cc-reduced-motion',!!p.reducedMotion);}
export function startBackgroundTools(){applyAccess();}
export function toolsView(tab,{filter,gameOptions,button,actions}){const p=getState().preferences;
 if(tab==='settings')return `<div class="cc-two"><section class="cc-panel">${heading('Launch & workspace','Optionally choose what a tracked session can open. Launchers are configured locally and never imported from shared packs.')}<label>Game<select id="cc-launch-game">${gameOptions(filter==='all'?'wardogs':filter)}</select></label>${actions(button('configure-launch','Choose game launcher')+button('configure-companion','Choose companion app')+button('launch-status','Show configured apps'))}<p id="cc-launch-status" role="status"></p><label class="cc-check"><input type="checkbox" data-pref="detectGame" ${p.detectGame?'checked':''}>Detect supported running games</label><label class="cc-check"><input type="checkbox" data-pref="autoWorkspace" ${p.autoWorkspace?'checked':''}>Switch Dropzone’s workspace when detected</label><p class="cc-muted">Detection checks process names every 30 seconds while Dropzone is visible. It never brings Dropzone to the foreground.</p></section><section class="cc-panel">${heading('Accessibility','Use keyboard navigation throughout. Marker labels and shapes remain visible independently of color.')}<label class="cc-check"><input type="checkbox" data-pref="contrast" ${p.contrast?'checked':''}>High contrast</label><label class="cc-check"><input type="checkbox" data-pref="reducedMotion" ${p.reducedMotion?'checked':''}>Reduced motion</label><label class="cc-check"><input type="checkbox" data-pref="reminders" ${p.reminders?'checked':''}>Event reminders while Dropzone is open</label>${actions(button('voice','Voice commands')+button('readiness','Audio readiness check'))}</section><section class="cc-panel">${heading('Game settings backups','Choose a text settings file to save a recoverable copy. Restore only with the game closed.')}<p class="cc-muted">Backups never modify the live file until you explicitly choose Restore.</p>${actions(button('backup-settings-file','Choose settings file'))}</section><section class="cc-panel">${heading('Connection status','Your tools work with local records. Automatic game account synchronization is not connected.')}<p>Automatic match history / challenge import: not connected.<br>Device battery and game-update status: not connected.</p></section></div>`;
 if(tab==='data')return `<div class="cc-two"><section class="cc-panel">${heading('Complete workspace backup','Export saves, preferences and imported media together. Restore shows a review first and saves a rollback copy.')}<p class="cc-muted">Pairing secrets and launcher paths are excluded. Native settings-file backups are included when exporting from the Windows app. Large media backups can take time.</p>${actions(button('backup','Export backup')+button('restore','Restore backup')+button('sync','Private workspace sync'))}<p id="cc-backup-status" role="status"></p></section><section class="cc-panel">${heading('Content packs','Builds, routines, strategy notes, goals and squad setups use the same portable pack format.')}<p>Creators can distribute JSON packs or DZ1 codes. Every import gets a review screen and becomes a new copy. Packs cannot execute code.</p>${actions(button('import-pack','Import a pack')+button('export-all-content','Export content library'))}</section><section class="cc-panel">${heading('Move between PCs','Transfer a backup to another PC, then restore it there. Shared packs merge as copies so both versions survive.')}<p class="cc-muted">Hosted cross-device account sync is not enabled. Local pairing works on the same trusted network.</p></section><section class="cc-panel">${heading('Use existing saved builds','Bring your existing COD, League and THE FINALS saves into the shared notebook and pack system.')}<p>Original saves remain in their existing tools.</p>${actions(button('import-existing','Copy existing builds'))}</section></div>`;
 if(tab==='feedback')return `<section class="cc-panel">${heading('Report a problem or outdated data','Review your report before exporting. Nothing is sent automatically.')}<label>Category<select id="cc-feedback-type"><option>Something will not load</option><option>Outdated build or guide</option><option>Incorrect number</option><option>Usability feedback</option></select></label>${inp('cc-feedback-source','Affected source URL (optional)')}<label>What happened?<textarea id="cc-feedback-body"></textarea></label>${actions(button('feedback-save','Create reviewed report')+button('health','Show app health'))}<p id="cc-health" role="status"></p></section><h2>Saved reports</h2><p class="cc-muted">Exported reports include the app version and selected game. No account credentials or private files are attached.</p>`;
 return `<div class="cc-two"><section class="cc-panel">${heading('Physical sensitivity conversion','Match centimetres per full turn. Supply verified yaw constants for both games; this does not match scoped or perceived aiming speed.')}<div class="cc-form-grid">${inp('calc-dpi','Current DPI',800,'number')}${inp('calc-sens','Current sensitivity',1,'number')}${inp('calc-yaw','Current yaw (degrees / count / sensitivity)','','number')}${inp('calc-target-dpi','Target DPI',800,'number')}${inp('calc-target-yaw','Target yaw','','number')}</div>${actions(button('calc-sensitivity','Calculate'))}<p id="calc-sensitivity-result" role="status"></p></section><section class="cc-panel">${heading('Frame time & aspect ratio','Simple unit calculations, independent of game telemetry.')}<div class="cc-form-grid">${inp('calc-fps','FPS',144,'number')}${inp('calc-width','Width',2560,'number')}${inp('calc-height','Height',1440,'number')}</div>${actions(button('calc-display','Calculate'))}<p id="calc-display-result" role="status"></p></section><section class="cc-panel">${heading('Damage breakpoint','Constant per-hit damage supplied by you. No armor breakage, travel time, reload or game-specific effects are assumed.')}<div class="cc-form-grid">${inp('calc-hp','Effective health',100,'number')}${inp('calc-damage','Damage per hit','','number')}${inp('calc-rpm','Rounds per minute','','number')}</div>${actions(button('calc-damage','Calculate'))}<p id="calc-damage-result" role="status"></p></section></div>`;
}
document.addEventListener('change',ev=>{if(ev.target.dataset.pref){const s=getState();saveState({...s,preferences:{...s.preferences,[ev.target.dataset.pref]:ev.target.checked}});applyAccess();}});
const num=id=>{const v=Number($(id).value);if(!Number.isFinite(v)||v<=0)throw Error('Enter positive numbers for every input.');return v;};
async function filePicker(accept){return new Promise(resolve=>{const i=document.createElement('input');i.type='file';i.accept=accept;i.onchange=()=>resolve(i.files[0]);i.oncancel=()=>resolve(null);i.click();});}
function csvRows(raw){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<raw.length;i++){const c=raw[i];if(c==='"'){if(quoted&&raw[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&raw[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function parseFrameTimes(raw){const rows=csvRows(raw);if(!rows.length)throw Error('No frame samples found.');const header=rows[0].map(x=>x.trim().toLowerCase());let index=header.findIndex(h=>['msbetweenpresents','frametime','frame time','frametime (ms)','frame_time_ms','frametime_ms'].includes(h));let data=rows;if(index>=0)data=rows.slice(1);else if(rows[0].length===1&&Number.isFinite(Number(rows[0][0])))index=0;else throw Error('CSV needs a frame-time column in milliseconds: MsBetweenPresents or frame_time_ms.');const values=data.map(row=>Number(row[index]));if(values.some(v=>!Number.isFinite(v)||v<=0)||values.length>500000)throw Error('Frame times must be positive, with at most 500,000 samples.');return values;}
export async function toolsAction(action,ctx={}){
 const {record,show,button,actions,render,filter,gameOptions}=ctx;
 if(action==='show-attachments'){const host=$('#cc-attachments');if(!host)return;for(const attachment of record.data.attachments||[]){const file=await mediaGet(attachment.id);if(!host.isConnected)return;if(!file)continue;const url=URL.createObjectURL(file);disposers.push(()=>URL.revokeObjectURL(url));const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=url;img.alt=attachment.name;img.style='max-width:100%;max-height:500px;object-fit:contain';caption.textContent=attachment.name;figure.append(img,caption);host.append(figure);}return;}
 if(action==='access-save'||action==='access-reset'){saveAccessPreset(filter,action==='access-reset');render();return;}
 if(action==='sync')return openSync(ctx);
 if(action==='calendar-export'){const records=getState().records.filter(r=>r.kind==='event'&&(filter==='all'||r.game===filter));if(!records.length)throw Error('Add an event first.');download('dropzone-calendar.ics',exportCalendar(records),'text/calendar');return;}
 if(action==='calendar-import'){const file=await filePicker('.ics');if(!file)return;if(file.size>2000000)throw Error('Calendar exceeds 2 MB.');const records=importCalendar(await file.text(),filter==='all'?'wardogs':filter);show(`<h2>Review calendar import</h2><p>${records.length} one-time events. Times below use your device’s timezone.</p>${records.map(r=>`<p><b>${e(r.title)}</b> · ${new Date(r.data.when).toLocaleString()}</p>`).join('')}${actions(button('calendar-confirm','Import events')+button('close','Cancel'))}`);$('[data-cc="calendar-confirm"]').onclick=()=>{for(const r of records)saveRecord(r);$('#cc-dialog').close();render();};return;}
 if(action==='calc-sensitivity'){const r=sensitivity({dpi:num('#calc-dpi'),sensitivity:num('#calc-sens'),yaw:num('#calc-yaw'),targetDpi:num('#calc-target-dpi'),targetYaw:num('#calc-target-yaw')});$('#calc-sensitivity-result').textContent=`${r.cm360.toFixed(2)} cm / 360° · target sensitivity ${r.targetSensitivity.toFixed(6)}`;return;}
 if(action==='calc-display'){const fps=num('#calc-fps'),w=num('#calc-width'),h=num('#calc-height');const gcd=(a,b)=>b?gcd(b,a%b):a;if(!Number.isInteger(w)||!Number.isInteger(h))throw Error('Resolution dimensions must be whole pixels.');const d=gcd(w,h);$('#calc-display-result').textContent=`${(1000/fps).toFixed(2)} ms per frame · ${w/d}:${h/d} aspect ratio`;return;}
 if(action==='calc-damage'){const hp=num('#calc-hp'),damage=num('#calc-damage'),rpm=num('#calc-rpm'),shots=Math.ceil(hp/damage);$('#calc-damage-result').textContent=`${shots} hits · ${((shots-1)*60/rpm).toFixed(3)} seconds of firing time`;return;}
 if(action==='configure-launch'||action==='configure-companion'){if(!api.command)throw Error('Use the Windows app to configure launchers.');const r=await api.command({action:'configure-launch',game:$('#cc-launch-game').value,companion:action==='configure-companion'});$('#cc-launch-status').textContent=r.canceled?'No change.':'Selected '+r.name;return;}
 if(action==='launch-status'){if(!api.command)throw Error('Desktop configuration is unavailable in a browser.');const r=await api.command({action:'launch-status'});$('#cc-launch-status').textContent=Object.entries(r).map(([k,v])=>k+': '+v).join(' · ')||'No launchers configured.';return;}
 if(action==='backup-settings-file'){if(!api.command)throw Error('Use the Windows app for native settings backups.');const game=filter==='all'?'wardogs':filter;const r=await api.command({action:'settings-backup',game});if(!r.canceled){saveRecord({kind:'settings',game,title:r.name+' backup',body:'Native settings file backup.',data:{backupId:r.id,size:r.size}});render();}return;}
 if(action==='health'){if(!api.command)throw Error('Native diagnostics are available in the Windows app.');const r=await api.command({action:'health'});$('#cc-health').textContent=`App main process: ${(r.appMemory/1048576).toFixed(0)} MB · free system RAM: ${(r.freeMemory/1073741824).toFixed(1)} GB · ${r.cpu}. This is not game FPS telemetry.`;return;}
 if(action==='feedback-save'){const body=$('#cc-feedback-body').value.trim();if(!body)throw Error('Describe what happened first.');const report={app:'Dropzone',version:APP_VERSION,game:filter,category:$('#cc-feedback-type').value,source:$('#cc-feedback-source').value,body};show(`<h2>Review report</h2><pre style="white-space:pre-wrap">${e(JSON.stringify(report,null,2))}</pre>${actions(button('report-export','Save & export')+button('close','Cancel'))}`);$('[data-cc="report-export"]').onclick=()=>{saveRecord({kind:'feedback',game:filter==='all'?'wardogs':filter,title:report.category,body,source:report.source,data:{version:APP_VERSION}});download('dropzone-feedback.json',report);$('#cc-dialog').close();};return;}
 if(action==='parse-performance'){const {values}=ctx;let raw=values.samples||'';if(values.csv?.size){if(values.csv.size>30000000)throw Error('CSV exceeds 30 MB.');raw=await values.csv.text();}const samples=parseFrameTimes(raw),summary=performanceSummary(samples);return {summary,samples:samples.length<=5000?samples:[],sampleCount:samples.length};}
 if(action==='performance-record'){const s=record.data.summary;return s?`<div class="cc-demo-metrics"><div><strong class="cc-stat">${s.averageFps.toFixed(1)}</strong><p>Average FPS</p></div><div><strong class="cc-stat">${s.onePercentLow.toFixed(1)}</strong><p>1% low · slowest frames’ mean</p></div><div><strong class="cc-stat">${s.p99Ms.toFixed(2)}</strong><p>p99 frame time (ms)</p></div></div><p>${s.frames.toLocaleString()} imported samples · ${e(record.data.setup||'No setup notes')}</p><h3>Other runs</h3><table class="cc-table">${getState().records.filter(r=>r.kind==='performance'&&r.game===record.game&&r.data.summary).map(r=>`<tr><th>${e(r.title)}</th><td>${r.data.summary.averageFps.toFixed(1)} FPS</td><td>${(r.data.summary.averageFps-s.averageFps).toFixed(1)} vs this run</td></tr>`).join('')}</table>`:'<p>No imported frame-time samples.</p>';}
 if(action==='compare'){const candidates=getState().records.filter(r=>r.kind==='build'&&r.game===record.game&&r.id!==record.id);show(`<h2>Compare ${e(record.title)}</h2><label>Other build<select id="cc-compare">${opts(candidates.map(r=>[r.id,r.title]),candidates[0]?.id)}</select></label><div id="cc-comparison"></div>${button('close','Close')}`);const paint=()=>{const other=candidates.find(r=>r.id===$('#cc-compare').value);$('#cc-comparison').innerHTML=other?`<p>${e(record.data.measurement||'Personal values')} / ${e(other.data.measurement||'Personal values')}</p><table class="cc-table"><thead><tr><th>Metric</th><th>This build</th><th>Other build</th><th>Change</th></tr></thead><tbody>${compareMetrics(record.data.metrics,other.data.metrics).map(r=>`<tr><th>${e(r.key)}</th><td>${r.a??'Unknown'}</td><td>${r.b??'Unknown'}</td><td>${r.delta===null?'Unknown':(r.delta>0?'+':'')+r.delta}</td></tr>`).join('')}</tbody></table><p>Compare matching units and test conditions. Higher does not automatically mean better.</p>`:'<p>Save another build for this game first.</p>';};$('#cc-compare').onchange=paint;paint();return;}
 if(action==='export-all-content'){download('dropzone-content.json',pack(getState().records.filter(r=>['build','strategy','note','goal','routine','team'].includes(r.kind)),'My library'));return;}
 if(action==='import-existing'){
  let count=0;const game=filter==='all'?null:filter;for(const b of JSON.parse(localStorage.getItem('tbb-saved-loadouts')||'[]')){if(game&&game!==b.game||!GAMES.includes(b.game))continue;saveRecord({kind:'build',game:b.game,title:b.build.weapon+' · '+b.mode,body:'Copied from your saved COD build.',source:b.sourceUrl,patch:b.sourceUpdatedAt,data:{pick:b.build.weapon,mode:b.mode,equipment:(b.build.attachments||[]).map(x=>typeof x==='string'?x:JSON.stringify(x)).join('\n')}});count++;}
  for(const b of JSON.parse(localStorage.getItem('tbb-finals-saves')||'[]')){if(game&&game!=='finals')continue;saveRecord({kind:'build',game:'finals',title:b.name||b.title||'Saved FINALS setup',body:JSON.stringify(b.players||[],null,2),data:{mode:'Saved setup'}});count++;}for(const b of JSON.parse(localStorage.getItem('rf-saved')||'[]')){if(game&&game!=='lol')continue;saveRecord({kind:'build',game:'lol',title:(b.champion||'Champion')+' · '+(b.mode||'Saved build'),body:JSON.stringify({build:b.build,threats:b.threats,overrides:b.overrides},null,2).slice(0,16000),data:{pick:b.champion||'',mode:b.mode||'',measurement:'Copied personal League build'}});count++;}toast(`Copied ${count} builds.`);return;
 }
 if(action==='backup'){
  $('#cc-backup-status').textContent='Collecting saves and media…';const value=backupStorage(localStorage);value.settingsBackups=api.command?await api.command({action:'settings-export-all'}):[];value.media=[];let total=0;for(const [id,file]of await mediaEntries()){total+=file.size;if(total>250*1024*1024)throw Error('Media exceeds 250 MB. Export clips separately before creating a portable backup.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));value.media.push({id,name:file.name||id,type:file.type,data:btoa(binary)});}
  const blob=new Blob([JSON.stringify(value)]),compressed=await new Response(blob.stream().pipeThrough(new CompressionStream('gzip'))).blob();download('dropzone-backup-'+new Date().toISOString().slice(0,10)+'.json.gz',compressed);$('#cc-backup-status').textContent='Backup exported. Keep it somewhere safe.';return;
 }
 if(action==='restore'){
  const file=await filePicker('.json,.gz');if(!file)return;if(file.size>350*1024*1024)throw Error('Backup is too large.');const raw=await readBackupText(file);const value=JSON.parse(raw);let entries=validateBackup({...value,media:undefined,settingsBackups:undefined});if(!Array.isArray(value.media||[]))throw Error('Invalid media list.');const files=[];let total=0;for(const m of value.media||[]){if(typeof m.id!=='string'||m.id.length>100||!m.data||typeof m.type!=='string')throw Error('Invalid media entry.');const bytes=Uint8Array.from(atob(m.data),c=>c.charCodeAt(0));total+=bytes.length;if(total>250*1024*1024)throw Error('Media exceeds 250 MB.');files.push([m.id,new File([bytes],m.name||m.id,{type:m.type})]);}
  const remapped=remapRestoredMedia(entries,files);entries=remapped.entries;files.splice(0,files.length,...remapped.files);
  show(`<h2>Restore workspace?</h2><p>${Object.keys(entries).length} saved settings and ${files.length} media files. Matching settings will be replaced. A rollback JSON is downloaded first; imported media receives new IDs so current files remain recoverable.</p>${actions(button('restore-confirm','Restore')+button('close','Cancel'))}`);$('[data-cc="restore-confirm"]').onclick=async()=>{try{download('dropzone-before-restore.json',backupStorage(localStorage));if(value.settingsBackups?.length&&api.command)await api.command({action:'settings-import-all',entries:value.settingsBackups});for(const [id,file]of files)await mediaPut(id,file);restoreStorage(localStorage,entries);resetMemory();$('#cc-dialog').close();render();toast('Restored. Restart Dropzone to refresh older game tools.');}catch(err){toast(err.message);}};return;
 }
 if(action==='clip-open'){
  const video=$('#cc-video'),host=$('#cc-clip-tools'),file=record.data.mediaId?await mediaGet(record.data.mediaId):null;if(!video.isConnected)return;if(!file){video.hidden=true;host.textContent='No local video on this PC. Use Edit to attach it, or open the source link.';return;}
  const url=URL.createObjectURL(file);video.src=url;let recorder,stopTimer,capture,canceled=false,segmentEnd=null;disposers.push(()=>{canceled=true;clearTimeout(stopTimer);video.pause();if(recorder?.state==='recording')recorder.stop();capture?.getTracks().forEach(t=>t.stop());URL.revokeObjectURL(url);});
  host.innerHTML='<div class="cc-actions"><button id="cc-clip-seek">Play saved segment</button><button id="cc-clip-export">Export segment as WebM</button><button id="cc-clip-original">Export original</button></div><p id="cc-clip-status" role="status">Segment export re-encodes in real time while the video plays.</p>';
  bindClipMoments(record,video,host);
  const bounds=()=>{const start=Number(record.data.start)||0,end=Number(record.data.end)||video.duration;if(!Number.isFinite(end)||end<=start||end>video.duration+.1)throw Error('Set a valid start and end within the video duration.');return {start,end:Math.min(end,video.duration)};};
  video.addEventListener('timeupdate',()=>{if(segmentEnd!==null&&video.currentTime>=segmentEnd){segmentEnd=null;video.pause();if(recorder?.state==='recording')recorder.stop();}});
  $('#cc-clip-original').onclick=()=>download(record.data.mediaName||'clip.webm',file);
  $('#cc-clip-seek').onclick=async()=>{try{const {start,end}=bounds();video.currentTime=start;await video.play();if(canceled){video.pause();return;}clearTimeout(stopTimer);segmentEnd=end;}catch(err){toast(err.message);}};
  $('#cc-clip-export').onclick=async()=>{try{if(recorder?.state==='recording')return;const {start,end}=bounds();if(!video.captureStream||!window.MediaRecorder)throw Error('This browser cannot export clips. Use the Windows app or export the original.');video.pause();video.currentTime=start;await new Promise(resolve=>{if(!video.seeking)resolve();else video.addEventListener('seeked',resolve,{once:true});});if(canceled)return;await video.play();if(canceled){video.pause();return;}const stream=capture=video.captureStream();const chunks=[];recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'});recorder.ondataavailable=ev=>{if(ev.data.size)chunks.push(ev.data);};recorder.onstop=()=>{video.pause();stream.getTracks().forEach(t=>t.stop());if(!canceled&&chunks.length)download('dropzone-segment.webm',new Blob(chunks,{type:'video/webm'}));if(!canceled&&$('#cc-clip-status'))$('#cc-clip-status').textContent='Segment exported.';};recorder.start(200);$('#cc-clip-status').textContent='Exporting… keep this view open.';segmentEnd=end;}catch(err){toast(err.message);}};return;
 }
 if(action==='readiness'){
  show(`<header><h2>Audio & readiness</h2>${button('close','Close')}</header><p>Check your microphone and playback device before you queue. No audio is uploaded or saved.</p><div class="cc-actions"><button id="cc-mic">Enable microphone test</button><button id="cc-audio-test">Play test tone</button></div><label>Microphone<select id="cc-mic-select"></select></label><label>Output device<select id="cc-output-select"></select></label><meter id="cc-meter" min="0" max="1" value="0" style="width:100%"></meter><p id="cc-audio-status" role="status">Microphone is off. Game updates and controller battery cannot be checked here.</p>`);
  let stream,audioContext,frame,alive=true,micRequest=0;disposers.push(()=>{alive=false;stream?.getTracks().forEach(t=>t.stop());audioContext?.close();cancelAnimationFrame(frame);});
  const start=async()=>{const request=++micRequest;try{stream?.getTracks().forEach(t=>t.stop());if(api.command)await api.command({action:'microphone'});if(!alive)return;const opened=await navigator.mediaDevices.getUserMedia({audio:$('#cc-mic-select').value?{deviceId:{exact:$('#cc-mic-select').value}}:true,video:false});if(!alive||request!==micRequest){opened.getTracks().forEach(t=>t.stop());return;}stream=opened;const devices=await navigator.mediaDevices.enumerateDevices();if(!alive||request!==micRequest)return;const chosen=$('#cc-mic-select').value;$('#cc-mic-select').innerHTML=opts(devices.filter(d=>d.kind==='audioinput').map(d=>[d.deviceId,d.label||'Microphone']),chosen);$('#cc-output-select').innerHTML=opts(devices.filter(d=>d.kind==='audiooutput').map(d=>[d.deviceId,d.label||'Output device']),'default');audioContext??=new AudioContext();const analyser=audioContext.createAnalyser();audioContext.createMediaStreamSource(stream).connect(analyser);const samples=new Uint8Array(analyser.fftSize);const tick=()=>{if(!$('#cc-meter'))return;analyser.getByteTimeDomainData(samples);$('#cc-meter').value=Math.sqrt(samples.reduce((sum,v)=>sum+((v-128)/128)**2,0)/samples.length)*4;frame=requestAnimationFrame(tick);};cancelAnimationFrame(frame);tick();$('#cc-audio-status').textContent='Microphone test active. Closing this view stops it.';}catch(err){if(alive&&$('#cc-audio-status'))$('#cc-audio-status').textContent='Microphone unavailable: '+err.message;}};
  $('#cc-mic').onclick=start;$('#cc-mic-select').onchange=start;$('#cc-audio-test').onclick=async()=>{try{audioContext??=new AudioContext();if(audioContext.setSinkId&&$('#cc-output-select').value)await audioContext.setSinkId($('#cc-output-select').value);const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();gain.gain.value=.03;oscillator.frequency.value=440;oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.35);}catch(err){toast(err.message);}};return;
 }
 if(action==='voice'){
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;show(`<h2>Voice commands</h2><p>Commands: “open session”, “show builds”, “show map”, “show notes”. Voice recognition may use your browser’s speech service. It starts only after you press Listen.</p><div id="cc-voice-status" role="status"></div>${actions(button('voice-listen','Listen once')+button('close','Close'))}`);if(!Recognition){$('#cc-voice-status').textContent='Speech recognition is unavailable in this runtime. Keyboard shortcuts remain available.';return;}const listenButton=$('[data-cc="voice-listen"]');listenButton.onclick=async()=>{if(api.command)await api.command({action:'microphone'});if(!listenButton.isConnected)return;const recognition=new Recognition();recognition.lang='en-US';recognition.continuous=false;recognition.onresult=ev=>{const said=ev.results[0][0].transcript.toLowerCase();$('#cc-voice-status').textContent=said;if(said.includes('session'))ctx.navigate('command');else if(said.includes('build'))ctx.navigate('saved');else if(said.includes('map'))ctx.navigate(filter==='all'?'wardogs':filter);else if(said.includes('note'))document.querySelector('[data-tab="note"]')?.click();};recognition.onerror=()=>{if($('#cc-voice-status'))$('#cc-voice-status').textContent='Recognition failed. Try again or use keyboard controls.';};recognition.start();disposers.push(()=>recognition.abort());};return;
 }
}
