import {$,api,e,date,toast,stored,persist,opts} from './shared.js';
import {resolveTeam,teamReview} from './team-model.js';
const classes=['Light','Medium','Heavy'];
const classRoles={Light:'Movement, disruption, and quick angles.',Medium:'Healing, revives, and creative access.',Heavy:'Space, pressure, and objective control.'};
const initial=stored('tbb-finals-saves',[]);
const s={active:false,data:null,error:null,loading:false,request:0,tab:'classes',className:'Medium',build:null,weapon:null,team:'hhm',saved:Array.isArray(initial)?initial.filter(x=>x?.id&&['build','team'].includes(x.kind)&&Array.isArray(x.players)):[]};
export function leaveFinals(){s.active=false;s.request++;}
export async function mountFinals(){s.active=true;await load();}
async function load(refresh=false){
  const request=++s.request;s.loading=true;s.error=null;render();
  try{const data=await api.loadouts({game:'finals',mode:'ranked',refresh});if(request!==s.request)return;if(!data.builds?.length||!data.teamPresets?.teams?.length||data.game!=='finals')throw new Error(data.error||'No complete ranked class loadouts were returned.');s.data=data;ensureBuild();}
  catch(error){if(request!==s.request)return;s.error=error.message;}
  if(request!==s.request)return;s.loading=false;render();
}
function ensureBuild(){const choices=s.data.builds.filter(b=>b.className===s.className);if(!choices.some(b=>b.id===s.build))s.build=choices[0]?.id;const b=chosen();if(!b?.weapons.includes(s.weapon))s.weapon=b?.weapons[0];}
function chosen(){return s.data?.builds.find(b=>b.id===s.build&&b.className===s.className);}
function gear(b,weapon){return `<dl class="finals-gear"><div class="primary-gear"><dt>WEAPON</dt><dd>${e(weapon)}</dd></div><div><dt>SPECIALIZATION</dt><dd>${e(b.specialization)}</dd></div>${b.gadgets.map((g,i)=>`<div><dt>GADGET ${i+1}</dt><dd>${e(g)}</dd></div>`).join('')}</dl>`;}
function sources(){const d=s.data,p=d.official;return `<details class="source-disclosure finals-source"><summary>Sources and update dates</summary><p>${e(d.methodology)}</p><div class="freshness-dates"><span>Build review <strong>${date(d.sourceUpdatedAt)}</strong></span><span>Build patch <strong>${e(d.patch)}</strong></span><span>Last successful fetch <strong>${date(d.fetchedAt)}</strong></span><span>Official release <strong>${e(p?.latest?.patch||'Unavailable')}</strong></span></div><div class="hub-action-row"><button class="source-link" data-hub-source="${e(d.sourceUrl)}">Community loadout source ↗</button><button class="source-link" data-hub-source="https://www.reachthefinals.com/patchnotes">Official patch notes ↗</button><button class="source-link" data-route="updates">All update checks</button></div></details>`;}
function classView(){
  const b=chosen();return `<div class="finals-class-tabs" role="group" aria-label="Contestant class">${classes.map(c=>`<button class="class-tab ${c===s.className?'active':''}" data-finals-class="${c}" aria-pressed="${c===s.className}"><b>${c[0]}</b><span><strong>${c}</strong><small>${c==='Light'?'150':c==='Medium'?'250':'350'} HP</small></span></button>`).join('')}</div><div class="finals-layout"><aside class="finals-class-panel"><div class="class-art"><img src="assets/games/finals-${s.className.toLowerCase()}.webp" alt="Official ${s.className} contestant artwork"><div><span class="hub-eyebrow">CLASS</span><h2>${s.className}</h2><p>${classRoles[s.className]}</p></div></div><div class="finals-build-list">${s.data.builds.filter(b=>b.className===s.className).map(b=>`<button data-finals-build="${e(b.id)}" class="${b.id===s.build?'active':''}"><span class="finals-tier">${e(b.tier)}</span><span><strong>${e(b.name)}</strong><small>${e(b.specialization)}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div></aside><section class="finals-build-detail">${b?`<div class="finals-detail-heading"><div><span class="hub-eyebrow">${e(b.className.toUpperCase())} // COMMUNITY ${e(b.tier)} TIER</span><h2>${e(b.name)}</h2></div><button class="hub-button secondary" data-finals-action="save-build">Save build</button></div><p class="muted">Recommended weapon, specialization, and gadgets.</p>${b.weapons.length>1?`<label class="finals-weapon-picker"><span>CHOOSE ONE WEAPON</span><select id="finals-weapon" aria-label="Primary weapon">${opts(b.weapons.map(w=>[w,w]),s.weapon)}</select></label>`:''}${gear(b,s.weapon)}<div class="finals-alternatives"><strong>Alternatives</strong><p>${e(b.alternatives.join(' · '))}</p><small>Source alternatives; equip only three active gadgets.</small></div><div class="hub-action-row"><button class="hub-button" data-finals-action="copy-build">Copy full loadout</button><button class="source-link" data-hub-source="${e(b.sourceUrl)}">View original build ↗</button></div>`:'<p>No build is available for this class.</p>'}</section></div>`;
}
function currentTeam(){const preset=s.data.teamPresets.teams.find(t=>t.id===s.team)||s.data.teamPresets.teams[0];s.team=preset.id;return resolveTeam(preset,s.data.builds);}
function teamsView(){
  const team=currentTeam(),review=teamReview(s.data);
  return `<div class="team-intro"><div><span class="hub-eyebrow">SEASON ${e(s.data.season)} // RANKED CASHOUT</span><h2>Meta team comps</h2><p>Class builds refresh automatically. Comp choices and fixed weapon picks were reviewed separately on ${date(s.data.teamPresets.reviewedAt)}.</p></div></div><div class="team-preset-tabs" role="group" aria-label="Meta team compositions">${s.data.teamPresets.teams.map(t=>`<button class="${t.id===s.team?'active':''}" data-finals-team="${t.id}" aria-pressed="${t.id===s.team}"><strong>${e(t.comp)}</strong><small>${e(t.tag)}</small></button>`).join('')}</div><div class="team-strategy"><div><h2>${e(team.name)}</h2><p>${e(team.description)}</p><p><strong>Weakness:</strong> ${e(team.tradeoff)}</p></div><div class="hub-action-row"><button class="hub-button" data-finals-action="copy-team" ${team.valid?'':'disabled'}>Copy team loadouts</button><button class="hub-button secondary" data-finals-action="save-team" ${team.valid?'':'disabled'}>Save team</button></div></div><div class="team-player-grid">${team.players.map((p,i)=>`<article class="team-player"><div class="team-player-head"><span class="player-number">0${i+1}</span><img src="assets/games/finals-${p.className.toLowerCase()}.webp" alt=""><div><span class="hub-eyebrow">${e(p.className.toUpperCase())}</span><h3>${e(p.role)}</h3></div></div><div class="team-player-body">${p.valid?`${gear(p.build,p.weapon)}<p>${e(p.task)}</p><button class="source-link" data-hub-source="${e(p.build.sourceUrl)}">Loadout source ↗</button>`:'<div class="cod-notice">This loadout changed at the source and needs a new team review.</div>'}</div></article>`).join('')}</div>${review.warning?`<div class="cod-notice">${e(review.message)}</div>`:''}<details class="source-disclosure team-evidence"><summary>Why this comp · reviewed ${date(s.data.teamPresets.reviewedAt)}</summary><p>${e(team.evidence.creator)}: <button class="source-link" data-hub-source="${e(team.evidence.url)}">${e(team.evidence.title)} ↗</button> · ${date(team.evidence.publishedAt)}</p><p>${e(team.evidence.note)}</p><p>${e(s.data.teamPresets.methodology)}</p><p>${e(review.message)}</p><button class="source-link" data-hub-source="https://thefinalsloadout.com/specializations">Current specialization guide ↗</button></details>`;
}
function savesView(){return `<div class="team-intro"><div><span class="hub-eyebrow">SAVED BUILDS</span><h2>Saved loadouts</h2><p>These are snapshots. Refreshing the source does not rewrite your saved equipment.</p></div></div><div class="finals-saved-grid">${s.saved.map(x=>`<article class="finals-saved"><span class="hub-eyebrow">${x.kind==='team'?'TEAM COMPOSITION':'CLASS BUILD'} // SEASON ${e(x.season)}</span><h3>${e(x.name)}</h3><p>Saved ${date(x.savedAt)} · source review ${date(x.sourceUpdatedAt)} · patch ${e(x.patch)}</p><details><summary>See complete equipment</summary>${x.players.map(p=>`<h4>${e(p.className)} · ${e(p.name)}</h4>${gear(p,p.weapon)}`).join('')}</details><div class="hub-action-row"><button class="hub-button secondary" data-finals-copy-saved="${e(x.id)}">Copy snapshot</button><button class="source-link" data-finals-delete="${e(x.id)}">Remove</button></div></article>`).join('')||'<div class="cod-empty"><h2>No saved loadouts</h2><p>Save a class loadout or a full team composition.</p><button class="hub-button" data-finals-tab="classes">Find a loadout</button></div>'}</div>`;}
function render(){if(!s.active)return;const d=s.data;
  const previous=$('.finals-page'),scroll=previous?.scrollTop||0,focused=document.activeElement;
  const focusKey=focused&&previous?.contains(focused)?[...focused.attributes].find(a=>a.name==='id'||a.name.startsWith('data-finals-')):null;
  const openDetails=previous?[...previous.querySelectorAll('details')].map(x=>x.open):[];
  $('#hub-app').innerHTML=`<main class="hub-main finals-page"><section class="finals-hero"><img src="assets/games/finals.webp" alt=""><div><span class="hub-eyebrow">${d?'SEASON '+e(d.season):'SEASON 11'} // RANKED CASHOUT</span><h1>THE FINALS</h1><p>Ranked loadouts and team compositions.</p><div class="hub-action-row"><button class="hub-button" data-watch-game="finals">Videos & tournaments</button><button class="hub-button secondary" data-finals-action="refresh" ${s.loading?'disabled':''}>${s.loading?'Checking sources…':'Refresh builds'}</button></div></div></section><div class="playlist-tabs finals-section-tabs" role="group" aria-label="THE FINALS page">${[['classes','Class loadouts'],['teams','Meta team comps'],['saved','Saved loadouts'+(s.saved.length?' · '+s.saved.length:'')]].map(([id,label])=>`<button data-finals-tab="${id}" class="${s.tab===id?'active':''}" aria-pressed="${s.tab===id}">${label}</button>`).join('')}</div>${s.error?`<div class="cod-notice error">${e(s.error)} <button data-finals-action="refresh">Try again</button></div>`:''}${d?`<div class="finals-freshness ${d.freshness.level==='warning'?'warning':''}"><span class="feed-dot"></span><p>${e(d.freshness.message)}</p><button data-route="updates">Update details</button></div>${s.tab==='classes'?classView():s.tab==='teams'?teamsView():savesView()}${sources()}`:`<div class="cod-loading"><h2>${s.loading?'Loading ranked loadouts…':'The build source is unavailable.'}</h2><p>Checking community builds and Embark’s official patch feed.</p></div>`}</main>`;
  const page=$('.finals-page');
  page.querySelectorAll('details').forEach((x,i)=>{if(openDetails[i])x.open=true;});
  if(focusKey){const match=[...page.querySelectorAll('button,select,input')].find(x=>x.getAttribute(focusKey.name)===focusKey.value);match?.focus({preventScroll:true});}
  page.scrollTop=scroll;
}
function record(kind){const d=s.data,b=chosen(),t=kind==='team'?currentTeam():null;if(t&&!t.valid)throw new Error('This team needs a source review before it can be saved.');return {id:crypto.randomUUID(),kind,name:t?t.comp+' · '+t.name:b.name,season:d.season,patch:d.patch,sourceUpdatedAt:d.sourceUpdatedAt,savedAt:new Date().toISOString(),players:t?t.players.map(p=>({...structuredClone(p.build),weapon:p.weapon,role:p.role})): [{...structuredClone(b),weapon:s.weapon}],strategy:t?{description:t.description,tradeoff:t.tradeoff,reviewedPatch:d.teamPresets.reviewedPatch}:null};}
function copyText(r){return `DROPZONE\nTHE FINALS · Ranked Cashout · Season ${r.season}\n${r.name}\nSource build review: ${date(r.sourceUpdatedAt)} · patch ${r.patch}\n${r.strategy?'Team recommendation: '+r.strategy.description+'\nTradeoff: '+r.strategy.tradeoff+'\n':''}\n${r.players.map((p,i)=>`PLAYER ${i+1} · ${p.className} · ${p.name}\nWeapon: ${p.weapon}\nSpecialization: ${p.specialization}\n${p.gadgets.map((g,j)=>'Gadget '+(j+1)+': '+g).join('\n')}\nSource: ${p.sourceUrl}`).join('\n\n')}`;}
document.addEventListener('click',async event=>{
  const b=event.target.closest('button');if(!b||!s.active)return;
  try{
    if(b.dataset.finalsTab){s.tab=b.dataset.finalsTab;render();return;}
    if(b.dataset.finalsClass){if(!classes.includes(b.dataset.finalsClass))return;s.className=b.dataset.finalsClass;ensureBuild();render();return;}
    if(b.dataset.finalsBuild){s.build=b.dataset.finalsBuild;ensureBuild();render();return;}
    if(b.dataset.finalsTeam){s.team=b.dataset.finalsTeam;render();return;}
    if(b.dataset.finalsDelete){const next=s.saved.filter(x=>x.id!==b.dataset.finalsDelete);persist('tbb-finals-saves',next);s.saved=next;render();return;}
    if(b.dataset.finalsCopySaved){const r=s.saved.find(x=>x.id===b.dataset.finalsCopySaved);if(r){await api.copy(copyText(r));toast('Saved loadouts copied.');}return;}
    const action=b.dataset.finalsAction;if(!action)return;
    if(action==='refresh')return load(true);
        const r=record(action.endsWith('team')?'team':'build');
    if(action.startsWith('copy')){await api.copy(copyText(r));toast(r.kind==='team'?'All three player builds copied.':'Full class loadout copied.');}
    if(action.startsWith('save')){const next=[r,...s.saved].slice(0,40);persist('tbb-finals-saves',next);s.saved=next;toast('Loadout saved.');render();}
  }catch(error){toast(error.message);}
});
document.addEventListener('change',event=>{if(!s.active||!s.data)return;const el=event.target;
  if(el.id==='finals-weapon'){s.weapon=el.value;ensureBuild();render();return;}

});
window.addEventListener('tbb-sources-updated',()=>{if(s.active&&!s.loading)load();});
