import {sourceStatus} from './source-status.js';
import {$,api,e,date,toast,stored,persist,opts} from './shared.js';
import {resolveTeam,teamReview} from './team-model.js';

const classes=['Light','Medium','Heavy'];
const classRoles={Light:'Movement & disruption',Medium:'Healing & team support',Heavy:'Space & objective control'};
const classHealth={Light:150,Medium:250,Heavy:350};
const initial=stored('tbb-finals-saves',[]);
const s={active:false,data:null,error:null,loading:false,request:0,tab:'classes',className:'Medium',build:null,weapon:null,team:'hhm',saved:Array.isArray(initial)?initial.filter(x=>x?.id&&['build','team'].includes(x.kind)&&Array.isArray(x.players)):[]};
const confirmations=new Map();
function clearConfirmations(){for(const timer of confirmations.values())clearTimeout(timer);confirmations.clear();}
export function leaveFinals(){s.active=false;s.request++;clearConfirmations();}
export async function mountFinals(tab){s.tab=['classes','teams','saved'].includes(tab)?tab:'classes';s.active=true;await load();}
async function load(refresh=false){
  const request=++s.request;s.loading=true;s.error=null;render();
  try{const data=await api.loadouts({game:'finals',mode:'ranked',refresh});if(request!==s.request)return;if(!Array.isArray(data.builds)||data.game!=='finals')throw new Error(data.error||'The build source did not return usable loadouts.');s.data=data;ensureBuild();}
  catch(error){if(request!==s.request)return;s.error=error.message;}
  if(request!==s.request)return;s.loading=false;render();
}
function ensureBuild(){const choices=s.data.builds.filter(b=>b.className===s.className);if(!choices.some(b=>b.id===s.build))s.build=choices[0]?.id;const b=chosen();if(!b?.weapons.includes(s.weapon))s.weapon=b?.weapons[0];}
function chosen(){return s.data?.builds.find(b=>b.id===s.build&&b.className===s.className);}
function symbol(name='',kind='gadget'){
  let path;
  if(kind==='copy')path='<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h3"/>';
  else if(kind==='save')path='<path d="M6 4h12v17l-6-4-6 4Z"/>';
  else if(/heal|infuser|defibrillator/i.test(name))path='<path d="M9 3h6v6h6v6h-6v6H9v-6H3V9h6Z"/><path d="m10 12 2-3v6l2-3"/>';
  else if(/shield|barricade|aps/i.test(name))path='<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="M12 6v12M7 9h10"/>';
  else if(/pad|dash|grappl|gateway/i.test(name))path='<path d="m7 13 5-8 5 8M12 5v12M4 19h16M6 22h12"/>';
  else if(/cloak|vanish|smoke/i.test(name))path='<path d="M3 12s3-6 9-6 9 6 9 6-3 6-9 6-9-6-9-6Z"/><circle cx="12" cy="12" r="3"/><path d="m3 3 18 18"/>';
  else if(/sonar|glitch|shock|reshap|nullifier|dematerial/i.test(name))path='<path d="m13 2-8 12h6l-1 8 9-13h-7Z"/>';
  else if(/sword|dagger|kniv/i.test(name))path='<path d="m5 19 3-3m2-2L19 3l2 2-9 11M6 13l5 5M3 21l2-2"/>';
  else if(/bow/i.test(name))path='<path d="M6 3q18 9 0 18L6 3M6 12h15m-4-4 4 4-4 4"/>';
  else if(kind==='weapon')path='<path d="M3 9h13v5H9l-2 6H3l3-7H2V9m14 1h6v3h-6M10 6h5v3M9 14l3 4h3l-2-4"/>';
  else if(/rpg/i.test(name))path='<path d="m3 9 15-3 3 2-2 3-15 3ZM9 13l-1 6h3l2-7M5 6l1 3M16 4l1 2"/>';
  else if(/winch/i.test(name))path='<path d="M12 3v8a5 5 0 1 1-5 5M9 3h6M7 16l-3-1 3-3"/>';
  else if(/charge|slam/i.test(name))path='<path d="m13 3-7 9h6l-1 8 8-11h-6M3 21h18"/>';
  else if(kind==='alternative')path='<path d="m12 3 9 5v9l-9 5-9-5V8Zm-9 5 9 5 9-5M12 13v9M7 5l10 6"/>';
  else path='<path d="M10 3h4v4l4 4v7a3 3 0 0 1-3 3H9a3 3 0 0 1-3-3v-7l4-4ZM14 4h5l2 3M7 13h10"/>';
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
}
function equipment(name,kind='gadget',slot=''){
  const iconKind=kind==='alternative'&&s.data?.builds.some(b=>b.weapons.includes(name))?'weapon':kind;
  return `<div class="fn-equipment fn-equipment-${kind}"><span class="fn-equipment-symbol">${symbol(name,iconKind)}</span><div><small>${kind==='specialization'?'Specialization':kind==='weapon'?'Primary weapon':slot?'Gadget '+slot:'Alternative equipment'}</small><strong>${e(name)}</strong></div>${slot?`<span class="fn-slot-number" aria-hidden="true">0${slot}</span>`:''}</div>`;
}
function gear(b,weapon){return `<div class="fn-team-equipment">${equipment(weapon,'weapon')}${equipment(b.specialization,'specialization')}<div class="fn-team-gadgets">${b.gadgets.map(g=>`<span>${symbol(g)}<b>${e(g)}</b></span>`).join('')}</div></div>`;}
function sources(){
  const d=s.data,p=d.official;return `<details class="fn-disclosure fn-sources" data-disclosure="sources"><summary><span>Sources & updates<small>Where these recommendations come from</small></span><span class="fn-disclosure-chevron" aria-hidden="true">⌄</span></summary><div class="fn-disclosure-body"><p>${e(d.methodology||'Community loadout recommendations. These are not official rankings or measured win rates.')}</p><dl class="fn-source-dates"><div><dt>Build review</dt><dd>${date(d.sourceUpdatedAt)}</dd></div><div><dt>Build patch</dt><dd>${e(d.patch||'Not supplied')}</dd></div><div><dt>Last successful check</dt><dd>${date(d.fetchedAt)}</dd></div><div><dt>Official release</dt><dd>${e(p?.latest?.patch||'Unavailable')}</dd></div></dl><div class="fn-source-links"><button class="source-link" data-hub-source="${e(d.sourceUrl)}">Community loadout source ↗</button><button class="source-link" data-hub-source="https://www.reachthefinals.com/patchnotes">Official patch notes ↗</button><button class="source-link" data-route="sources">All source checks</button></div></div></details>`;
}
function empty(title,text){return `<section class="fn-empty"><span aria-hidden="true">${symbol('','weapon')}</span><h2>${title}</h2><p>${text}</p><button class="hub-button secondary" data-finals-action="refresh" ${s.loading?'disabled':''}>${s.loading?'Checking…':'Refresh builds'}</button></section>`;}
function buildDetail(b){
  if(!b)return empty('No builds for this class','The source has no ranked loadouts for this class yet. Try another class or refresh the builds.');
  return `<section class="fn-build-stage" aria-label="Selected build"><header class="fn-build-intro"><div><div class="fn-build-context"><span>${e(b.className)} build</span><span class="fn-tier-badge"><b>${e(b.tier)}</b>Community tier</span></div><h2>${e(b.name)}</h2><p>${e(b.specialization)} · ${b.gadgets.length} active gadgets</p></div><img src="assets/games/finals-${b.className.toLowerCase()}.webp" alt="" class="fn-build-contestant"></header><div class="fn-loadout-composition"><div class="fn-primary-kit"><section class="fn-weapon-stage"><div class="fn-weapon-topline"><span>Primary weapon</span><span>01</span></div><div class="fn-weapon-display"><span class="fn-weapon-symbol">${symbol(s.weapon,'weapon')}</span><h3>${e(s.weapon)}</h3></div>${b.weapons.length>1?`<label class="fn-weapon-picker"><span>Weapon option</span><select id="finals-weapon" aria-label="Primary weapon">${opts(b.weapons.map(w=>[w,w]),s.weapon)}</select></label>`:'<p class="fn-weapon-caption">The primary weapon for this build</p>'}</section>${equipment(b.specialization,'specialization')}</div><section class="fn-field-kit"><header><h3>Field kit</h3><span>3 equipped</span></header><div class="fn-gadget-grid">${b.gadgets.map((g,i)=>equipment(g,'gadget',i+1)).join('')}</div></section></div><footer class="fn-build-actions"><button class="hub-button fn-primary-button" data-finals-action="copy-build">${symbol('','copy')}<span>Copy full loadout</span></button><button class="fn-icon-button" data-finals-action="save-build" aria-label="Save loadout" title="Save loadout">${symbol('','save')}</button><button class="source-link" data-hub-source="${e(b.sourceUrl)}">Original build <span aria-hidden="true">↗</span></button></footer><details class="fn-disclosure fn-alternatives" data-disclosure="alternatives"><summary><span>Alternative equipment<small>${b.alternatives.length} reserve options</small></span><span class="fn-disclosure-chevron" aria-hidden="true">⌄</span></summary><div class="fn-disclosure-body"><div class="fn-reserve-grid">${b.alternatives.map(g=>equipment(g,'alternative')).join('')}</div><p>These are alternatives from the source. Equip one primary weapon and three active gadgets.</p></div></details></section>`;
}
function classView(){
  const choices=s.data.builds.filter(b=>b.className===s.className),b=chosen();
  return `<div class="fn-class-selector" role="group" aria-label="Contestant class">${classes.map(c=>`<button class="fn-class-choice ${c===s.className?'active':''}" data-finals-class="${c}" aria-pressed="${c===s.className}"><span class="fn-class-copy"><span class="fn-class-name">${c}<small>${classHealth[c]} HP</small></span><span class="fn-class-role">${classRoles[c]}</span></span><img src="assets/games/finals-${c.toLowerCase()}.webp" alt=""><span class="fn-class-check" aria-hidden="true">${c===s.className?'✓':'+'}</span></button>`).join('')}</div><div class="fn-loadout-workspace"><aside class="fn-build-browser"><header><div><span class="fn-kicker">${e(s.className)} class</span><h2>Build browser</h2></div><span class="fn-build-count">${choices.length}</span></header><div class="fn-build-list" aria-label="${e(s.className)} builds">${choices.map(item=>`<button data-finals-build="${e(item.id)}" aria-pressed="${item.id===s.build}" class="fn-build-option ${item.id===s.build?'active':''}"><span class="fn-build-list-tier">${e(item.tier)}</span><span class="fn-build-option-copy"><strong>${e(item.name)}</strong><span>${e(item.weapons.join(' / '))}</span><small>${e(item.specialization)}</small></span><span class="fn-build-arrow" aria-hidden="true">↗</span></button>`).join('')||'<p class="fn-browser-empty">No builds available.</p>'}</div><p class="fn-browser-note">Community recommendations<br>Ranked Cashout</p></aside>${buildDetail(b)}</div>`;
}
function currentTeam(){const presets=s.data.teamPresets?.teams||[],preset=presets.find(t=>t.id===s.team)||presets[0];if(!preset)return null;s.team=preset.id;return resolveTeam(preset,s.data.builds);}
function teamsView(){
  const team=currentTeam();if(!team)return empty('No team setups available','The class loadouts are available, but the source has not provided team recommendations yet.');
  const review=teamReview(s.data);
  return `<section class="fn-team-workspace"><div class="fn-team-selector" role="group" aria-label="Team compositions">${s.data.teamPresets.teams.map(t=>`<button class="fn-composition-choice ${t.id===s.team?'active':''}" data-finals-team="${e(t.id)}" aria-pressed="${t.id===s.team}"><span class="fn-composition-portraits">${t.players.map(p=>`<img src="assets/games/finals-${p.className.toLowerCase()}.webp" alt="${e(p.className)}">`).join('')}</span><span><strong>${e(t.comp)}</strong><small>${e(t.tag)}</small></span><i aria-hidden="true">${t.id===s.team?'✓':'↗'}</i></button>`).join('')}</div><header class="fn-team-strategy"><div><span class="fn-kicker">Team composition · Season ${e(s.data.season)}</span><h2>${e(team.name)}</h2><p>${e(team.description)}</p></div><div class="fn-team-actions"><button class="hub-button fn-primary-button" data-finals-action="copy-team" ${team.valid?'':'disabled'}>${symbol('','copy')}<span>Copy team loadouts</span></button><button class="fn-icon-button" data-finals-action="save-team" aria-label="Save team loadouts" title="Save team loadouts" ${team.valid?'':'disabled'}>${symbol('','save')}</button></div></header><div class="fn-team-player-grid">${team.players.map((p,i)=>`<article class="fn-team-player"><header class="fn-player-banner"><span class="fn-player-number">0${i+1}</span><img src="assets/games/finals-${p.className.toLowerCase()}.webp" alt=""><div><span>${e(p.className)}</span><h3>${e(p.role)}</h3></div></header><div class="fn-player-loadout">${p.valid?`${gear(p.build,p.weapon)}<p class="fn-player-task">${e(p.task)}</p><button class="source-link" data-hub-source="${e(p.build.sourceUrl)}">Loadout source ↗</button>`:'<div class="fn-inline-warning"><strong>Loadout needs review</strong><p>This build changed at the source. The team recommendation needs a new equipment check.</p></div>'}</div></article>`).join('')}</div><div class="fn-team-tradeoff"><span>Keep in mind</span><p>${e(team.tradeoff)}</p></div>${review.warning?`<div class="fn-inline-warning"><strong>Strategy review pending</strong><p>${e(review.message)}</p></div>`:''}<details class="fn-disclosure fn-team-evidence" data-disclosure="team-evidence"><summary><span>Why this composition<small>Reviewed ${date(s.data.teamPresets.reviewedAt)}</small></span><span class="fn-disclosure-chevron" aria-hidden="true">⌄</span></summary><div class="fn-disclosure-body"><p>${e(team.evidence.creator)} · <button class="source-link" data-hub-source="${e(team.evidence.url)}">${e(team.evidence.title)} ↗</button> · ${date(team.evidence.publishedAt)}</p><p>${e(team.evidence.note)}</p><p>${e(s.data.teamPresets.methodology)}</p><p>${e(review.message)}</p><button class="source-link" data-hub-source="https://thefinalsloadout.com/specializations">Current specialization guide ↗</button></div></details></section>`;
}
function savesView(){return `<section class="fn-saved-workspace"><header><h2>Saved loadouts</h2><p>Equipment snapshots stay as you saved them when the live source changes.</p></header><div class="fn-saved-grid">${s.saved.map(x=>`<article class="fn-saved-card"><span class="fn-kicker">${x.kind==='team'?'Team composition':'Class build'} · Season ${e(x.season)}</span><h3>${e(x.name)}</h3><p>Saved ${date(x.savedAt)} · Patch ${e(x.patch)}</p><details class="fn-disclosure" data-disclosure="saved-${e(x.id)}"><summary><span>Complete equipment</span><span class="fn-disclosure-chevron" aria-hidden="true">⌄</span></summary><div class="fn-disclosure-body">${x.players.map(p=>`<h4>${e(p.className)} · ${e(p.name)}</h4>${gear(p,p.weapon)}`).join('')}</div></details><div class="fn-source-links"><button class="hub-button secondary" data-finals-copy-saved="${e(x.id)}">Copy snapshot</button><button class="source-link" data-finals-delete="${e(x.id)}">Remove</button></div></article>`).join('')||'<div class="fn-empty"><h2>No saved loadouts</h2><p>Use the bookmark beside a loadout’s copy button to keep a snapshot.</p><button class="hub-button secondary" data-finals-tab="classes">Find a loadout</button></div>'}</div></section>`;}
function render(){
  if(!s.active)return;const d=s.data,previous=$('.finals-page'),scroll=previous?.scrollTop||0,listScroll=previous?.querySelector('.fn-build-list')?.scrollTop||0,focused=document.activeElement;
  const focusKey=focused&&previous?.contains(focused)?[...focused.attributes].find(a=>a.name==='id'||a.name.startsWith('data-finals-')):null,openDetails=new Set(previous?[...previous.querySelectorAll('details[open][data-disclosure]')].map(x=>x.dataset.disclosure):[]);
  clearConfirmations();
  const patchUnknown=!d?.official?.gameplay,warning=s.error||d?.freshness?.level==='warning'||patchUnknown;
  $('#hub-app').innerHTML=`<main class="hub-main finals-page"><div class="fn-loadouts-container"><header class="fn-page-intro"><div><span class="fn-kicker">THE FINALS <i></i> Ranked Cashout</span><h1>Build your loadout<span>.</span></h1></div><div class="fn-page-actions">${sourceStatus({id:'fn-build-status',label:s.loading?'Checking builds…':s.error?'Refresh unavailable':d?.freshness?.level==='warning'?'Build review pending':d&&patchUnknown?'Patch check unavailable':d?'Builds current':'Build source',tone:warning?'warning':'neutral',detail:[s.error,d?.freshness?.message,patchUnknown?'The current official balance update could not be verified.':'',d?.fetchedAt?'Last successful check: '+date(d.fetchedAt):''].filter(Boolean).join('\n')})}<button class="hub-button secondary" data-finals-action="refresh" ${s.loading?'disabled':''}><span aria-hidden="true">↻</span>${s.loading?'Checking…':'Refresh builds'}</button></div></header><div class="fn-workspace-switch" role="group" aria-label="Loadout workspace">${[['classes','My loadout'],['teams','Team setups'],...(s.saved.length||s.tab==='saved'?[['saved','Saved '+s.saved.length]]:[])].map(([id,label])=>`<button data-finals-tab="${id}" class="${s.tab===id?'active':''}" aria-pressed="${s.tab===id}">${label}</button>`).join('')}</div>${s.error?`<section class="fn-inline-warning fn-load-error" role="status"><div><strong>${d?'Couldn’t refresh the builds':'Builds aren’t available right now'}</strong><p>${d?'Your last available builds are still shown below.':'Try the build source again in a moment.'}</p><details><summary>Details</summary><p>${e(s.error)}</p></details></div><button class="hub-button secondary" data-finals-action="refresh" ${s.loading?'disabled':''}>Try again</button></section>`:''}${d?`${s.tab==='classes'?classView():s.tab==='teams'?teamsView():savesView()}${sources()}`:s.loading?'<section class="fn-empty fn-loading" role="status"><span class="fn-loading-mark" aria-hidden="true">///</span><h2>Getting your loadouts</h2><p>Checking community builds and the latest official patch.</p></section>':''}</div></main>`;
  const page=$('.finals-page');for(const detail of page.querySelectorAll('details[data-disclosure]'))if(openDetails.has(detail.dataset.disclosure))detail.open=true;
  if(focusKey){const match=[...page.querySelectorAll('button,select,input')].find(x=>x.getAttribute(focusKey.name)===focusKey.value);match?.focus({preventScroll:true});}
  page.scrollTop=scroll;const list=page.querySelector('.fn-build-list');if(list)list.scrollTop=listScroll;
}
function record(kind){const d=s.data,b=chosen(),t=kind==='team'?currentTeam():null;if(t&&!t.valid)throw new Error('This team needs a source review before it can be saved.');if(!t&&!b)throw new Error('Choose a loadout first.');return {id:crypto.randomUUID(),kind,name:t?t.comp+' · '+t.name:b.name,season:d.season,patch:d.patch,sourceUpdatedAt:d.sourceUpdatedAt,savedAt:new Date().toISOString(),players:t?t.players.map(p=>({...structuredClone(p.build),weapon:p.weapon,role:p.role})): [{...structuredClone(b),weapon:s.weapon}],strategy:t?{description:t.description,tradeoff:t.tradeoff,reviewedPatch:d.teamPresets.reviewedPatch}:null};}
function copyText(r){return `DROPZONE\nTHE FINALS · Ranked Cashout · Season ${r.season}\n${r.name}\nSource build review: ${date(r.sourceUpdatedAt)} · patch ${r.patch}\n${r.strategy?'Team recommendation: '+r.strategy.description+'\nTradeoff: '+r.strategy.tradeoff+'\n':''}\n${r.players.map((p,i)=>`PLAYER ${i+1} · ${p.className} · ${p.name}\nWeapon: ${p.weapon}\nSpecialization: ${p.specialization}\n${p.gadgets.map((g,j)=>'Gadget '+(j+1)+': '+g).join('\n')}\nSource: ${p.sourceUrl}`).join('\n\n')}`;}
async function copyFeedback(button,text){
  if(button.disabled)return;const original=button.innerHTML;button.disabled=true;
  try{await api.copy(text);if(!s.active||!button.isConnected)return;button.innerHTML='<span aria-hidden="true">✓</span><span>Copied</span>';button.classList.add('is-copied');button.setAttribute('aria-label','Loadout copied');const timer=setTimeout(()=>{confirmations.delete(button);if(!button.isConnected)return;button.innerHTML=original;button.classList.remove('is-copied');button.removeAttribute('aria-label');button.disabled=false;},1600);confirmations.set(button,timer);}
  catch(error){if(button.isConnected){button.innerHTML=original;button.disabled=false;}throw error;}
}
document.addEventListener('click',async event=>{
  const b=event.target.closest('button');if(!b||!s.active)return;
  try{
    if(b.dataset.finalsTab){if(!['classes','teams','saved'].includes(b.dataset.finalsTab))return;s.tab=b.dataset.finalsTab;render();return;}
    if(b.dataset.finalsClass){if(!classes.includes(b.dataset.finalsClass))return;s.className=b.dataset.finalsClass;ensureBuild();render();return;}
    if(b.dataset.finalsBuild){s.build=b.dataset.finalsBuild;ensureBuild();render();return;}
    if(b.dataset.finalsTeam){s.team=b.dataset.finalsTeam;render();return;}
    if(b.dataset.finalsDelete){const next=s.saved.filter(x=>x.id!==b.dataset.finalsDelete);persist('tbb-finals-saves',next);s.saved=next;render();return;}
    if(b.dataset.finalsCopySaved){const r=s.saved.find(x=>x.id===b.dataset.finalsCopySaved);if(r)await copyFeedback(b,copyText(r));return;}
    const action=b.dataset.finalsAction;if(!action)return;
    if(action==='refresh')return load(true);
    const r=record(action.endsWith('team')?'team':'build');
    if(action.startsWith('copy'))await copyFeedback(b,copyText(r));
    if(action.startsWith('save')){const next=[r,...s.saved].slice(0,40);persist('tbb-finals-saves',next);s.saved=next;render();const saveButton=$(`[data-finals-action="${action}"]`);if(saveButton){saveButton.classList.add('is-saved');saveButton.setAttribute('aria-label','Loadout saved');saveButton.title='Loadout saved';}}
  }catch(error){toast(error.message);}
});
document.addEventListener('change',event=>{if(!s.active||!s.data)return;const el=event.target;if(el.id==='finals-weapon'){s.weapon=el.value;ensureBuild();render();}});
window.addEventListener('tbb-sources-updated',()=>{if(s.active&&!s.loading)load();});
