import {$,api,e,opts,stored,persist,toast,date,dateTime} from './shared.js';
import {GzwMap} from './gzw-map.js';
import {FACTIONS,STARTER,normal,missionRegions,filterMissions,blankProfile,validateProfile,validateBackup,routeDistance,nearestLocations,gridText,validPoint,mergeMappedMissions} from './gzw-model.js';
import mapConfig from './data/gzw/map.json' with {type:'json'};
import places from './data/gzw/locations.json' with {type:'json'};
import markerBundle from './data/gzw/gzw-markers.json' with {type:'json'};
import bundled from './data/gzw/gzw-data.json' with {type:'json'};
let active=false,map=null,request=0,loading=false,data=bundled,tab='markers',selected=null,tool='pan',profiles={},imageError=false;
let faction=stored('dropzone-gzw-faction','mithras');if(!FACTIONS.some(([id])=>id===faction))faction='mithras';
const filters={query:'',vendor:'all',type:'all',region:'all',progress:'all',sort:'name',faction};
let markerData=markerBundle;
const categories=new Set(stored('dropzone-gzw-layers',[1,2,3,4,18,22,37,38,40,45,48,70]));
data={...data,tasks:mergeMappedMissions(data.tasks,markerData.objectives)};
categories.add(1);
const locations=()=>markerData.markers;
const lzs=()=>locations().filter(p=>p.type==='lz');
const objectives=t=>markerData.objectives.filter(p=>normal(p.taskName)===normal(t.name)&&(!p.faction||p.faction===faction));
const selectedPoint=()=>selected?.type==='pin'?profile().pins.find(p=>p.id===selected.id):[...locations(),...markerData.objectives].find(p=>p.id===selected?.id);
const layers={regions:false,lz:true,pins:true};let grid=true,labels=false;
const profile=()=>profiles[faction]||blankProfile();
const regions=()=>places.regions.filter(r=>!r.faction||r.faction===faction);
function readProfiles(){for(const [id]of FACTIONS){try{profiles[id]=validateProfile(stored('dropzone-gzw-'+id,blankProfile()),mapConfig);}catch{profiles[id]=blankProfile();toast('Saved map progress could not be read. Import a backup to restore it.');}}}
function saveProfile(next){try{validateProfile(next,mapConfig);persist('dropzone-gzw-'+faction,next);profiles[faction]=next;return true;}catch(err){toast(err.message);return false;}}
function updateProfile(fn){const next=structuredClone(profile());fn(next);if(saveProfile(next)){panel();detail();map?.draw();}}
function toggle(list,id){return list.includes(id)?list.filter(x=>x!==id):[...list,id];}
export function leaveGzw(){active=false;++request;map?.destroy();map=null;}
export async function mountGzw(){active=true;readProfiles();imageError=false;selected=null;shell();await refresh();}
async function refresh(force=false){const token=++request;loading=true;status();try{const results=await Promise.allSettled([api.gzw({refresh:force}),api.gzwMap({refresh:force})]);if(!active||token!==request)return;const marks=results[1];if(marks.status==='fulfilled'&&Array.isArray(marks.value.markers)){markerData=marks.value;if(map)map.map.version=markerData.mapVersion;}else markerData={...markerData,error:marks.reason?.message||marks.value?.error||'Map refresh failed'};const next=results[0].status==='fulfilled'?results[0].value:{...data,error:results[0].reason.message};if(!active||token!==request)return;if(!Array.isArray(next.tasks)||!Array.isArray(next.keys))throw new Error(next.error||'Mission data is unavailable.');data={...next,tasks:mergeMappedMissions(next.tasks,markerData.objectives)};panel();detail();map?.draw();}catch(err){if(!active||token!==request)return;data={...data,error:err.message};}if(!active||token!==request)return;loading=false;status();}
function shell(){
  $('#hub-app').innerHTML=`<main class="gz-page"><aside class="gz-sidebar"><div class="gz-sidebar-top"><span class="gz-kicker">LAMANG ISLAND</span><h1>Tactical map</h1><label class="gz-field">Faction<select id="gz-faction">${opts(FACTIONS,faction)}</select></label></div><nav class="gz-nav" aria-label="Map tools">${['markers','missions','layers','keys','pins'].map(t=>`<button data-gz-tab="${t}" aria-pressed="${tab===t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav><div class="gz-panel" id="gz-panel"></div><div class="gz-sidebar-bottom"><button data-gz-action="backup">Export progress</button><button data-gz-action="import">Import</button><button data-gz-action="help">Data & help</button></div></aside><section class="gz-map-area" aria-label="Lamang tactical map"><div class="gz-map-toolbar"><div class="gz-tools" role="group" aria-label="Map interaction">${[['pan','Pan'],['pin','Place pin'],['route','Plan route']].map(([id,label])=>`<button data-gz-tool="${id}" aria-pressed="${tool===id}">${label}</button>`).join('')}</div><div class="gz-view-tools"><button data-gz-action="zoom-out" aria-label="Zoom out">−</button><button data-gz-action="zoom-in" aria-label="Zoom in">+</button><button data-gz-action="fit">Fit map</button><button data-gz-action="starter">Starter town</button></div></div><div class="gz-canvas-wrap"><canvas id="gz-canvas" tabindex="0" aria-label="Lamang map. Drag to pan, scroll to zoom. Arrow keys move; plus and minus zoom; zero fits the map."></canvas><div class="gz-cursor" id="gz-cursor" hidden></div><div class="gz-map-hint" id="gz-map-hint"></div><div class="gz-route-summary" id="gz-route-summary" hidden></div><aside class="gz-detail" id="gz-detail" aria-label="Selection details" hidden></aside></div><div class="gz-status" id="gz-status" role="status"></div></section><input type="file" id="gz-import" accept=".json,application/json" hidden><dialog id="gz-dialog" class="gz-dialog"></dialog></main>`;
  panel();hint();status();
  map=new GzwMap($('#gz-canvas'),{map:{...mapConfig,version:markerData.mapVersion},getState:mapState,onSelect:selectMap,onPoint:addPoint,onCursor:cursor,onError:()=>{if(!imageError){imageError=true;status();}}});
}
function mapState(){const visible=filterMissions(data.tasks,filters,profile(),places.regions),counts={};for(const t of visible)for(const r of missionRegions(t,places.regions,faction))counts[r.id]=(counts[r.id]||0)+1;const task=selected?.type==='mission'?data.tasks.find(t=>t.id===selected.id):null;const selectedRegions=task?missionRegions(task,places.regions,faction).map(r=>r.id):selected?.type==='region'?[selected.id]:[];return {tool,grid,labels,layers,regions:regions(),locations:lzs(),pois:locations().filter(p=>p.type!=='lz'&&categories.has(p.category)&&(!p.faction||p.faction===faction)&&(!filters.query||tab!=='markers'||normal(p.name+' '+p.region).includes(normal(filters.query)))),objectives:task?objectives(task):categories.has(36)?markerData.objectives.filter(p=>!p.faction||p.faction===faction):[],pins:profile().pins,route:profile().route,counts,selected:selected?.id,selectedRegions};}
function cursor(value){const box=$('#gz-cursor');if(!box)return;box.hidden=!value;if(!value)return;box.textContent='Grid '+value.text;const rect=$('.gz-canvas-wrap').getBoundingClientRect();box.style.left=Math.max(6,Math.min(value.screen.x+18,rect.width-box.offsetWidth-8))+'px';box.style.top=Math.max(6,Math.min(value.screen.y+18,rect.height-box.offsetHeight-8))+'px';}
function hint(){const text={pan:'Drag to pan · Scroll to zoom · Click a marker for details',pin:'Click the map to place a pin. Drag to pan.',route:'Click to add route points · Right-drag to pan'};$('#gz-map-hint').textContent=text[tool];const route=profile().route;$('#gz-route-summary').hidden=!route.length;$('#gz-route-summary').innerHTML=`<strong>${route.length} points · ~${(routeDistance(route)/1000).toFixed(2)} km</strong><span>Straight segments; terrain is not routed.</span><button data-gz-action="undo-route" ${!route.length?'disabled':''}>Undo</button><button data-gz-action="clear-route" ${!route.length?'disabled':''}>Clear</button>`;}
function status(){if(!active)return;$('#gz-status').innerHTML=`<span>${loading?'Checking mission data…':data.error?'Offline · saved mission data':`Markers checked ${e(dateTime(markerData.fetchedAt))} · older terrain image`}</span><div><button data-gz-action="help">${imageError?'Terrain detail unavailable':markerData.error?'Map refresh failed':`${markerData.counts.markers.toLocaleString()} markers · ${markerData.counts.lz} LZs`}</button><button data-gz-action="refresh" ${loading?'disabled':''}>${loading?'Checking…':'Refresh data'}</button></div>`;}
function panel(){if(!active)return;const el=$('#gz-panel'),scroll=el.scrollTop;const focusButton=document.activeElement?.closest('[data-gz-mission],[data-gz-key],[data-gz-pin]')?.dataset;const focused=document.activeElement?.id,selection=focused==='gz-search'?[$('#gz-search').selectionStart,$('#gz-search').selectionEnd]:null;const p=profile();
  document.querySelectorAll('[data-gz-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.gzTab===tab));
  if(tab==='markers'){
    const query=normal(filters.query),list=[...locations(),...(categories.has(36)?markerData.objectives:[])].filter(p=>categories.has(p.category)&&(!p.faction||p.faction===faction)&&(!query||normal(p.name+' '+p.region+' '+(p.taskName||'')).includes(query))).sort((a,b)=>a.name.localeCompare(b.name));
    const cats=markerData.categories.filter(c=>locations().some(p=>p.category===c.id)||c.id===36);
    el.innerHTML=`<label class="gz-search"><span class="sr-only">Search map markers</span><input id="gz-search" type="search" placeholder="LZ, key, intel, location…" value="${e(filters.query)}"></label><div class="gz-marker-presets"><button data-gz-preset="essential">Essentials</button><button data-gz-preset="all">Show all</button><button data-gz-preset="none">LZs only</button></div><details class="gz-category-picker"><summary>Layers · ${categories.size} selected</summary><div class="gz-layer-list">${cats.map(c=>`<label><span>${e(c.name)} <small>${c.id===36?markerData.objectives.length:locations().filter(p=>p.category===c.id).length}</small></span><input type="checkbox" data-gz-category="${c.id}" ${categories.has(c.id)?'checked':''} ${c.id===1?'disabled':''}></label>`).join('')}</div></details><div class="gz-results-heading">${list.length.toLocaleString()} matches${list.length>200?' · first 200 listed':''}</div><div class="gz-results">${list.slice(0,200).map(m=>`<button class="gz-result" data-gz-marker="${e(m.id)}"><span class="gz-result-title"><strong>${e(m.name)}</strong>${m.type==='lz'?'<span class="gz-lz-badge">LZ</span>':''}</span><span>${e(m.taskName||cats.find(c=>c.id===m.category)?.name||'Location')}${m.region?' · '+e(m.region):''}</span><small>Grid ${gridText(m)}</small></button>`).join('')||'<p class="gz-empty">No matching markers. Enable another layer or clear the search.</p>'}</div>`;
  }else if(tab==='missions'){
    const list=filterMissions(data.tasks,filters,p,places.regions),vendors=[...new Set(data.tasks.map(t=>t.vendor))].sort(),types=[...new Set(data.tasks.flatMap(t=>t.types))].sort();
    el.innerHTML=`<div class="gz-progress"><div><strong>${data.tasks.filter(t=>p.completed.includes(t.id)).length}<span> / ${data.tasks.length}</span></strong><span>missions completed</span></div><button data-gz-action="tracked">Tracked · ${p.tracked.length}</button></div><label class="gz-search"><span class="sr-only">Search missions</span><input id="gz-search" type="search" placeholder="Search missions, vendors…" value="${e(filters.query)}"></label><div class="gz-filters"><label>Vendor<select data-gz-filter="vendor">${opts([['all','All vendors'],...vendors.map(x=>[x,x])],filters.vendor)}</select></label><label>Type<select data-gz-filter="type">${opts([['all','All missions'],...types.map(x=>[x,x])],filters.type)}</select></label><label>Region<select data-gz-filter="region">${opts([['all','All regions'],...regions().map(r=>[r.id,r.name])],filters.region)}</select></label><label>Progress<select data-gz-filter="progress">${opts([['all','All'],['remaining','Remaining'],['tracked','Tracked'],['completed','Completed']],filters.progress)}</select></label></div><div class="gz-results-heading"><label class="gz-sort"><span>${list.length} results</span><select data-gz-filter="sort" aria-label="Sort missions">${opts([['name','Name'],['vendor','Vendor']],filters.sort)}</select></label><button data-gz-action="reset-filters">Reset filters</button></div><div class="gz-results">${list.map(t=>`<button class="gz-result ${selected?.id===t.id?'selected':''}" data-gz-mission="${e(t.id)}"><span class="gz-result-title"><strong>${e(t.name)}</strong><span aria-label="${p.completed.includes(t.id)?'Completed':p.tracked.includes(t.id)?'Tracked':''}">${p.completed.includes(t.id)?'✓':p.tracked.includes(t.id)?'★':''}</span></span><span>${e(t.vendor)} · ${e(t.types[0])}</span><small>${e(t.location||'Location not supplied')}</small></button>`).join('')||'<div class="gz-empty">No missions match these filters.</div>'}</div>`;
  }else if(tab==='keys'){
    const list=data.keys.filter(k=>normal(k.name+' '+k.usage).includes(normal(filters.query)));
    el.innerHTML=`<div class="gz-progress"><div><strong>${data.keys.filter(k=>p.foundKeys.includes(k.id)).length}<span> / ${data.keys.length}</span></strong><span>keys collected</span></div></div><label class="gz-search"><span class="sr-only">Search keys</span><input id="gz-search" type="search" placeholder="Search keys or door locations…" value="${e(filters.query)}"></label><div class="gz-results-heading">${list.length} keys and keycards</div><div class="gz-results">${list.map(k=>`<button class="gz-result ${selected?.id===k.id?'selected':''}" data-gz-key="${e(k.id)}"><span class="gz-result-title"><strong>${e(k.name)}</strong><span>${p.foundKeys.includes(k.id)?'✓':''}</span></span><small>${e(k.usage||'Door details not supplied')}</small></button>`).join('')||'<div class="gz-empty">No keys match your search.</div>'}</div>`;
  }else if(tab==='layers'){
    el.innerHTML=`<div class="gz-section-label">Map layers</div><div class="gz-layer-list">${[['regions','Region names'],['lz','Landing zones · always labeled'],['pins','My pins']].map(([id,label])=>`<label><span>${label}</span><input type="checkbox" data-gz-layer="${id}" ${layers[id]?'checked':''} ${id==='lz'?'disabled':''}></label>`).join('')}<label><span>Coordinate grid</span><input type="checkbox" data-gz-toggle="grid" ${grid?'checked':''}></label><label><span>Pin labels</span><input type="checkbox" data-gz-toggle="labels" ${labels?'checked':''}></label></div><div class="gz-section-label">Jump to a region</div><div class="gz-region-list">${regions().map(r=>`<button data-gz-region="${r.id}">${e(r.name)}<span>↗</span></button>`).join('')}</div><p class="gz-small">Region centers are approximate. All ${markerData.counts.lz} approved landing zones from GZW Tac Map are included. Use Markers to choose loot, keys, intel, caches and other layers.</p>`;
  }else{
    el.innerHTML=`<div class="gz-results-heading"><span>${p.pins.length} saved pins</span><button data-gz-tool="pin">Place pin</button></div><form id="gz-coordinate-form" class="gz-coordinate-form"><label>Go to grid<input name="coordinates" placeholder="171.50, 144.25" required></label><button type="submit">Go</button></form><div class="gz-results">${p.pins.map(pin=>`<button class="gz-result" data-gz-pin="${e(pin.id)}"><strong>${e(pin.name)}</strong><span>${gridText(pin)}</span>${pin.note?`<small>${e(pin.note)}</small>`:''}</button>`).join('')||'<div class="gz-empty">Choose Place pin, then click the map. Pins and notes stay on this PC.</div>'}</div>`;
  }
  el.scrollTop=scroll;if(selection){const input=$('#gz-search');input?.focus({preventScroll:true});try{input?.setSelectionRange(...selection);}catch{}}else if(focusButton){const button=[...el.querySelectorAll('button')].find(b=>['gzMission','gzKey','gzPin'].some(k=>focusButton[k]&&b.dataset[k]===focusButton[k]));button?.focus({preventScroll:true});}
}
function closeDetail(){selected=null;$('#gz-detail').hidden=true;map?.draw();panel();}
function detail(){if(!active)return;const box=$('#gz-detail');box.hidden=!selected;if(!selected)return;let content='';
  if(selected.type==='mission'){
    const t=data.tasks.find(t=>t.id===selected.id);if(!t){closeDetail();return;}const exact=objectives(t),area=missionRegions(t,places.regions,faction),alternative=data.tasks.find(x=>normal(x.name)===normal(t.alternate)),p=profile();
    content=`<span class="gz-kicker">${e(t.types.join(' · '))}</span><h2>${e(t.name)}</h2><dl class="gz-facts"><div><dt>Vendor</dt><dd>${e(t.vendor)}</dd></div><div><dt>Region</dt><dd>${e(area.length?area.map(r=>r.name).join(', '):t.location||'Not supplied')}</dd></div></dl><div class="gz-detail-actions"><button class="gz-primary" data-gz-action="track">${p.tracked.includes(t.id)?'Untrack mission':'Track mission'}</button><button data-gz-action="complete">${p.completed.includes(t.id)?'✓ Completed — undo':'Mark complete'}</button></div>${exact.length?`<div class="gz-section-label">${exact.length} mapped objectives</div>${exact.map(m=>`<button class="gz-result" data-gz-marker="${m.id}"><strong>${e(m.name)}</strong><span>Step ${e(m.step??'—')} · Grid ${gridText(m)}</span></button>`).join('')}`:''}<div class="gz-location-note"><strong>${exact.length?'Mapped objectives':area.length?'Region only':'No map location'}</strong><p>${exact.length?'Objective pins come from GZW Tac Map. Open the source for full instructions.':area.length?'Only the mission region is available for this entry.':'This source does not supply a usable location for this mission.'}</p></div>${exact.length||area.length?`<button class="gz-wide" data-gz-action="focus-mission">${exact.length?'Show objectives':'Show region'+(area.length>1?'s':'')} on map</button>`:''}${t.alternate?`<div class="gz-section-label">Alternative mission</div>${alternative?`<button class="gz-wide" data-gz-mission="${e(alternative.id)}">${e(t.alternate)}</button>`:`<p>${e(t.alternate)}</p>`}<p class="gz-small">Check the guide before choosing a branch.</p>`:''}<button class="gz-wide" data-hub-source="${e(t.sourceUrl)}">Open mission guide ↗</button><p class="gz-small">Progress is tracked locally. It is not synced with the game.</p>`;
  }else if(selected.type==='key'){
    const k=data.keys.find(k=>k.id===selected.id);if(!k){closeDetail();return;}content=`<span class="gz-kicker">${e(k.type)}</span><h2>${e(k.name)}</h2><p>${e(k.usage||'Door details are not supplied by this source.')}</p><button class="gz-primary gz-wide" data-gz-action="found-key">${profile().foundKeys.includes(k.id)?'✓ Collected — undo':'Mark collected'}</button><p class="gz-small">An unlock description is not a verified key spawn.</p><button class="gz-wide" data-hub-source="${e(k.sourceUrl)}">Open key guide ↗</button>`;
  }else if(selected.type==='region'){
    const r=places.regions.find(r=>r.id===selected.id);const count=data.tasks.filter(t=>missionRegions(t,places.regions,faction).some(x=>x.id===r.id)).length;content=`<span class="gz-kicker">REGION</span><h2>${e(r.name)}</h2><p>${count} indexed missions mention this region.</p><button class="gz-primary gz-wide" data-gz-action="region-missions">Show missions</button><p class="gz-small">This marker identifies the general region, not a specific objective.</p><button class="gz-wide" data-hub-source="${e(r.sourceUrl)}">Region guide ↗</button>`;
  }else{
    const item=selectedPoint();if(!item){closeDetail();return;}const near=nearestLocations(item,lzs().filter(l=>l.id!==item.id));content=`<span class="gz-kicker">${selected.type==='pin'?'MY PIN':markerData.categories.find(c=>c.id===item.category)?.name||'MAP LOCATION'}</span><h2>${e(item.name)}</h2><p class="gz-grid-value">${gridText(item)}</p>${item.note?`<p>${e(item.note)}</p>`:''}<div class="gz-detail-actions"><button data-gz-action="copy-position">Copy grid</button><button data-gz-action="route-selection">Add to route</button></div>${selected.type==='pin'?'<button class="gz-wide" data-gz-action="edit-pin">Edit pin</button><button class="gz-wide gz-danger" data-gz-action="delete-pin">Delete pin</button>':`<p class="gz-small">GZW Tac Map · source revision ${e(markerData.mapVersion)}${item.region?' · '+e(item.region):''}${item.tier?' · Tier '+e(item.tier):''}${item.level!==null?' · Level '+e(item.level):''}${item.locked?' · Locked':''}. Spawn markers indicate possible locations; loot is not guaranteed.</p><button class="gz-wide" data-hub-source="${e(item.sourceUrl)}">Source ↗</button>`}<div class="gz-section-label">Nearby known landing zones</div>${near.map(l=>`<button class="gz-nearby" data-gz-lz="${l.id}"><span>${e(l.name)}</span><span>~${Math.round(l.distance)} m</span></button>`).join('')}<p class="gz-small">Distances are straight-line estimates.</p>`;
  }
  box.innerHTML=`<button class="gz-close" data-gz-action="close-detail" aria-label="Close details">×</button>${content}`;
}
function focus(points){map?.focus(points,selected?($('#gz-detail')?.offsetWidth||0)+24:0);}
function selectMap(item){if(item.type==='cluster'){map.focus(item.points);return;}selected={id:item.id,type:item.type};detail();map?.draw();}
function selectMission(id){selected={id,type:'mission'};detail();panel();const t=data.tasks.find(t=>t.id===id);focus(objectives(t).length?objectives(t):missionRegions(t,places.regions,faction));map.draw();}
function selectPoint(id,type){const item=(type==='pin'?profile().pins:[...locations(),...markerData.objectives]).find(x=>x.id===id);if(!item)return;selected={id,type};detail();focus([item]);}
function setTool(next){tool=next;document.querySelectorAll('[data-gz-tool]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.gzTool===tool));hint();}
function addPoint(point,type){if(type==='pin'){editPin({id:crypto.randomUUID(),...point,name:'',note:'',color:'green'},true);}else{if(profile().route.length>=100)return toast('Routes support up to 100 points.');updateProfile(p=>p.route.push(point));hint();}}
function showDialog(html){const d=$('#gz-dialog');d.innerHTML=`<button class="gz-close" data-gz-action="close-dialog" aria-label="Close">×</button>${html}`;if(!d.open)d.showModal();}
function editPin(pin,isNew=false){if(isNew&&profile().pins.length>=150)return toast('You can save up to 150 pins per faction.');showDialog(`<h2>${isNew?'Place pin':'Edit pin'}</h2><p class="gz-small">Grid ${gridText(pin)}</p><form id="gz-pin-form"><input name="id" type="hidden" value="${e(pin.id)}"><input name="x" type="hidden" value="${pin.x}"><input name="y" type="hidden" value="${pin.y}"><label>Name<input name="name" required maxlength="80" value="${e(pin.name)}" placeholder="Rally point, stash, objective…"></label><label>Note<textarea name="note" maxlength="500" rows="4" placeholder="Add a note…">${e(pin.note)}</textarea></label><label>Color<select name="color">${opts([['green','Green'],['amber','Amber'],['red','Red'],['blue','Blue']],pin.color)}</select></label><button class="gz-primary" type="submit">Save pin</button></form>`);$('#gz-pin-form [name=name]').focus();}
function help(){showDialog(`<span class="gz-kicker">GRAY ZONE WARFARE</span><h2>Data & map controls</h2><dl class="gz-facts"><div><dt>Missions & contracts</dt><dd>${data.tasks.length}</dd></div><div><dt>Keys & keycards</dt><dd>${data.keys.length}</dd></div><div><dt>Source data date</dt><dd>${date(data.sourceUpdatedAt)}</dd></div><div><dt>Last successful fetch</dt><dd>${e(dateTime(data.fetchedAt))}</dd></div></dl>${data.error?`<p class="gz-location-note">Refresh failed: ${e(data.error)}</p>`:''}<p>The mission index checks on every app launch and every 15 minutes. Offline, the last saved index remains available. New source entries arrive without rebuilding Dropzone.</p><p>The API supplies mission names, vendors, categories and regions. Exact objective markers are supplied separately by GZW Tac Map where available. Full instructions remain on the linked guides. The guide button opens the community wiki.</p><p>${e(mapConfig.calibration)} ${markerData.counts.markers} approved markers and ${markerData.counts.objectives} objective entries refresh on launch and every 15 minutes. The terrain is an older, approximately calibrated image. GZW Tac Map’s tile server refused the image download; new marker coordinates are source-supplied, but the background may differ from the current game. The source provides no last-edit date; the check time records when data was fetched, not when it changed.</p>${markerData.error?`<p class="gz-location-note">Map refresh failed: ${e(markerData.error)}. Showing the saved snapshot.</p>`:``}<p>Drag to pan; scroll to zoom at the pointer. On the focused map, arrow keys pan, + / − zoom and 0 fits the map. Plan route draws straight segments, not a path around terrain.</p><p>Each faction keeps separate completed missions, tracked missions, collected keys, routes and pins on this PC. Export progress makes a backup; Import merges it into the matching faction.</p><div class="gz-help-links"><button data-hub-source="https://gzw-data.dev/">Mission data ↗</button><button data-hub-source="https://github.com/ZedimAits/GZW_map">Map image source ↗</button><button data-hub-source="https://gzwtacmap.com/">Reference map ↗</button></div><p class="gz-small">GZW Data API by ZoniBoy00 (MIT); wiki content from Gray Zone Warfare Wiki contributors (CC BY-SA). Map markers supplied by GZW Tac Map, used with permission confirmed by the app owner. Terrain image: ZedimAits/GZW_map. Game imagery © MADFINGER Games. Independent fan companion.</p>`);}
async function action(name){
  if(name==='refresh')return refresh(true);if(name==='help')return help();if(name==='close-dialog')return $('#gz-dialog').close();if(name==='close-detail')return closeDetail();if(name==='fit')return map.fit();if(name==='zoom-in')return map.zoom(1.4);if(name==='zoom-out')return map.zoom(1/1.4);if(name==='starter')return focus(regions().filter(r=>r.id===STARTER[faction]));
  if(name==='reset-filters'){Object.assign(filters,{query:'',vendor:'all',type:'all',region:'all',progress:'all',sort:'name'});panel();map.draw();return;}
  if(name==='tracked'){filters.progress=filters.progress==='tracked'?'all':'tracked';panel();map.draw();return;}
  if(name==='track'){const id=selected.id;updateProfile(p=>{p.tracked=toggle(p.tracked,id);if(p.tracked.includes(id))p.completed=p.completed.filter(x=>x!==id);});return;}
  if(name==='complete'){const id=selected.id;updateProfile(p=>{p.completed=toggle(p.completed,id);if(p.completed.includes(id))p.tracked=p.tracked.filter(x=>x!==id);});return;}
  if(name==='found-key'){updateProfile(p=>{p.foundKeys=toggle(p.foundKeys,selected.id);});return;}
  if(name==='focus-mission'){const t=data.tasks.find(t=>t.id===selected.id);return focus(objectives(t).length?objectives(t):missionRegions(t,places.regions,faction));}
  if(name==='region-missions'){tab='missions';Object.assign(filters,{query:'',vendor:'all',type:'all',progress:'all',region:selected.id});closeDetail();panel();return;}
  if(name==='undo-route'||name==='clear-route'){updateProfile(p=>{if(name==='undo-route')p.route.pop();else p.route=[];});hint();return;}
  if(name==='backup'){const backup={schema:1,game:'gzw',faction,mapRevision:mapConfig.sha256,exportedAt:new Date().toISOString(),profile:profile()};await api.exportFile('Dropzone-GZW-'+faction+'.json',backup);return;}
  if(name==='import')return $('#gz-import').click();
  const item=selectedPoint();
  if(name==='copy-position'&&item){await api.copy(gridText(item));toast('Grid copied.');return;}
  if(name==='route-selection'&&item){addPoint({x:item.x,y:item.y},'route');return;}
  if(name==='edit-pin'&&item)return editPin(item);
  if(name==='delete-pin'&&item){const id=item.id;closeDetail();updateProfile(p=>{p.pins=p.pins.filter(x=>x.id!==id);});}
}
document.addEventListener('click',event=>{if(!active)return;const b=event.target.closest('button');if(!b)return;const d=b.dataset;
  if(d.gzPreset){categories.clear();const ids=d.gzPreset==='all'?markerData.categories.map(c=>c.id):d.gzPreset==='essential'?[1,2,3,4,18,22,37,38,40,45,48,70]:[1];ids.forEach(id=>categories.add(id));persist('dropzone-gzw-layers',[...categories]);panel();map.draw();return;}
  if(d.gzMarker)return selectPoint(d.gzMarker,'poi');
  if(d.gzTab){tab=d.gzTab;filters.query='';panel();return;}
  if(d.gzTool)return setTool(d.gzTool);
  if(d.gzMission)return selectMission(d.gzMission);
  if(d.gzKey){selected={id:d.gzKey,type:'key'};detail();panel();return;}
  if(d.gzRegion){const r=places.regions.find(r=>r.id===d.gzRegion);selectMap({...r,type:'region'});focus([r]);return;}
  if(d.gzPin)return selectPoint(d.gzPin,'pin');if(d.gzLz)return selectPoint(d.gzLz,'lz');
  if(d.gzAction)action(d.gzAction).catch(err=>toast(err.message));
});
document.addEventListener('input',event=>{if(active&&event.target.id==='gz-search'){filters.query=event.target.value;panel();map.draw();}});
document.addEventListener('change',async event=>{if(!active)return;const t=event.target;
  if(t.id==='gz-faction'){if(!FACTIONS.some(([id])=>id===t.value))return;faction=t.value;filters.faction=faction;filters.region='all';try{persist('dropzone-gzw-faction',faction);}catch{toast('Faction selection could not be saved.');}closeDetail();panel();hint();map.draw();return;}
  if(t.dataset.gzCategory){const id=Number(t.dataset.gzCategory);if(t.checked)categories.add(id);else categories.delete(id);categories.add(1);persist('dropzone-gzw-layers',[...categories]);panel();map.draw();return;}
  if(t.dataset.gzFilter){filters[t.dataset.gzFilter]=t.value;panel();map.draw();return;}
  if(t.dataset.gzLayer){layers[t.dataset.gzLayer]=t.checked;map.draw();return;}
  if(t.dataset.gzToggle){if(t.dataset.gzToggle==='grid')grid=t.checked;else labels=t.checked;map.draw();return;}
  if(t.id==='gz-import'){
    const pageRoot=$('.gz-page'),file=t.files?.[0];t.value='';if(!file)return;
    try{if(file.size>200000)throw new Error('Choose a backup smaller than 200 KB.');const imported=validateBackup(JSON.parse(await file.text()),mapConfig);if(!active||pageRoot!==$('.gz-page'))return;const existing=profiles[imported.faction]||blankProfile(),next={...existing,completed:[...new Set([...existing.completed,...imported.profile.completed])],tracked:[...new Set([...existing.tracked,...imported.profile.tracked])],foundKeys:[...new Set([...existing.foundKeys,...imported.profile.foundKeys])],pins:[...existing.pins,...imported.profile.pins.filter(p=>!existing.pins.some(x=>x.id===p.id))],route:existing.route.length?existing.route:imported.profile.route};next.tracked=next.tracked.filter(id=>!next.completed.includes(id));validateProfile(next,mapConfig);persist('dropzone-gzw-'+imported.faction,next);profiles[imported.faction]=next;panel();detail();hint();map.draw();toast('Progress imported for '+FACTIONS.find(([id])=>id===imported.faction)[1]+'.');}catch(err){toast(err.message);}
  }
});
document.addEventListener('submit',event=>{if(!active)return;const form=event.target;
  if(form.id==='gz-pin-form'){event.preventDefault();const v=Object.fromEntries(new FormData(form)),pin={id:v.id,x:Number(v.x),y:Number(v.y),name:v.name.trim(),note:v.note.trim(),color:v.color};const p=structuredClone(profile());p.pins=[...p.pins.filter(x=>x.id!==pin.id),pin];if(saveProfile(p)){$('#gz-dialog').close();selected={id:pin.id,type:'pin'};setTool('pan');panel();detail();map.draw();}}
  if(form.id==='gz-coordinate-form'){event.preventDefault();const value=new FormData(form).get('coordinates');const parts=String(value).trim().split(/[,/\s]+/).map(Number);const point={x:parts[0],y:parts[1]};if(parts.length!==2||!validPoint(point,mapConfig))return toast('Enter two grid coordinates inside the map, for example 171.50, 144.25.');focus([point]);}
});
window.addEventListener('tbb-sources-updated',()=>{if(active&&!loading)refresh();});
