import {$,api,e,stored,persist,toast} from './shared.js';
let revision=0;
const list=key=>{const value=stored(key,[]);return Array.isArray(value)?value:[];};
const check=input=>api.personalIntel?api.personalIntel(input):fetch('/api/personal-intel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}).then(r=>r.json());
let checking=false;
export function startPersonalAlerts(){
 const run=async()=>{if(checking||stored('dropzone-intel-enabled',true)===false)return;checking=true;
 try{const prefs=stored('dropzone-intel-preferences',{}),results=stored('dropzone-intel-results',{});for(const game of ['wardogs','bo7','warzone','lol','finals','siege']){
 const names=[...savedNames(game),...(prefs.game===game?String(prefs.extra||'').split('\n').filter(Boolean):[])];if(!names.length)continue;
 try{const result=await check({game,names});if(result.error)continue;const old=results[game],fresh=result.article?.url+'|'+result.article?.publishedAt;
 results[game]=result;persist('dropzone-intel-results',results);
 if(result.names?.length&&(!old||fresh!==old.article?.url+'|'+old.article?.publishedAt)){toast('Patch watch: '+result.names.slice(0,3).join(', ')+' mentioned in '+game.toUpperCase()+'. Open My patch alerts in Tools.');const b=$('#workspace-open');if(b){b.dataset.alert='true';b.title='New patch mentions — open My patch alerts';}}
 }catch{/* Retain the last check; the page provides a manual retry. */}
 }}finally{checking=false;}};
 setTimeout(run,7000);setInterval(run,15*60_000);window.addEventListener('tbb-sources-updated',()=>{if(Date.now()-(startPersonalAlerts.last||0)>14*60_000){startPersonalAlerts.last=Date.now();run();}});
}
export function leaveIntel(){revision++;}
function savedNames(game){const found=[];if(['bo7','warzone'].includes(game))for(const s of list('tbb-saved-loadouts'))if(s.game===game)found.push(s.build?.weapon,...(s.build?.attachments||[]).map(a=>a.name));if(game==='lol')for(const s of list('rf-saved'))found.push(s.champion);if(game==='finals')for(const s of list('tbb-finals-saves'))for(const p of s.players||[])found.push(p.weapon,...(p.gadgets||[]));if(game==='wardogs')for(const s of list('dropzone-wardogs-plans'))found.push(s.weaponName);return [...new Set(found.filter(x=>typeof x==='string'))];}
export function mountIntel(){
 const b=document.querySelector("#workspace-open");if(b)delete b.dataset.alert;
 const token=++revision,preferences=stored('dropzone-intel-preferences',{game:'wardogs',extra:''});
 $('#hub-app').innerHTML=`<main class="hub-main intel-page"><div class="library-intro"><div><span class="hub-eyebrow">YOUR GEAR / PATCH WATCH</span><h1>What matters to your next match.</h1><p>Find your saved weapons and equipment in the latest publisher patch notes.</p></div></div><div class="intel-controls"><label>Game<select id="intel-game">${[['wardogs','WARDOGS'],['bo7','Black Ops 7'],['warzone','Warzone'],['lol','League'],['finals','THE FINALS'],['siege','Rainbow Six Siege']].map(([id,n])=>`<option value="${id}" ${id===preferences.game?'selected':''}>${n}</option>`).join('')}</select></label><label>Also track <small>One weapon, champion or item per line</small><textarea id="intel-extra" rows="3" maxlength="4000">${e(preferences.extra||'')}</textarea></label><button id="intel-check" class="hub-button">Check my gear</button></div><label class="squad-share"><input id="intel-enabled" type="checkbox" ${stored('dropzone-intel-enabled',true)!==false?'checked':''}> Check my saved gear every 15 minutes while Dropzone is open</label><div id="intel-results" aria-live="polite"></div><p class="intel-note">Mentions can include fixes, buffs, nerfs or unrelated context. Dropzone links the original notes and does not infer a balance change from a name alone.</p></main>`;
 const results=stored('dropzone-intel-results',{});const show=result=>{if(token!==revision)return;$('#intel-results').innerHTML=result?`<section class="intel-card"><span class="hub-eyebrow">${e(result.game.toUpperCase())} · ${result.checkedAt?e(new Date(result.checkedAt).toLocaleString()):'Not checked'}</span><h2>${e(result.article?.title||'No patch post')}</h2><p>${e(result.message)}</p>${result.names.length?`<div class="intel-chips">${result.names.map(n=>`<span>${e(n)}</span>`).join('')}</div>`:'<p>No tracked names found in the available page. This does not prove that your gear is unchanged.</p>'}${result.article?`<button class="hub-button secondary" data-hub-source="${e(result.article.url)}">Read publisher notes ↗</button>`:''}</section>`:'<p>Add tracked gear or save a loadout, then check the latest notes.</p>';};
 $('#intel-enabled').onchange=ev=>persist('dropzone-intel-enabled',ev.target.checked);show(results[preferences.game]);$('#intel-game').onchange=()=>show(results[$('#intel-game').value]);
 $('#intel-check').onclick=async()=>{const game=$('#intel-game').value,extra=$('#intel-extra').value,names=[...savedNames(game),...extra.split('\n').map(n=>n.trim()).filter(Boolean)];persist('dropzone-intel-preferences',{game,extra});if(!names.length){toast('Save a loadout or enter at least one item to track.');return;}const button=$('#intel-check');button.disabled=true;$('#intel-results').textContent='Checking the publisher’s latest patch page…';try{const result=api.personalIntel?await api.personalIntel({game,names}):await fetch('/api/personal-intel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game,names})}).then(r=>r.json());if(result.error)throw Error(result.error);if(token!==revision)return;results[game]=result;persist('dropzone-intel-results',results);show(result);}catch(err){if(token===revision)$('#intel-results').textContent='Could not check the publisher: '+err.message;}finally{if(token===revision)button.disabled=false;}};
}
