import {$,e,api,stored,persist,toast} from './shared.js';
import {SENS_GAMES,convertSensitivity} from './sensitivity-engine.js';
import {syncSelects} from './controls.js';
const initial=()=>({source:{game:'cs2',kind:'preset',dpi:800,sens:1,cm:'',yaw:''},target:{game:'valorant',kind:'preset',dpi:800,sens:1,cm:'',yaw:''}});
let state,result;
const field=(side,key,label,value)=>`<label>${label}<input data-side="${side}" data-field="${key}" type="number" min="0" step="any" value="${e(value??'')}"></label>`;
function panel(side,title){const s=state[side],g=SENS_GAMES.find(g=>g.id===s.game);return `<section class="sens-panel"><span class="hub-eyebrow">${side==='source'?'01 / FROM':'02 / TO'}</span><h2>${title}</h2><label>Game<select id="sens-${side}-game" data-searchable="true" data-side="${side}" data-field="game">${SENS_GAMES.map(g=>`<option value="${g.id}" ${g.id===s.game?'selected':''}>${g.name}</option>`).join('')}</select></label><label>Conversion data<select id="sens-${side}-kind" data-side="${side}" data-field="kind"><option value="preset" ${s.kind==='preset'?'selected':''}>Game preset · hipfire</option><option value="measured" ${s.kind==='measured'?'selected':''}>Manual · measured cm/360</option><option value="custom" ${s.kind==='custom'?'selected':''}>Manual · custom coefficient</option></select></label><div class="sens-fields">${field(side,'dpi',side==='source'?'Source DPI':'Destination DPI',s.dpi)}${side==='source'||s.kind==='measured'?field(side,'sens',s.kind==='measured'?'Sensitivity used to measure':(s.game==='fortnite'?'X-axis sensitivity (%)':'In-game sensitivity'),s.sens):''}${s.kind==='measured'?field(side,'cm','Measured cm / 360°',s.cm):''}${s.kind==='custom'?field(side,'yaw','Degrees / count / sensitivity',s.yaw):''}</div>${!g?.yaw?`<p>${e(g?.note||'No verified preset.')}</p>`:''}${s.kind==='measured'?'<p>At the DPI and sensitivity above, measure how far the mouse moves for one complete horizontal turn. Use hipfire with acceleration off. The game must scale sensitivity linearly.</p>':s.kind==='custom'?'<p>Use a verified horizontal rotation coefficient. For a nonlinear sensitivity scale, this conversion is not supported.</p>':`<p>${e(g?.note||'Use default unscoped input with acceleration off.')}</p>`}</section>`;}
function save(){try{persist('dropzone-sensitivity-v1',state);}catch{}}
function update(){result=null;try{result=convertSensitivity(state.source,state.target);$('#sens-result').innerHTML=`<span>DESTINATION SENSITIVITY</span><strong>${Number(result.sensitivity.toPrecision(8))}</strong><p>${result.cm360.toFixed(2)} cm for a full 360° turn</p><small>${state.source.kind==='preset'&&state.target.kind==='preset'?'Preset conversion':'Based on your manual calibration'} · round to the precision your game accepts.</small>`;}catch(err){$('#sens-result').innerHTML=`<span>COMPLETE YOUR SETUP</span><p>${e(err.message)}</p>`;}$('#sens-copy').disabled=!result;$('#sens-swap').disabled=!result;save();}
function render(){
 $('#hub-app').innerHTML=`<main class="hub-main sensitivity-page"><header><span class="hub-eyebrow">MOUSE SETUP</span><h1>Sensitivity converter</h1><p>Keep the same physical mouse movement when you switch games.</p></header><div class="sens-panels">${panel('source','Your current setup')}${panel('target','Your next setup')}</div><section class="sens-output"><div id="sens-result" role="status" aria-live="polite"></div><div class="sens-actions"><button id="sens-copy" class="hub-button">Copy sensitivity</button><button id="sens-swap" class="hub-button secondary">Swap games</button></div></section><details class="sens-help"><summary>How to measure, supported settings & sources</summary><p>Pick a landmark, move the mouse horizontally until you face it again, and measure the distance traveled by the mouse sensor. Repeat slowly to check the result. Enter that distance, the sensitivity used, and your DPI in manual mode. Do this in the destination game too if it has no verified preset.</p><p>This matches horizontal cm/360, not perceived speed or screen distance. Resolution and aspect ratio do not change raw physical rotation. Some games couple FOV to rotation: use the profile’s stated defaults or measure at your actual FOV. ADS, scopes, acceleration and unverified nonlinear sliders are not covered by manual calibration. Mouse DPI tolerances can require a final measured adjustment.</p><p>For linear games: cm/360 = 914.4 ÷ (DPI × sensitivity × coefficient). Nonlinear presets use their published rotation formula and inverse; they are not treated as a simple coefficient. Manual calibration assumes a linear scale.</p><p>${SENS_GAMES.filter(g=>g.yaw).length} published game presets, plus clearly marked manual profiles. Presets include linear, offset and nonlinear scales. Game-specific notes appear in each setup. References checked September 14, 2026; these are published reference profiles, not in-game tests by Dropzone. Calculations run locally. No in-game automation or input injection.</p><button class="source-link" data-sens-source="https://aimlabs.com/mouse-sensitivity-converter">Aimlabs profile reference ↗</button><button class="source-link" data-sens-source="https://sensconverter.app/cs2-to-valorant-sensitivity-converter/">CS2 / VALORANT conversion reference ↗</button><button class="source-link" data-sens-source="https://github.com/ValveSoftware/source-sdk-2013/blob/master/src/game/client/in_mouse.cpp">Valve input implementation ↗</button></details></main>`;
 document.querySelectorAll('[data-side]').forEach(input=>{const change=()=>{const {side,field}=input.dataset;state[side][field]=input.value;if(field==='game'){state[side].kind=SENS_GAMES.find(g=>g.id===input.value)?.yaw?'preset':'measured';}if(field==='game'||field==='kind'){save();render();}else update();};input.addEventListener(input.tagName==='SELECT'?'change':'input',change);});
 $('#sens-copy').onclick=async()=>{if(!result)return;try{await api.copy(String(Number(result.sensitivity.toPrecision(8))));toast('Sensitivity copied.');}catch{toast('Could not copy. Select the displayed sensitivity to copy it.');}};
 $('#sens-swap').onclick=()=>{if(!result)return;const source={...state.target,sens:result.sensitivity};if(source.kind==='measured')source.cm=result.cm360;state={source,target:{...state.source}};save();render();};
 document.querySelectorAll('[data-sens-source]').forEach(b=>b.onclick=()=>api.openSource(b.dataset.sensSource));update();syncSelects();
}
export function mountSensitivity(){const saved=stored('dropzone-sensitivity-v1',null),base=initial();state={source:{...base.source,...saved?.source},target:{...base.target,...saved?.target}};for(const s of Object.values(state)){if(!SENS_GAMES.some(g=>g.id===s.game))s.game='custom';if(!['preset','measured','custom'].includes(s.kind))s.kind='measured';}render();}
