import {sourceStatus} from './source-status.js';
import {$,api,e,opts,stored,persist,date,dateTime} from './shared.js';
import abilities from './data/siege/operator-abilities.json' with {type:'json'};
import operatorAssets from './data/siege/operator-assets.json' with {type:'json'};
import bundle from './data/siege/siege-data.json' with {type:'json'};
import guideBundle from './data/siege/siege-guides.json' with {type:'json'};
let active=false,request=0,loading=false,data={...bundle,guides:guideBundle},tab='maps',side='attack',platform=stored('dropzone-siege-platform','pc'),mapId='clubhouse';
if(!['pc','console'].includes(platform))platform='pc';
const op=id=>data.operators.find(o=>o.id===id);
const roleName=s=>({'anti-gadget':'Anti-gadget','anti-entry':'Entry denial','intel-gatherer':'Intel','intel-denier':'Intel denial','crowd-control':'Crowd control','front-line':'Front line','back-line':'Support'}[s]||s.replaceAll('-',' ').replace(/^./,s=>s.toUpperCase()));
const image=o=>`<img src="${e(operatorAssets[o.icon]||'assets/siege/'+o.id+'.png')}" data-r6-fallback="${e(o.icon)}" width="54" height="54" alt="">`;
export function leaveSiege(){active=false;++request;}
export async function mountSiege(){active=true;render();await refresh();}
async function refresh(force=false){const token=++request;loading=true;render();try{const d=await api.siege({refresh:force});if(!active||token!==request)return;if(!d.operators?.length||!d.guides)throw new Error(d.error||'Siege data is unavailable.');data=d;if(!data.maps.some(m=>m.id===mapId))mapId=data.maps[0]?.id;}catch(err){if(!active||token!==request)return;data={...data,error:err.message};}if(!active||token!==request)return;loading=false;render();}
function card(pick,index){const o=op(pick.id);if(!o||o.side!==side)return '';const artwork=operatorAssets[o.image]||o.image;return `<button class="r6-team-member" data-open-operator="${e(o.id)}" aria-label="${e(o.name)} — open operator details"><span class="r6-team-art"><img src="${e(artwork)}" data-r6-fallback="${e(o.image)}" alt="" loading="lazy"></span><span class="r6-team-copy"><span class="r6-team-name">${e(o.name)}<span aria-hidden="true">↗</span></span><span class="r6-team-role">${e(o.roles.map(roleName).join(' · '))}</span>${abilities[o.id]?`<span class="r6-team-gadget">${e(abilities[o.id].name)}</span>`:''}<span class="r6-team-reason">${e(pick.reason)}</span></span></button>`;}
function roundPlan(g,m){const picks=g[side]||[],sentences=(side==='attack'?g.plan:g.defensePlan||'').match(/[^.!?]+[.!?]*/g)||[],objective=sentences[0]?.trim(),roles=[...new Set(picks.flatMap(p=>op(p.id)?.roles||[]))].filter(r=>!['front-line','back-line'].includes(r));return `<section class="r6-round-plan" aria-label="Round plan"><div class="r6-briefing-heading"><h2>Round plan</h2><span>${e(m.name)} · ${side==='attack'?'Attack':'Defense'}</span></div><div class="r6-briefing-body"><div><span class="r6-briefing-label">Objective</span>${objective?`<p class="r6-objective">${e(objective)}</p>`:'<p class="r6-plan-note">No site-specific objective is supplied. Use the team roles below to assign the hold.</p>'}</div><div><span class="r6-briefing-label">Team requirements</span><p class="r6-capabilities">${roles.map(roleName).map(e).join(' · ')}</p>${sentences.length>1?`<p class="r6-plan-note">${e(sentences.slice(1).join(' ').trim())}</p>`:''}</div></div>${g.provisional?'<small>Provisional guide — adapt to your bomb site.</small>':''}</section>`;}

function mapView(){const m=data.maps.find(m=>m.id===mapId)||data.maps[0],g=data.guides.maps[m?.id];return `<section class="r6-map-detail"><div class="r6-match-context"><img class="r6-context-image" src="assets/siege/map-${e(m.id)}.jpg" data-r6-fallback="${e(m.image||'')}" alt="${e(m.name)}"><div class="r6-context-fields"><label>Map<select id="r6-map">${opts(data.maps.map(m=>[m.id,m.name]),m.id)}</select></label><label>Side<select id="r6-side">${opts([['attack','Attack'],['defense','Defense']],side)}</select></label></div><button class="source-link" data-hub-source="${e(m.sourceUrl)}">Map reference ↗</button></div>${g?`${roundPlan(g,m)}<div class="r6-lineup-heading"><h2>Your recommended team</h2><p>Coordinate these five roles. Select an operator for their loadout and abilities.</p></div><div class="r6-team" aria-label="Recommended five-operator team">${g[side].map(card).join('')}</div><details class="r6-ban-details"><summary>Ban options</summary><div class="r6-ban-choices"><div><span class="r6-label">ATTACKERS</span><p>${g.attackBans.map(id=>e(op(id)?.name||id)).join(' / ')}</p></div><div><span class="r6-label">DEFENDERS</span><p>${g.defenseBans.map(id=>e(op(id)?.name||id)).join(' / ')}</p></div><small>Consider which utility you want to deny. Avoid banning an operator your own plan needs.</small></div></details><p class="r6-fine">Guide reviewed ${date(data.guides.reviewedAt)} · ${e(data.guides.patch)}. ${data.patch!==data.guides.patch?'A newer patch needs a guide review.':''}</p>`:'<p class="r6-plan">A guide for this map has not been reviewed yet.</p>'}<p class="r6-fine">Suggested lineup, not a map win-rate ranking. Maps follow Ubisoft’s index and can differ from the seasonal rotation.</p></section>`;}
function chart(kind){const c=data.analysis.charts.find(c=>c.kind===kind&&c.platform===platform&&c.side===side);if(!c)return '<p>No matching chart was published.</p>';const index=bundle.analysis.charts.findIndex(b=>b.url===c.url);return `<button class="r6-chart" data-r6-chart="${e(c.url)}" aria-label="Enlarge ${kind==='bans'?'ban rates':'presence and win delta'} chart"><img src="${e(index>=0?'assets/siege/chart-'+index+'.jpg':c.url)}" ${index>=0?`data-r6-fallback="${e(c.url)}"`:''} alt="Ubisoft ranked ${platform} ${side} ${kind} chart, ${e(c.dataPatch||data.analysis.title)}"></button>`;}
function statsView(){let rows=data.guides.bans.filter(b=>b.platform===platform&&b.side===side&&data.analysis.charts.some(c=>c.url===b.chartUrl));const patch=data.analysis.charts.find(c=>c.platform===platform&&c.side===side)?.dataPatch;return `<div class="r6-stats-heading"><div><span class="r6-label">OFFICIAL RANKED SNAPSHOT</span><h2>${e(patch||data.analysis.title)}</h2><p>Platinum and above · ${platform==='pc'?'PC':'Console'} · Published ${date(data.analysis.publishedAt)}</p></div><button class="hub-button secondary" data-hub-source="${e(data.analysis.sourceUrl)}">Ubisoft analysis ↗</button></div><div class="r6-stats-grid"><section class="r6-panel"><h3>Most banned</h3>${rows.length?`<table class="r6-ban-table"><thead><tr><th>Operator</th><th>Ban rate</th></tr></thead><tbody>${rows.sort((a,b)=>b.rate-a.rate).map(b=>`<tr><td>${op(b.id)?image(op(b.id)):''}${e(op(b.id)?.name||b.id)}</td><td>${b.rate}%<span class="r6-rate-track"><span style="width:${b.rate}%"></span></span></td></tr>`).join('')}</tbody></table>`:'<p>The official chart has changed. Use the chart below until its numeric table is reviewed.</p>'}${chart('bans')}</section><section class="r6-panel"><h3>Pick presence & win delta</h3><p>Presence is the pick rate when an operator is not banned. Win delta is not a win-rate percentage.</p>${chart('presence')}<p class="r6-fine">Click a chart to enlarge it. Ubisoft publishes these periodically; checking on launch retrieves the latest published snapshot.</p></section></div>`;}
function render(){if(!active)return;const root=$('#hub-app'),scroll=window.scrollY,focused=document.activeElement?.id;root.innerHTML=`<main class="hub-main r6-page"><header class="game-simple-heading"><div><span class="hub-eyebrow">RAINBOW SIX SIEGE / RANKED</span><h1>Plan your round</h1><p>Choose your side and map. See what each teammate brings.</p></div><div class="page-header-actions">${sourceStatus({label:loading?'Checking sources…':data.error||data.guides.error?'Refresh failed · saved data':'Ubisoft · '+date(data.fetchedAt),tone:data.error||data.guides.error?'warning':'neutral',detail:`Last successful check: ${dateTime(data.fetchedAt)}\n${data.error||'Latest published catalog and ranked charts.'}\n${data.guides.error||'Map guides reviewed separately: '+date(data.guides.reviewedAt)}`})}<button data-r6-refresh ${loading?'disabled':''}>Refresh</button></div></header><div class="r6-toolbar"><nav aria-label="Siege ranked sections">${[['maps','Map guide'],['stats','Pick & ban rates']].map(([id,label])=>`<button data-r6-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</nav><div class="r6-filter-row">${tab!=='maps'?`<label>Side<select id="r6-side">${opts([['attack','Attack'],['defense','Defense']],side)}</select></label>`:''}${tab!=='maps'?`<label>Platform<select id="r6-platform">${opts([['pc','PC'],['console','Console']],platform)}</select></label>`:''}</div></div>${tab==='maps'?mapView():statsView()}<details class="r6-method"><summary>Sources & updates</summary><p>Ubisoft’s operator catalog, ranked-map index and latest available charts refresh on launch and every 15 minutes. Map guides are maintained separately and fetched from Dropzone’s website, so guide edits do not require an installer update.</p><p>${e(data.guides.method)} New patches do not automatically rewrite tactical advice. Each guide shows its review date. Rates are only displayed when their source chart matches the currently fetched chart.</p>${data.error?`<p>${e(data.error)}</p>`:''}${data.guides.error?`<p>${e(data.guides.error)}</p>`:''}</details><dialog class="r6-chart-dialog" id="r6-chart-dialog"><div class="r6-chart-actions"><span>Official ranked chart</span><button data-r6-zoom>Actual size</button><button data-r6-close aria-label="Close chart">Close ×</button></div><div id="r6-chart-full"></div></dialog></main>`;window.scrollTo({top:scroll,behavior:'instant'});}
document.addEventListener('click',event=>{if(!active)return;const b=event.target.closest('button');if(!b)return;const d=b.dataset;if(d.r6Tab){tab=d.r6Tab;render();}if(d.r6Map){mapId=d.r6Map;render();}if('r6Refresh'in d)refresh(true);if(d.r6Chart){const chart=data.analysis.charts.find(c=>c.url===d.r6Chart);if(!chart)return;const i=bundle.analysis.charts.findIndex(c=>c.url===chart.url);$('#r6-chart-full').innerHTML=`<img src="${e(i>=0?'assets/siege/chart-'+i+'.jpg':chart.url)}" ${i>=0?`data-r6-fallback="${e(chart.url)}"`:''} alt="Official ranked chart">`;$('#r6-chart-full').classList.remove('is-zoomed');document.querySelector('[data-r6-zoom]').textContent='Actual size';$('#r6-chart-dialog').showModal();}if('r6Zoom'in d){const zoom=$('#r6-chart-full').classList.toggle('is-zoomed');b.textContent=zoom?'Fit to window':'Actual size';}if('r6Close'in d)$('#r6-chart-dialog').close();});
document.addEventListener('change',event=>{if(!active)return;const t=event.target;if(t.id==='r6-side'){side=t.value;}else if(t.id==='r6-map'){mapId=t.value;}else if(t.id==='r6-platform'){platform=t.value;persist('dropzone-siege-platform',platform);}else return;render();});
document.addEventListener('error',event=>{const img=event.target;if(img.dataset?.r6Fallback){const src=img.dataset.r6Fallback;delete img.dataset.r6Fallback;img.src=src;}else if(img.closest?.('.r6-chart,.r6-chart-dialog')){img.replaceWith(Object.assign(document.createElement('p'),{textContent:'Chart could not load. Open the Ubisoft analysis link.'}));}},true);
window.addEventListener('tbb-sources-updated',()=>{if(active&&!loading)refresh();});
