import {$,api,e,opts,stored,persist,date,dateTime} from './shared.js';
import bundle from './data/siege/siege-data.json' with {type:'json'};
import guideBundle from './data/siege/siege-guides.json' with {type:'json'};
let active=false,request=0,loading=false,data={...bundle,guides:guideBundle},tab='maps',side='attack',platform=stored('dropzone-siege-platform','pc'),mapId='clubhouse',query='',role='all',sort='name';
if(!['pc','console'].includes(platform))platform='pc';
const op=id=>data.operators.find(o=>o.id===id);
const ban=id=>data.guides.bans.find(b=>b.id===id&&b.platform===platform&&b.side===side&&data.analysis.charts.some(c=>c.url===b.chartUrl));
const roleName=s=>({'anti-gadget':'Anti-gadget','anti-entry':'Entry denial','intel-gatherer':'Intel','intel-denier':'Intel denial','crowd-control':'Crowd control','front-line':'Front line','back-line':'Support'}[s]||s.replaceAll('-',' ').replace(/^./,s=>s.toUpperCase()));
const image=o=>`<img src="${e(o.icon)}" data-r6-fallback="assets/siege/${e(o.id)}.png" width="54" height="54" alt="">`;
export function leaveSiege(){active=false;++request;}
export async function mountSiege(){active=true;render();await refresh();}
async function refresh(force=false){const token=++request;loading=true;render();try{const d=await api.siege({refresh:force});if(!active||token!==request)return;if(!d.operators?.length||!d.guides)throw new Error(d.error||'Siege data is unavailable.');data=d;if(!data.maps.some(m=>m.id===mapId))mapId=data.maps[0]?.id;}catch(err){if(!active||token!==request)return;data={...data,error:err.message};}if(!active||token!==request)return;loading=false;render();}
function card(pick){const o=op(pick.id);if(!o||o.side!==side)return '';const b=ban(o.id);return `<article class="r6-pick"><div class="r6-pick-heading">${image(o)}<div><h3>${e(o.name)}</h3><span>${e(o.roles.map(roleName).join(' · '))}</span></div></div><p>${e(pick.reason)}</p><div class="r6-pick-foot"><span>${b?`${b.rate}% banned · ${b.dataPatch}`:'Ban rate not published in top 10'}</span><button data-hub-source="${e(o.sourceUrl)}">Operator ↗</button></div></article>`;}
function mapView(){const m=data.maps.find(m=>m.id===mapId)||data.maps[0],g=data.guides.maps[m?.id];return `<div class="r6-map-layout"><aside class="r6-map-list" aria-label="Choose a map"><p class="r6-label">MAPS LISTED AS RANKED BY UBISOFT</p>${data.maps.map(m=>`<button data-r6-map="${m.id}" aria-pressed="${mapId===m.id}"><img src="${e(m.image)}" data-r6-fallback="assets/siege/map-${m.id}.jpg" alt="" loading="lazy"><span>${e(m.name)}</span><span>↗</span></button>`).join('')}</aside><section class="r6-map-detail"><div class="r6-map-banner"><img src="${e(m.image)}" data-r6-fallback="assets/siege/map-${m.id}.jpg" alt="${e(m.name)}" loading="lazy"><div><span class="r6-label">${side==='attack'?'ATTACK':'DEFENSE'} · MAP PICKS</span><h2>${e(m.name)}</h2><button data-hub-source="${e(m.sourceUrl)}">Official map page ↗</button></div></div>${g?`<div class="r6-plan"><strong>${g.provisional?'Starting lineup':'Suggested lineup'}</strong><p>${e(g.plan)}</p><small>Guide reviewed ${date(data.guides.reviewedAt)} · ${e(data.guides.patch)}. ${data.patch!==data.guides.patch?'A newer patch needs a guide review.':'Adjust to the bomb site and your team’s plan.'}</small></div><div class="r6-ban-choices"><div><span class="r6-label">ATTACKER BAN OPTIONS</span><p>${g.attackBans.map(id=>e(op(id)?.name||id)).join(' / ')}</p></div><div><span class="r6-label">DEFENDER BAN OPTIONS</span><p>${g.defenseBans.map(id=>e(op(id)?.name||id)).join(' / ')}</p></div><small>Choose a ban that disrupts the opponent’s plan without removing utility your team needs. These are map-guide suggestions.</small></div><div class="r6-picks">${g[side].map(card).join('')}</div>`:'<div class="r6-plan">This map was added to Ubisoft’s index. A map-specific guide has not been reviewed yet.</div>'}<p class="r6-fine">Map picks are editorial recommendations. Verified ranked pick/ban rates by map are unavailable. The official map index can differ from the active seasonal rotation.</p></section></div>`;}
function chart(kind){const c=data.analysis.charts.find(c=>c.kind===kind&&c.platform===platform&&c.side===side);if(!c)return '<p>No matching chart was published.</p>';const index=bundle.analysis.charts.findIndex(b=>b.url===c.url);return `<button class="r6-chart" data-r6-chart="${e(c.url)}" aria-label="Enlarge ${kind==='bans'?'ban rates':'presence and win delta'} chart"><img src="${e(c.url)}" ${index>=0?`data-r6-fallback="assets/siege/chart-${index}.jpg"`:''} alt="Ubisoft ranked ${platform} ${side} ${kind} chart, ${e(c.dataPatch||data.analysis.title)}"></button>`;}
function statsView(){let rows=data.guides.bans.filter(b=>b.platform===platform&&b.side===side&&data.analysis.charts.some(c=>c.url===b.chartUrl));const patch=data.analysis.charts.find(c=>c.platform===platform&&c.side===side)?.dataPatch;return `<div class="r6-stats-heading"><div><span class="r6-label">OFFICIAL RANKED SNAPSHOT</span><h2>${e(patch||data.analysis.title)}</h2><p>Platinum and above · ${platform==='pc'?'PC':'Console'} · Published ${date(data.analysis.publishedAt)}</p></div><button class="hub-button secondary" data-hub-source="${e(data.analysis.sourceUrl)}">Ubisoft analysis ↗</button></div><div class="r6-stats-grid"><section class="r6-panel"><h3>Most banned</h3>${rows.length?`<table class="r6-ban-table"><thead><tr><th>Operator</th><th>Ban rate</th></tr></thead><tbody>${rows.sort((a,b)=>b.rate-a.rate).map(b=>`<tr><td>${op(b.id)?image(op(b.id)):''}${e(op(b.id)?.name||b.id)}</td><td>${b.rate}%<span class="r6-rate-track"><span style="width:${b.rate}%"></span></span></td></tr>`).join('')}</tbody></table>`:'<p>The official chart has changed. Use the chart below until its numeric table is reviewed.</p>'}${chart('bans')}</section><section class="r6-panel"><h3>Pick presence & win delta</h3><p>Presence is the pick rate when an operator is not banned. Win delta is not a win-rate percentage.</p>${chart('presence')}<p class="r6-fine">Click a chart to enlarge it. Ubisoft publishes these periodically; checking on launch retrieves the latest published snapshot.</p></section></div>`;}
function operatorsView(){const list=data.operators.filter(o=>o.side===side&&(!query||o.name.toLowerCase().includes(query.toLowerCase()))&&(role==='all'||o.roles.includes(role))).sort((a,b)=>sort==='ban'?(ban(b.id)?.rate??-1)-(ban(a.id)?.rate??-1)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));const roles=[...new Set(data.operators.filter(o=>o.side===side).flatMap(o=>o.roles))].sort();return `<div class="r6-catalog-controls"><label>Search<input type="search" id="r6-search" placeholder="Find an operator…" value="${e(query)}"></label><label>Role<select id="r6-role">${opts([['all','All roles'],...roles.map(r=>[r,roleName(r)])],role)}</select></label><label>Sort<select id="r6-sort">${opts([['name','Name'],['ban','Published ban rate']],sort)}</select></label><span>${list.length} operators</span></div><div class="r6-operators">${list.map(o=>card({id:o.id,reason:o.roles.map(roleName).join(' · ')})).join('')||'<p>No matching operators.</p>'}</div>`;}
function render(){if(!active)return;const root=$('#hub-app'),scroll=window.scrollY,focused=document.activeElement?.id,caret=focused==='r6-search'?document.activeElement.selectionStart:null;root.innerHTML=`<main class="hub-main r6-page"><header class="r6-hero"><div><span class="r6-label">RANKED / ${e(data.patch||'SIEGE')}</span><h1>RAINBOW SIX<br><em>SIEGE</em></h1><p>Map picks. Ban decisions. Official ranked stats.</p></div><img src="assets/siege/noor-portrait.png" alt="Noor from Rainbow Six Siege"></header><div class="r6-toolbar"><nav aria-label="Siege ranked sections">${[['maps','Map picks'],['stats','Pick & ban rates'],['operators','Operators']].map(([id,label])=>`<button data-r6-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</nav><div class="r6-filter-row"><label>Side<select id="r6-side">${opts([['attack','Attack'],['defense','Defense']],side)}</select></label><label>Platform<select id="r6-platform">${opts([['pc','PC'],['console','Console']],platform)}</select></label></div></div><div class="r6-source-status" role="status"><span>${loading?'Checking Siege sources…':data.error?'Refresh failed · saved Siege data':`Official data checked ${e(dateTime(data.fetchedAt))}`}${data.guides.error?' · Guide refresh failed':''}</span><button data-r6-refresh ${loading?'disabled':''}>Refresh</button></div>${tab==='maps'?mapView():tab==='stats'?statsView():operatorsView()}<details class="r6-method"><summary>Sources & updates</summary><p>Ubisoft’s operator catalog, ranked-map index and latest available charts refresh on launch and every 15 minutes. Map guides are maintained separately and fetched from Dropzone’s website, so guide edits do not require an installer update.</p><p>${e(data.guides.method)} New patches do not automatically rewrite tactical advice. Each guide shows its review date. Rates are only displayed when their source chart matches the currently fetched chart.</p>${data.error?`<p>${e(data.error)}</p>`:''}${data.guides.error?`<p>${e(data.guides.error)}</p>`:''}</details><dialog class="r6-chart-dialog" id="r6-chart-dialog"><button data-r6-close aria-label="Close chart">Close ×</button><div id="r6-chart-full"></div></dialog></main>`;if(focused==='r6-search'){$('#r6-search')?.focus({preventScroll:true});try{$('#r6-search')?.setSelectionRange(caret,caret);}catch{}}window.scrollTo({top:scroll,behavior:'instant'});}
document.addEventListener('click',event=>{if(!active)return;const b=event.target.closest('button');if(!b)return;const d=b.dataset;if(d.r6Tab){tab=d.r6Tab;render();}if(d.r6Map){mapId=d.r6Map;render();}if('r6Refresh'in d)refresh(true);if(d.r6Chart){const chart=data.analysis.charts.find(c=>c.url===d.r6Chart);if(!chart)return;const i=bundle.analysis.charts.findIndex(c=>c.url===chart.url);$('#r6-chart-full').innerHTML=`<img src="${e(chart.url)}" ${i>=0?`data-r6-fallback="assets/siege/chart-${i}.jpg"`:''} alt="Official ranked chart">`;$('#r6-chart-dialog').showModal();}if('r6Close'in d)$('#r6-chart-dialog').close();});
document.addEventListener('change',event=>{if(!active)return;const t=event.target;if(t.id==='r6-side'){side=t.value;role='all';}else if(t.id==='r6-platform'){platform=t.value;persist('dropzone-siege-platform',platform);}else if(t.id==='r6-role')role=t.value;else if(t.id==='r6-sort')sort=t.value;else return;render();});
document.addEventListener('input',event=>{if(active&&event.target.id==='r6-search'){query=event.target.value;render();}});
document.addEventListener('error',event=>{const img=event.target;if(img.dataset?.r6Fallback){const src=img.dataset.r6Fallback;delete img.dataset.r6Fallback;img.src=src;}else if(img.closest?.('.r6-chart,.r6-chart-dialog')){img.replaceWith(Object.assign(document.createElement('p'),{textContent:'Chart could not load. Open the Ubisoft analysis link.'}));}},true);
window.addEventListener('tbb-sources-updated',()=>{if(active&&!loading)refresh();});
