import {$,api,e,stored,persist,toast} from './shared.js';
import maps from './data/wardogs/maps.json' with {type:'json'};
import {squadState,connectSquad,leaveSquad,inviteCode,editSquad,followTarget,setSharing} from './squad-client.js';
let lastRender=null;
export function mountSquad(){
 lastRender=null;
 $('#hub-app').innerHTML=`<main class="hub-main squad-page"><div class="library-intro"><div><span class="hub-eyebrow">WARDOGS / SQUAD ROOM</span><h1>One target. Your whole squad.</h1><p>Create a room, copy its invite code, and give it to your squad. Every code holder can read and edit its markers. Rooms expire after eight hours.</p></div><button class="hub-button secondary" data-route="wardogs">Open calculator</button></div><div id="squad-status" role="status"></div><div id="squad-connect" class="squad-connect"><label>Map<select id="squad-map">${maps.maps.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></label><button class="hub-button" id="squad-create">Create squad room</button><label>Invite code<input id="squad-code" maxlength="110" placeholder="DZ1.…" autocomplete="off" spellcheck="false"></label><button class="hub-button secondary" id="squad-join">Join room</button><button class="source-link" id="squad-reconnect">Reconnect saved room</button><p>Only shared markers and the selected map leave your PC. Your progression and loadouts stay local. Keep the invite code within your squad.</p></div><section id="squad-room" hidden><div class="hub-action-row"><strong id="squad-room-name"></strong><button class="hub-button" id="squad-copy">Copy invite code</button><button class="hub-button secondary" id="squad-leave">Disconnect</button><button class="source-link" id="squad-close">Close room for everyone</button></div><label class="squad-share"><input id="squad-share" type="checkbox"> Share my target automatically when I place or move it in the calculator</label><p id="squad-follow"></p><form id="squad-marker-form" class="squad-marker-form"><label>Name<input name="label" maxlength="60" required placeholder="North bridge"></label><label>Type<select name="type"><option value="target">Target</option><option value="rally">Rally point</option><option value="gun">Gun position</option><option value="note">Note</option></select></label><label>X<input name="x" type="number" step="0.01" required></label><label>Y<input name="y" type="number" step="0.01" required></label><button class="hub-button">Add marker</button><button type="button" class="source-link" id="squad-use-target">Use my calculator target</button></form><div id="squad-markers"></div><div class="hub-action-row"><button class="hub-button secondary" id="squad-save">Save room as local plan</button><button class="source-link" id="squad-unfollow">Stop following target</button></div></section><section><h2>Saved squad plans</h2><div id="squad-plans"></div><p>Plans stay on this PC and can be restored into a connected room on the same map. Gun position is only shared when you add it explicitly.</p></section></main>`;
 const run=fn=>async()=>{try{await fn();}catch(err){toast(err.message);}};
 $('#squad-create').onclick=run(()=>connectSquad({map:$('#squad-map').value}));$('#squad-join').onclick=run(()=>connectSquad({code:$('#squad-code').value.trim()}));$('#squad-reconnect').onclick=run(()=>connectSquad({restore:true}));$('#squad-copy').onclick=run(async()=>{await api.copy(inviteCode());toast('Invite code copied.');});$('#squad-leave').onclick=leaveSquad;$('#squad-close').onclick=run(()=>editSquad('close'));$('#squad-share').onchange=ev=>setSharing(ev.target.checked);$('#squad-unfollow').onclick=()=>followTarget(null);
 $('#squad-use-target').onclick=()=>{const s=squadState(),local=stored('dropzone-wardogs-v1',{}),p=local.positions?.[s.room?.map]?.target;if(!p){toast('Place a target on the room’s map in the calculator first.');return;}const f=$('#squad-marker-form');f.elements.x.value=p.x;f.elements.y.value=p.y;};
 $('#squad-marker-form').onsubmit=async ev=>{ev.preventDefault();const f=ev.target;try{await editSquad('put',{marker:{id:crypto.randomUUID(),label:f.elements.label.value,type:f.elements.type.value,x:+f.elements.x.value,y:+f.elements.y.value}});f.elements.label.value='';}catch(err){toast(err.message);}};
 $('#squad-save').onclick=()=>{const r=squadState().room;if(!r)return;const saved=stored('dropzone-squad-plans',[]);persist('dropzone-squad-plans',[{...r,id:crypto.randomUUID(),savedAt:new Date().toISOString()},...(Array.isArray(saved)?saved:[])].slice(0,20));renderPlans();toast('Squad plan saved locally.');};
 renderSquad();renderPlans();
}
function renderSquad(){if(!$('#squad-status'))return;const s=squadState();$('#squad-status').textContent=s.message;$('#squad-connect').hidden=s.connected;$('#squad-room').hidden=!s.connected;$('#squad-reconnect').hidden=!s.saved;if(!s.connected)return;
 $('#squad-room-name').textContent=maps.maps.find(m=>m.id===s.room.map).name+' · expires '+new Date(s.room.expires).toLocaleTimeString();$('#squad-close').hidden=!s.owner;$('#squad-share').checked=s.share;$('#squad-follow').textContent=s.follow?'Following: '+s.room.markers.find(m=>m.id===s.follow)?.label+' · calculator target updates automatically on this map.':'Choose Follow on a target to receive the spotter’s changes. Your gun stays fixed.';
 const renderKey=s.room.version+'|'+s.follow;if(renderKey===lastRender)return;lastRender=renderKey;
 $('#squad-markers').innerHTML=s.room.markers.map(m=>`<article><span>${e(m.type.toUpperCase())}</span><strong>${e(m.label)}</strong><code>${m.x.toFixed(2)}, ${m.y.toFixed(2)}</code>${m.type==='target'?`<button class="hub-button secondary" data-follow="${e(m.id)}">${s.follow===m.id?'Following':'Follow target'}</button>`:''}<button class="source-link" data-remove-marker="${e(m.id)}">Remove</button></article>`).join('')||'<p>No shared markers. Add coordinates or use your calculator target.</p>';
 document.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>{followTarget(b.dataset.follow);toast('Following target. Open the calculator on '+maps.maps.find(m=>m.id===s.room.map).name+'.');});document.querySelectorAll('[data-remove-marker]').forEach(b=>b.onclick=()=>editSquad('remove',{markerId:b.dataset.removeMarker}).catch(err=>toast(err.message)));
}
function renderPlans(){const raw=stored('dropzone-squad-plans',[]),plans=Array.isArray(raw)?raw:[];$('#squad-plans').innerHTML=plans.map(p=>`<article><strong>${e(p.map)}</strong><span>${p.markers?.length||0} markers · ${e(new Date(p.savedAt).toLocaleString())}</span><button class="source-link" data-restore-plan="${e(p.id)}">Add to connected room</button><button class="source-link" data-delete-plan="${e(p.id)}">Remove local plan</button></article>`).join('')||'<p>No saved plans yet.</p>';
 document.querySelectorAll('[data-restore-plan]').forEach(b=>b.onclick=async()=>{const plan=plans.find(p=>p.id===b.dataset.restorePlan),state=squadState();if(!state.connected||state.room.map!==plan.map||state.room.revision!==plan.revision){toast('Connect to a room using the same map and calibration first.');return;}try{for(const m of plan.markers)await editSquad('put',{marker:m});toast('Plan added to room.');}catch(err){toast('Plan only partly restored: '+err.message);}});document.querySelectorAll('[data-delete-plan]').forEach(b=>b.onclick=()=>{persist('dropzone-squad-plans',plans.filter(p=>p.id!==b.dataset.deletePlan));renderPlans();});
}
window.addEventListener('dropzone-squad-state',renderSquad);
