import {$,e,opts,toast} from './shared.js';
import {getState,saveState,saveRecord,download} from './command-store.js';
import {APP_VERSION} from './version.js';
import {GAMES} from './command-model.js';
let context={id:'home',game:''};
export const calculatorChoices=[['sensitivity','Physical sensitivity conversion'],['display','Frame time & aspect ratio'],['damage','Damage breakpoint']];
export function initExtras(){
 window.addEventListener('dropzone-workspace-change',ev=>{context=ev.detail;applyGameAccess(context.game);});
 $('.global-tools').insertAdjacentHTML('beforeend','<button class="workspace-control" id="context-feedback" title="Report a problem with this tool">Feedback</button>');
 $('#context-feedback').onclick=()=>{
  const dialog=document.createElement('dialog');dialog.className='cc-dialog';
  const heading=document.querySelector('#hub-app h1,#league-app:not([hidden]) h1')?.textContent||context.id;
  const report={app:'Dropzone',version:APP_VERSION,game:context.game,tool:heading,source:'',description:''};
  dialog.innerHTML=`<form><header><h2>Feedback on ${e(heading)}</h2><button type="button" data-close>Close</button></header><p>Version ${APP_VERSION} · ${e(context.game)}. Review the report before saving or sharing it.</p><label>Affected source (optional)<input name="source" type="url" placeholder="https://…"></label><label>What happened, and what did you expect?<textarea name="description" required maxlength="16000"></textarea></label><button>Review report</button></form>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  dialog.querySelector('form').onsubmit=ev=>{ev.preventDefault();Object.assign(report,Object.fromEntries(new FormData(ev.target)));dialog.innerHTML=`<h2>Review report</h2><pre style="white-space:pre-wrap">${e(JSON.stringify(report,null,2))}</pre><div class="cc-actions"><button data-export>Save & export report</button><button data-close>Cancel</button></div><p>Nothing is sent automatically. Share the exported file when you choose.</p>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('[data-export]').onclick=()=>{if(GAMES.includes(report.game))saveRecord({kind:'feedback',game:report.game,title:report.tool+' feedback',body:report.description,source:report.source,data:{version:APP_VERSION,category:report.tool}});download('dropzone-feedback.json',report);dialog.close();};};
 };
 document.addEventListener('click',ev=>{const pin=ev.target.closest('[data-pin-calculation]');if(pin){try{const host=document.getElementById(pin.dataset.pinCalculation),result=host?.innerText.trim()||host?.textContent.trim();if(!result)throw Error('Calculate a result first.');const panel=host.closest('section'),inputs=Array.from(panel.querySelectorAll('input,select')).map(el=>(el.closest('label')?.firstChild.textContent.trim()||el.id)+': '+el.value).join('\n'),id=crypto.randomUUID(),game=GAMES.includes(pin.dataset.game)?pin.dataset.game:'wardogs',title=panel.querySelector('h2').textContent;const pins=JSON.parse(localStorage.getItem('dropzone-pins-v1')||'[]');if(pins.length>=12)throw Error('Remove a pin in Tools before adding another.');saveRecord({id,kind:'note',game,title:title+' result',body:inputs+'\n\n'+result,tags:'calculator pinned',data:{category:'calculation'}});localStorage.setItem('dropzone-pins-v1',JSON.stringify([...pins,{id:'command',game,recordId:id,label:title+' result'}]));toast('Result saved and pinned. Open it from Tools (Ctrl K).');}catch(err){toast(err.message);}}});
}
export function calculatorNavigation(filter){return `<label class="cc-search">Find a calculator<input id="cc-calculator-search" type="search" placeholder="Sensitivity, damage, frame time…"></label><p class="cc-muted">Save a calculated result with Pin result. It becomes a searchable notebook entry.</p>`;}
export function bindCalculators(filter){
 for(const [id,label]of calculatorChoices){const result=$('#calc-'+id+'-result');if(!result)continue;const panel=result.closest('section');panel.dataset.calculator=id;const pin=document.createElement('button');pin.textContent='Pin result';pin.dataset.pinCalculation=result.id;pin.dataset.game=filter;pin.className='workspace-control';panel.append(pin);panel.addEventListener('input',()=>result.replaceChildren());panel.addEventListener('change',()=>result.replaceChildren());}
 const search=$('#cc-calculator-search');if(search)search.oninput=()=>{for(const panel of document.querySelectorAll('[data-calculator]'))panel.hidden=!panel.textContent.toLowerCase().includes(search.value.toLowerCase());};
}
export function applyGameAccess(game){const p=getState().preferences,preset=p.accessibility?.[game];document.body.classList.toggle('cc-access-contrast',preset?.contrast??!!p.contrast);document.body.classList.toggle('cc-reduced-motion',preset?.reducedMotion??!!p.reducedMotion);const textSize=preset?.textSize||Number(localStorage.getItem('rf-text-size')||100);window.dispatchEvent(new CustomEvent('dropzone-text-size',{detail:{value:textSize,save:false}}));}
export function accessPresetFields(game){const p=getState().preferences.accessibility?.[game]||{};return `<section class="cc-panel"><h2>Accessibility for this game</h2><p class="cc-muted">This preset takes effect when opening ${e(game)}. Reset to use the app-wide settings.</p><div class="cc-form-grid"><label>Text size<select id="cc-access-size">${opts([100,115,130,150,175,200].map(n=>[String(n),n+'%']),String(p.textSize||100))}</select></label><label class="cc-check"><input id="cc-access-contrast" type="checkbox" ${p.contrast?'checked':''}>High contrast</label><label class="cc-check"><input id="cc-access-motion" type="checkbox" ${p.reducedMotion?'checked':''}>Reduce motion</label></div><div class="cc-actions"><button data-cc="access-save">Save game preset</button><button data-cc="access-reset">Reset preset</button></div></section>`;}
export function saveAccessPreset(game,reset=false){if(!GAMES.includes(game))throw Error('Choose a specific game first.');const s=getState(),accessibility={...s.preferences.accessibility};if(reset)delete accessibility[game];else accessibility[game]={textSize:Number($('#cc-access-size').value),contrast:$('#cc-access-contrast').checked,reducedMotion:$('#cc-access-motion').checked};saveState({...s,preferences:{...s.preferences,accessibility}});applyGameAccess(game);toast(reset?'Using app-wide accessibility settings.':'Game accessibility preset saved.');}

export function bindClipMoments(record,video,host){
 const section=document.createElement('section');section.innerHTML='<h3>Timestamped notes</h3><div class="cc-moments"></div><label>What happened here?<textarea maxlength="1000" placeholder="Pause at the moment, then add an observation."></textarea></label><button type="button">Add note at current time</button>';host.append(section);
 const paint=()=>{const list=section.querySelector('.cc-moments');list.replaceChildren();for(const [index,m]of (record.data.moments||[]).entries()){const row=document.createElement('div');row.className='cc-moment';const seek=document.createElement('button'),text=document.createElement('p'),remove=document.createElement('button');seek.textContent=Math.floor(m.time/60)+':'+String(Math.floor(m.time%60)).padStart(2,'0');seek.setAttribute('aria-label','Seek to '+seek.textContent);seek.onclick=()=>{if(Number.isFinite(video.duration)&&m.time>video.duration){toast('This timestamp is outside the attached video.');return;}video.currentTime=m.time;};text.textContent=m.text;remove.textContent='Remove';remove.onclick=()=>{const latest=getState().records.find(r=>r.id===record.id)||record;record={...latest,data:{...latest.data,moments:latest.data.moments.filter((_,i)=>i!==index)}};saveRecord(record);paint();};row.append(seek,text,remove);list.append(row);}};
 section.querySelector(':scope>button').onclick=()=>{try{const text=section.querySelector('textarea').value.trim();if(!text)throw Error('Write an observation first.');if(!Number.isFinite(video.duration))throw Error('Wait for the video to load.');const latest=getState().records.find(r=>r.id===record.id)||record;record={...latest,data:{...latest.data,moments:[...(latest.data.moments||[]),{time:video.currentTime,text}].sort((a,b)=>a.time-b.time)}};saveRecord(record);section.querySelector('textarea').value='';paint();}catch(err){toast(err.message);}};paint();
}
