import {$,api,e,stored,persist,toast} from './shared.js';
let navigate,current,games=[];
const key='dropzone-pins-v1';
const names={settings:'Settings',home:'Game library',saved:'Saved loadouts',sources:'Source status',updates:'App updates',progression:'Progression',damage:'Damage lab',planner:'Loadout planner',intel:'My patch alerts',squad:'Squad room',wardogs:'Artillery calculator',patches:'Patch notes',watch:'Videos'};
const pins=()=>{const p=stored(key,[]);return Array.isArray(p)?p.filter(x=>x&&!['command','saved'].includes(x.id)&&!x.recordId&&typeof x.id==='string'&&typeof x.label==='string').slice(0,12):[];};
export function workspaceLabel(id,game){return (game?(games.find(g=>g.id===game)?.shortName||game)+' / ':'')+(names[id]||games.find(g=>g.id===id)?.name||id);}
export function rememberWorkspace(id,game){current={id,game};try{persist('dropzone-last-workspace',current);}catch{}paintPins();}
export function restoreWorkspace(){const startup=stored('dropzone-startup-game','last');return startup==='last'?(stored('dropzone-restore-session',true)!==false?stored('dropzone-last-workspace',null):null):{id:startup};}
function paintPins(){const el=$('#workspace-pin');if(el){el.disabled=!current;el.textContent=pins().some(p=>p.id===current?.id&&p.game===current?.game)?'Pinned ★':'Pin ☆';}}
async function openPin(pin){if(pin.recordId){await navigate('command',pin.game);window.dispatchEvent(new CustomEvent('dropzone-open-record',{detail:pin.recordId}));return;}if(pin.damage)persist('dropzone-damage-v1',pin.damage);if(pin.savedKey){await navigate('saved');document.querySelectorAll('[data-hub-saved]').forEach(b=>{if(b.dataset.hubSaved===pin.savedKey)b.click();});return;}navigate(pin.id,pin.game,pin.view);}
function palette(){
 const dialog=$('#workspace-dialog');const savedBuilds=stored('tbb-saved-loadouts',[]);const choices=[...pins().map(p=>({...p,pinned:true})),...games.filter(g=>g.status==='active').flatMap(g=>[{id:g.id,label:g.name},...(g.pages||[]).map(id=>({id,game:g.id,label:workspaceLabel(id,g.id)}))]),...['settings','intel','sources','updates'].map(id=>({id,label:names[id]}))];
 dialog.innerHTML=`<form method="dialog"><button class="hub-button secondary">Close</button></form><h2>Your tools, one shortcut away.</h2><input id="workspace-search" type="search" placeholder="Find a game, tool or pin…" aria-label="Find a tool"><div id="workspace-results"></div><div class="workspace-preferences"><p>Choose your startup game in Settings.</p><p>Ctrl K opens this menu. Desktop quick access stays above borderless games; exclusive fullscreen may hide it.</p>${api.desktop?'<label>Desktop shortcut<select id="quick-shortcut"><option value="CommandOrControl+Alt+D">Ctrl Alt D</option><option value="CommandOrControl+Shift+Space">Ctrl Shift Space</option><option value="F8">F8</option></select></label><p id="quick-status" role="status"></p>':'<p>Global shortcuts and the floating panel are available in the Windows app.</p>'}</div>`;
 const draw=()=>{$('#workspace-results').innerHTML=choices.filter(x=>x.label.toLowerCase().includes($('#workspace-search').value.toLowerCase())).map((x)=>`<div><button class="workspace-result" data-choice="${choices.indexOf(x)}"><span>${x.pinned?'★':'↗'}</span>${e(x.label)}</button>${x.pinned?`<button class="source-link" data-unpin="${e(x.id)}" data-game="${e(x.game||'')}" data-record="${e(x.recordId||'')}">Unpin</button>`:''}</div>`).join('')||'<p>No matching tools.</p>';};
 $('#workspace-search').oninput=draw;
 dialog.onclick=ev=>{const choice=ev.target.closest('[data-choice]'),unpin=ev.target.closest('[data-unpin]');if(choice){dialog.close();openPin(choices[Number(choice.dataset.choice)]);}if(unpin){persist(key,pins().filter(p=>!(p.id===unpin.dataset.unpin&&(p.game||'')===unpin.dataset.game&&(p.recordId||'')===unpin.dataset.record)));dialog.close();paintPins();palette();}};
 if(api.desktop){const status=s=>{if(!$('#quick-shortcut'))return;$('#quick-shortcut').value=s.shortcut;$('#quick-status').textContent=s.registered?'Shortcut ready. Press it again to hide the panel.':'Shortcut is already in use. Choose another.';};api.quickPanel('status').then(status);$('#quick-shortcut').onchange=ev=>{persist('dropzone-quick-shortcut',ev.target.value);return api.quickPanel({shortcut:ev.target.value}).then(status).catch(err=>toast(err.message));};}
 draw();dialog.showModal();$('#workspace-search').focus();
}
export function startWorkspaceTools(list,route){
 games=list;navigate=route;
 $('.global-tools').insertAdjacentHTML('afterbegin','<button id="workspace-open" class="workspace-control" title="Find tools (Ctrl K)">Tools <kbd>Ctrl K</kbd></button><button id="workspace-pin" class="workspace-control">Pin ☆</button><button id="workspace-quick" class="workspace-control">Quick panel</button><button id="workspace-full" class="workspace-control" hidden>Full app ↗</button>');
 document.body.insertAdjacentHTML('beforeend','<dialog id="workspace-dialog" class="workspace-dialog"></dialog>');
 $('#workspace-open').onclick=palette;$('#workspace-pin').onclick=()=>{if(!current)return;const p=pins(),exists=p.some(x=>x.id===current.id&&x.game===current.game);if(exists){palette();return;}if(p.length>=12){toast('You have 12 pins. Remove one in Tools first.');return;}persist(key,[...p,{...current,label:workspaceLabel(current.id,current.game),...(current.id==='damage'?{damage:stored('dropzone-damage-v1',{})}:{})}]);paintPins();toast('Pinned. Find it in Tools with Ctrl K.');};
 const apply=s=>{document.body.classList.toggle('quick-panel',!!s.quick);$('#workspace-full').hidden=!s.quick;$('#workspace-quick').hidden=!!s.quick;};
 $('#workspace-quick').onclick=()=>api.quickPanel?api.quickPanel('toggle').then(apply):toast('Open the Windows app to use the floating panel.');$('#workspace-full').onclick=()=>api.quickPanel('full').then(apply);api.onQuickPanel?.(apply);if(api.quickPanel){const saved=stored('dropzone-quick-shortcut',null);api.quickPanel(saved?{shortcut:saved}:'status').then(apply).catch(()=>{});}
 document.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&!ev.altKey&&ev.key.toLowerCase()==='k'){ev.preventDefault();ev.stopImmediatePropagation();if($('#workspace-dialog').open)$('#workspace-dialog').close();else palette();}if(ev.key==='Escape'&&document.body.classList.contains('quick-panel')&&!document.querySelector('dialog[open]'))api.quickPanel?.('hide');},true);
}
