from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(file,old,new):
 p=root/file;text=p.read_text(encoding='utf-8')
 if old not in text:raise Exception('Missing '+file+' '+old[:60])
 p.write_text(text.replace(old,new),encoding='utf-8')
edit('app/command-center.js',"import {teamFields", "import {initExtras,bindCalculators,calculatorNavigation,accessPresetFields,applyGameAccess} from './workspace-extras.js';\nimport {teamFields")
edit('app/command-center.js',"games=list;navigate=route;applyAccess();startBackgroundTools();", "games=list;navigate=route;applyAccess();startBackgroundTools();initExtras();")
edit('app/command-center.js',"if(view)tab=view;render();", "if(view)tab=view;applyGameAccess(filter);render();")
edit('app/command-center.js',"function render(){if(!active)return;disposeTools();", "function render(){if(!active)return;disposeTools();if(window.location.protocol!=='file:'){const url=new URL(window.location.href);url.searchParams.set('game','command');url.searchParams.set('context',filter);url.searchParams.set('view',tab);window.history.replaceState(null,'',url);}")
edit('app/command-center.js',"if(tab==='settings')$('#cc-content').insertAdjacentHTML", "if(tab==='tools'){$('#cc-content').insertAdjacentHTML('afterbegin',calculatorNavigation(filter));bindCalculators(filter);}if(tab==='settings'&&filter!=='all')$('#cc-content').insertAdjacentHTML('beforeend',accessPresetFields(filter));if(tab==='settings')$('#cc-content').insertAdjacentHTML")
edit('app/command-center.js',"filter=t.value;if(tab==='roster'", "filter=t.value;applyGameAccess(filter);if(tab==='roster'")
edit('app/command-tools.js',"import {importCalendar", "import {saveAccessPreset,bindClipMoments} from './workspace-extras.js';\nimport {importCalendar")
edit('app/command-tools.js'," if(action==='sync')", " if(action==='access-save'||action==='access-reset'){saveAccessPreset(filter,action==='access-reset');render();return;}\n if(action==='sync')")
edit('app/command-tools.js',"  const bounds=()=>", "  bindClipMoments(record,video,host);\n  const bounds=()=>")
edit('app/app.js',"function stepTextSize(direction)","window.addEventListener('dropzone-text-size',ev=>applyTextSize(ev.detail.value,ev.detail.save===true));\nfunction stepTextSize(direction)")
edit('app/command-center.js',"...(r.data.boards||[]).map(a=>a.imageId)].filter(Boolean)","...(r.data.boards||[]).map(a=>a.imageId)].filter(Boolean)")
edit('app/workspace-tools.js',"const choices=[...commandSearch()", "const choices=[...['Sensitivity conversion','Frame time calculator','Damage breakpoint','VALORANT weapon stats'].map(label=>({id:'command',game:current?.game,view:'tools',label})),...commandSearch()")
edit('app/workspace-tools.js',"navigate(pin.id,pin.game);", "navigate(pin.id,pin.game,pin.view);")
edit('app/workspace-tools.js',"data-game=\"${e(x.game||'')}\">Unpin", "data-game=\"${e(x.game||'')}\" data-record=\"${e(x.recordId||'')}\">Unpin")
edit('app/workspace-tools.js',"(p.game||'')===unpin.dataset.game)","(p.game||'')===unpin.dataset.game&&(p.recordId||'')===unpin.dataset.record)")
edit('app/workflow-model.js',"x.record.body,x.record.tags,", "x.record.body,x.record.tags,x.record.patch,")
edit('app/workflow-model.js',"[r.body,r.tags,", "[r.body,r.tags,r.patch,")
edit('app/navigation-compact.css',".app-rail .rail-link .icon{flex:none}",".app-rail .rail-link .icon{flex:none}.app-rail .rail-link>span[aria-hidden=true]{opacity:1!important;pointer-events:none}")
