from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(file,old,new):
 p=root/file;text=p.read_text(encoding='utf-8')
 if old not in text:raise Exception('Missing '+file+': '+old[:90])
 p.write_text(text.replace(old,new),encoding='utf-8')
def remove_line(file,prefix):
 p=root/file;lines=p.read_text(encoding='utf-8').splitlines();p.write_text('\n'.join(x for x in lines if not x.startswith(prefix))+'\n',encoding='utf-8')
edit('app/command-center.js',"const labels={home:'Tonight',build:","const labels={build:")
edit('app/command-center.js',"['home','build','strategy','team','note','goal','roster']","['build','strategy','team','note','goal','roster']")
edit('app/command-center.js',"tab='home',filter='all'","tab='build',filter='all'")
edit('app/command-center.js',"title=\"Session center\" aria-label=\"Session center\"", "title=\"Game tools\" aria-label=\"Game tools\"")
edit('app/command-center.js',"<span>Session center</span>","<span>Game tools</span>")
remove_line('app/command-center.js'," $('.global-tools').insertAdjacentHTML('beforeend','<button class=\"workspace-control\" data-route=\"command\">")
remove_line('app/command-center.js',"function home(){")
remove_line('app/command-center.js',"export function enhanceHome(){")
remove_line('app/command-center.js',"function sessionForm(){")
edit('app/command-center.js',"Session center is ready.","Your game tools are ready.")
edit('app/command-center.js',"export function mountCommandCenter(game=null,view=null){active=true;if(game&&GAMES.includes(game))filter=game;if(view)tab=view;applyGameAccess(filter);render();}","export const preferredGames=()=>getState().favorites;\nexport function mountCommandCenter(game=null,view=null){active=true;filter=GAMES.includes(game)?game:GAMES.includes(filter)?filter:getState().favorites[0]||'wardogs';tab=view&&labels[view]?view:'build';applyGameAccess(filter);render();}")
edit('app/command-center.js',"DROPZONE / SESSION CENTER","${e(names()[filter]||'DROPZONE')} / YOUR TOOLS")
edit('app/command-center.js',"labels[tab]||'Session center'","labels[tab]||'Game tools'")
edit('app/command-center.js',"<p>Plan it. Play it. Keep what worked.</p>","<p>Your saved setups and tools for ${e(names()[filter]||'this game')}.</p>")
edit('app/command-center.js',"${actions(button('start-session','Start session')+button('new','＋ Add entry',", "${actions(button('new','＋ Add entry',")
edit('app/command-center.js',"aria-label=\"Session tools\"","aria-label=\"Game tools\"")
edit('app/command-center.js',"${tab==='home'?home():tab==='roster'?roster():","${tab==='roster'?roster():")
edit('app/command-center.js',"${gameOptions(filter,true)}","${gameOptions(filter)}")
edit('app/command-center.js',"return `${tab==='goal'?goalGroups():''}","return `${tab==='session'?`<section class=\"cc-panel\"><h2>Optional session tracking</h2><p class=\"cc-muted\">Keep a checklist and recap for this game when you want them.</p>${actions(button(getState().activeSession?'end-session':'start-session',getState().activeSession?'Finish & recap':'Start session'))}${sessionOverview(getState().records.find(r=>r.id===getState().activeSession&&r.game===filter))}</section>`:''}${tab==='goal'?goalGroups():''}")
edit('app/command-center.js',"tab=['valorant','rivals'].includes(filter)?'roster':'home'", "tab=['valorant','rivals'].includes(filter)?'roster':'build'")
edit('app/command-center.js',"tab='home';render();", "tab='build';render();")
edit('app/command-center.js',"tab=labels[r.kind]?r.kind:'home'","tab=labels[r.kind]?r.kind:'build'")
edit('app/command-center.js',"document.addEventListener('click',ev=>{const b=ev.target.closest('[data-cc],[data-tab]');", "document.addEventListener('click',ev=>{if(ev.target.closest('[data-manage-games]')){setupDashboard({show,games,render:()=>window.dispatchEvent(new Event('dropzone-favorites-change'))});return;}const b=ev.target.closest('[data-cc],[data-tab]');")
edit('app/hub.js',"leaveCommandCenter,enhanceHome}", "leaveCommandCenter,preferredGames}")
edit('app/hub.js',";enhanceHome();", ";")
edit('app/hub.js',"location(null,'Session center')", "location(null,'Game tools')")
edit('app/hub.js',"  const navigation=++navigationRevision;", "  if(id==='command'&&!watchGame)watchGame=game()?.id;\n  const navigation=++navigationRevision;")
edit('app/index.html',">Session tools</button>",">Game tools</button>")
edit('app/workspace-tools.js',"command:'Session center'", "command:'Game tools'")
edit('app/session-workflow.js',"value=\"Tonight’s session\"","value=\"Practice session\"")
edit('app/session-workflow.js',"['home','Session overview']", "['home','Game workspace']")
edit('app/session-workflow.js',"['game','Game workspace'],", "")
edit('app/session-workflow.js',"navigate(v.tool==='game'?v.game:'command',v.game,'home')", "navigate(['game','home'].includes(v.tool)?v.game:'command',v.game,'build')")
edit('app/session-workflow.js',"Make Dropzone yours", "Your main games")
edit('app/session-workflow.js',"Pick your main games. You can change this anytime.", "Pin the games you play most. They appear first in your library; every other game stays available below.")
edit('app/session-workflow.js',"<button>Save dashboard</button>", "<button>Save games</button>")
edit('app/session-workflow.js',"onboarded:true,detectGame:f.has('detect')", "onboarded:true,detectGame:f.has('detect')")
edit('app/command-tools.js',"Choose what Start Session can open.", "Optionally choose what a tracked session can open.")
p=root/'app/hub.js';text=p.read_text(encoding='utf-8');needle="<div class=\"game-grid root-games\">${available.map(card).join('')}</div>";assert needle in text
text=text.replace(needle,"${preferredGames().length?`<section><h2>Your games</h2><div class=\"game-grid root-games\">${preferredGames().map(id=>state.games.find(g=>g.id===id)).filter(Boolean).map(card).join('')}</div></section><details class=\"other-games\"><summary>Other games</summary><div class=\"game-grid root-games\">${available.filter(g=>!preferredGames().includes(g.id)).map(card).join('')}</div></details>`:`<div class=\"game-grid root-games\">${available.map(card).join('')}</div>`}")
text=text.replace('<span class="library-count">${available.length} game spaces</span>','<button class="hub-button secondary" data-manage-games>Your main games</button>')
text += "\nwindow.addEventListener('dropzone-favorites-change',()=>{renderRail();if(state.route==='home')renderHome();});\n"
p.write_text(text,encoding='utf-8')
p=root/'app/command-center.css';p.write_text(p.read_text(encoding='utf-8')+'\n.other-games{margin-top:24px}.other-games>summary{cursor:pointer;padding:16px 0;color:var(--muted)}.other-games>.game-grid{padding-top:12px}\n',encoding='utf-8')
