from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(file,old,new):
 p=root/file
 text=p.read_text(encoding='utf-8')
 if old not in text: raise Exception('Missing replacement in '+file+': '+old[:100])
 p.write_text(text.replace(old,new),encoding='utf-8')
edit('app/hub.js',"g?.kind==='siege'?'Ranked':'Loadouts'","g?.kind==='siege'?'Ranked':g?.kind==='arena'?'Roster':'Loadouts'")
edit('app/hub.js',"  ++state.request;state.route=id;", "  if(window.location.protocol!=='file:'){const url=new URL(window.location.href);url.searchParams.set('game',id);if(watchGame)url.searchParams.set('context',watchGame);else url.searchParams.delete('context');if(initialView)url.searchParams.set('view',initialView);else url.searchParams.delete('view');window.history.replaceState(null,'',url);}\n  window.dispatchEvent(new CustomEvent('dropzone-workspace-change',{detail:{id,game:watchGame||id}}));\n  ++state.request;state.route=id;")
edit('app/hub.js',"requested||restored?null:previous?.game);startUpdatePolling()", "requested?new URLSearchParams(window.location.search).get('context'):restored?null:previous?.game,new URLSearchParams(window.location.search).get('view'));startUpdatePolling()")
edit('app/command-center.js',"bindPlanning,planningDetails}","bindPlanning,planningDetails,teamDetails}")
edit('app/command-center.js',"import {searchWorkspace}","import {searchWorkspace,challengeGroups}")
edit('app/command-center.js',"let pairingCards=null,pairingTimer;","let pairingCards=null,pairingTimer,editorDraft;\nconst navButton=([id,label])=>`<button data-tab=\"${id}\" aria-current=\"${id===tab?'page':'false'}\">${label}</button>`;\nfunction sessionNav(){const items=Object.entries(labels).filter(([k])=>k!=='roster'||['valorant','rivals'].includes(filter));const primary=['home','build','strategy','team','note','goal','roster'];return items.filter(([k])=>primary.includes(k)).map(navButton).join('')+`<details><summary>More tools</summary><div>${items.filter(([k])=>!primary.includes(k)).map(navButton).join('')}</div></details>`;}\nfunction goalGroups(){const groups=challengeGroups(entries('goal').filter(r=>!goalStatus(r,getState().records).missing.length));return `<details class=\"cc-panel cc-checklist-group\"><summary>Goals you can work on together</summary><p class=\"cc-muted\">Groups match the game, mode, map and weapon restrictions you entered. Check each objective’s conditions in game; blank restrictions mean any.</p>${groups.map((group,i)=>`<div class=\"cc-goal-group\"><b>Session group ${i+1}</b>${group.map(r=>`<p>${button('open',e(r.title),`data-id=\"${r.id}\"`)} · ${e(r.data.challengeAction||'No action condition recorded')}</p>`).join('')}</div>`).join('')||'<p>No available unfinished goals. Complete prerequisites or add a goal.</p>'}</details>`;}")
edit('app/command-center.js',"${Object.entries(labels).filter(([k])=>k!=='roster'||['valorant','rivals'].includes(filter)).map(([id,label])=>`<button data-tab=\"${id}\" aria-current=\"${id===tab?'page':'false'}\">${label}</button>`).join('')}","${sessionNav()}")
edit('app/command-center.js',"return `${tab==='event'?","return `${tab==='goal'?goalGroups():''}${tab==='event'?")
edit('app/command-center.js',"const d=record.data||{},kind=record.kind;let fields='';","editorDraft=record;const d=record.data||{},kind=record.kind;let fields='';")
edit('app/command-center.js',"if(t.name==='kind'&&t.closest('#cc-editor'))edit({kind:t.value,game:dialog.querySelector('[name=game]').value,data:{}});","if(['kind','game'].includes(t.name)&&t.closest('#cc-editor')){const f=t.closest('form'),v=Object.fromEntries(new FormData(f));edit({...editorDraft,kind:v.kind||f.dataset.kind,game:v.game,title:v.title,body:v.body,tags:v.tags,source:v.source,patch:v.patch,links:new FormData(f).getAll('links'),data:t.name==='game'?{map:'',checklist:editorDraft.data?.checklist||[]}:editorDraft.data||{}});}")
start=" if(r.kind==='strategy'){show(`<header>"
p=root/'app/command-center.js';text=p.read_text(encoding='utf-8');line=next(x for x in text.splitlines() if x.startswith(start))
text=text.replace(line," if(r.kind==='strategy'){show(`<header><h2>${e(r.title)}</h2>${closeButton()}</header>${actions(button('edit','Edit plan',`data-id=\"${r.id}\"`)+button('share','Share',`data-id=\"${r.id}\"`)+button('related-note','Add linked note',`data-id=\"${r.id}\"`)+button('delete','Delete',`data-id=\"${r.id}\"`))}<p>${e(r.body)}</p>${planningDetails(r)}${r.data.slots?.length?teamDetails(r):''}<div id=\"cc-board-host\"></div><div id=\"cc-attachments\" class=\"cc-attachments\"></div>`);await openBoard(r,$('#cc-board-host'));await toolsAction('show-attachments',{record:r});return;}")
line=next(x for x in text.splitlines() if x.startswith(" if(r.kind==='team'){"))
text=text.replace(line," if(r.kind==='team')detail=teamDetails(r)+actions(button('pair','Host this draft',`data-id=\"${r.id}\"`));")
p.write_text(text,encoding='utf-8')
edit('app/command-center.js',"<div id=\"cc-attachments\"></div>","<div id=\"cc-attachments\" class=\"cc-attachments\"></div>")
edit('app/command-center.js',"button('edit','Edit',`data-id=\"${r.id}\"`)+button('share','Share',`data-id=\"${r.id}\"`)+button('delete'", "button('edit','Edit',`data-id=\"${r.id}\"`)+button('related-note','Add linked note',`data-id=\"${r.id}\"`)+button('share','Share',`data-id=\"${r.id}\"`)+button('delete'")
edit('app/command-center.js'," if(name==='edit')return edit(r);", " if(name==='edit')return edit(r);\n if(name==='related-note')return edit({kind:'note',game:r.game,title:r.title+' · notes',links:[r.id],data:{map:r.data.map||'',...(r.data.location?{location:r.data.location}:{})}});")
edit('app/command-center.js',"...(r.data.attachments||[]).map(a=>a.id)","...(r.data.attachments||[]).map(a=>a.id),...(r.data.boards||[]).map(a=>a.imageId)")
edit('app/command-center.js',"...(x.data.attachments||[]).map(a=>a.id)","...(x.data.attachments||[]).map(a=>a.id),...(x.data.boards||[]).map(a=>a.imageId)")
