const {spawn}=require('node:child_process'),readline=require('node:readline'),path=require('node:path'),fs=require('node:fs/promises');
const {DEFAULTS,validateSettings,validateAnnotations,migrateSettings}=require('./coaching-settings.cjs');
function createCoachingOverlay({BrowserWindow,globalShortcut,screen,ipcMain,desktopCapturer,nativeImage,shell,directory,main,onError=()=>{},spawnWindow=spawn,platform=process.platform,getReplay=async()=>false}){
 let shortcutCapture=false,captureKeyTimer=null;
 let settings={...DEFAULTS},overlay=null,helper=null,active=false,suspended=false,starting=false,epoch=0,target=null,registered=[],error='',loaded=null,capturing=false,destroyed=false,replay=false,annotations=[],annotationWrite=Promise.resolve();
 const settingsFile=path.join(directory,'coaching.json'),captureDir=path.join(directory,'screenshots');
 const status=()=>({settings,active,suspended,starting,error,captureDir,replay});
 const publish=()=>{if(main&&!main.isDestroyed())main.webContents.send('coaching-status',status());};
 function stop(focus=true){focus=focus&&!suspended;suspended=false;epoch++;starting=false;active=false;target=null;for(const key of registered.filter(k=>k!==settings.toggleKey)){globalShortcut.unregister(key);}registered=registered.filter(k=>k===settings.toggleKey);if(overlay&&!overlay.isDestroyed()){overlay.setIgnoreMouseEvents(true);overlay.hide();overlay.webContents.send('coaching-mode',false);}const old=helper;helper=null;if(old){if(focus&&old.stdin.writable){old.stdin.write('exit\n');setTimeout(()=>old.kill(),150).unref();}else old.kill();}publish();}
 function fail(message){stop(false);error=message;publish();onError(message);}
 function installKeys(next){
  const wanted=next.enabled&&!shortcutCapture?[next.toggleKey,...(active&&!suspended?[next.clearKey]:[])]:[];const added=[];
  for(const key of wanted)if(!registered.includes(key)){const ok=globalShortcut.register(key,()=>{if(key===settings.toggleKey)void toggle().catch(e=>fail(e.message));else if(active)overlay?.webContents.send('coaching-clear');});if(!ok){for(const k of added)globalShortcut.unregister(k);throw Error('Shortcut '+key+' is already used. Choose another.');}added.push(key);}
  for(const key of registered)if(!wanted.includes(key))globalShortcut.unregister(key);registered=wanted;
 }
 function endShortcutCapture(){clearTimeout(captureKeyTimer);captureKeyTimer=null;if(!shortcutCapture)return;shortcutCapture=false;try{installKeys(settings);}catch(e){error=e.message;publish();}}
 function captureShortcuts(value){clearTimeout(captureKeyTimer);shortcutCapture=!!value;installKeys(settings);if(shortcutCapture){captureKeyTimer=setTimeout(endShortcutCapture,30000);captureKeyTimer.unref();}return status();}
 main?.on?.('blur',endShortcutCapture);
 async function save(input){const next=validateSettings({...settings,...input});installKeys(next);settings=next;if(!settings.enabled)stop();await fs.mkdir(directory,{recursive:true});await fs.writeFile(settingsFile,JSON.stringify(settings));overlay?.webContents.send('coaching-settings',settings);publish();return status();}
 const ready=(async()=>{try{annotations=validateAnnotations(JSON.parse(await fs.readFile(path.join(directory,'coaching-annotations.json'),'utf8')));}catch{}try{settings=migrateSettings(JSON.parse(await fs.readFile(settingsFile,'utf8')));}catch{}if(destroyed)return;try{installKeys(settings);}catch(e){error=e.message;}publish();})();
 async function ensureWindow(){if(overlay&&!overlay.isDestroyed())return loaded;
  overlay=new BrowserWindow({show:false,frame:false,transparent:true,backgroundColor:'#00000000',hasShadow:false,skipTaskbar:true,resizable:false,movable:false,fullscreenable:false,alwaysOnTop:true,webPreferences:{preload:path.join(__dirname,'coaching-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:true}});
  overlay.removeMenu();overlay.setIgnoreMouseEvents(true);overlay.setAlwaysOnTop(true,'screen-saver');overlay.webContents.setWindowOpenHandler(()=>({action:'deny'}));overlay.webContents.on('will-navigate',e=>e.preventDefault());overlay.webContents.on('render-process-gone',()=>{stop(false);overlay?.destroy();overlay=null;});overlay.on('closed',()=>{overlay=null;stop(false);});
  loaded=overlay.loadFile(path.join(__dirname,'../app/coaching/index.html'));await loaded;
 }
 function position(raw){if(!raw||![raw.x,raw.y,raw.width,raw.height].every(Number.isFinite)||raw.width<100||raw.height<100)return fail('The Rocket League window is not visible.');target=raw;const bounds=screen.screenToDipRect(null,{x:raw.x,y:raw.y,width:raw.width,height:raw.height});overlay.setBounds(bounds);}
 async function toggle(){await ready;if(active||starting){stop();return status();}if(!settings.enabled)throw Error('Enable Coaching Overlay in Tracker settings.');if(platform!=='win32')throw Error('Coaching Overlay currently supports Windows.');
  starting=true;error='';const ticket=++epoch;publish();
  try{await ensureWindow();}catch(e){stop(false);throw e;}if(ticket!==epoch)return status();
  try{replay=!!(await getReplay());}catch{replay=false;}if(ticket!==epoch)return status();
  const child=spawnWindow('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(__dirname,'coaching-window.ps1').replace(/app\.asar([\\/])/,'app.asar.unpacked$1')],{windowsHide:true,env:{...process.env,DZ_OVERLAY_PID:String(process.pid),DZ_OVERLAY_HWND:overlay.getNativeWindowHandle?.().readBigUInt64LE().toString()||'0',DZ_COACH_CACHE:path.join(directory,'coaching-cache')},stdio:['pipe','pipe','pipe']});helper=child;
  const timeout=setTimeout(()=>{if(ticket===epoch&&starting)fail('Could not locate Rocket League. Use Borderless or Windowed mode and try again.');},8000);timeout.unref();
  let helperError='';child.stdin.on('error',()=>{});child.stderr.on('data',chunk=>{helperError=(helperError+chunk.toString()).slice(-4000);});child.on('error',e=>{if(ticket===epoch)fail(e.message);});child.on('exit',code=>{clearTimeout(timeout);if(ticket===epoch){if(starting||code)fail('The coaching window helper could not start'+(code?' (exit '+code+')':'')+'. '+(helperError.trim().split(/\r?\n/)[0]||'Try opening the overlay again.'));else stop(false);}});
  readline.createInterface({input:child.stdout}).on('line',line=>{if(ticket!==epoch)return;try{const data=JSON.parse(line);if(data.error)return fail(data.error);if(data.closed)return stop(false);if(data.suspended===true||data.hidden){if(active){suspended=true;installKeys(settings);overlay.setIgnoreMouseEvents(true);overlay.hide();overlay.webContents.send('coaching-mode',{active:false,suspended:true});publish();}return;}if(data.suspended===false){if(active&&suspended){suspended=false;installKeys(settings);overlay.webContents.send('coaching-mode',{active:true,resume:true,replay});overlay.setIgnoreMouseEvents(false);overlay.show();overlay.focus();publish();}return;}position(data);if(ticket!==epoch)return;if(!active){clearTimeout(timeout);starting=false;active=true;try{installKeys(settings);}catch(e){return fail(e.message);}overlay.webContents.send('coaching-settings',settings);overlay.webContents.send('coaching-mode',{active:true,replay});overlay.setIgnoreMouseEvents(false);overlay.show();overlay.focus();publish();}}catch(e){if(ticket===epoch)fail('Could not position the coaching overlay: '+e.message);}});
  return status();
 }
 async function captureFrame(){if(!active||suspended||!target||capturing)throw Error('Open drawing mode before capturing.');if(!settings.screenshots)throw Error('Enable annotated screenshots in settings.');capturing=true;const captureTarget={...target},ticket=epoch;try{
  overlay.setOpacity(0);await new Promise(r=>setTimeout(r,65));
  const bounds=screen.screenToDipRect(null,captureTarget),display=screen.getDisplayMatching(bounds),m=captureTarget.monitor;
  if(captureTarget.x<m.x||captureTarget.y<m.y||captureTarget.x+captureTarget.width>m.x+m.width||captureTarget.y+captureTarget.height>m.y+m.height)throw Error('Move Rocket League fully onto one monitor before capturing.');
  const sources=await desktopCapturer.getSources({types:['screen'],thumbnailSize:{width:m.width,height:m.height},fetchWindowIcons:false});
  if(ticket!==epoch||suspended)throw Error('Drawing mode was interrupted before capture completed.');if(JSON.stringify(target)!==JSON.stringify(captureTarget))throw Error('Game window moved during capture. Try again.');
  const source=sources.find(s=>String(s.display_id)===String(display.id));if(!source||source.thumbnail.isEmpty())throw Error('Frame unavailable. Switch Rocket League to Borderless and try again.');
  const size=source.thumbnail.getSize(),sx=size.width/m.width,sy=size.height/m.height;
  const rect={x:Math.max(0,Math.round((captureTarget.x-m.x)*sx)),y:Math.max(0,Math.round((captureTarget.y-m.y)*sy)),width:Math.round(captureTarget.width*sx),height:Math.round(captureTarget.height*sy)};
  rect.width=Math.min(rect.width,size.width-rect.x);rect.height=Math.min(rect.height,size.height-rect.y);if(rect.width<1||rect.height<1)throw Error('Move Rocket League fully onto one monitor before capturing.');
  return {image:source.thumbnail.crop(rect).toDataURL()};
 }finally{capturing=false;if(overlay&&!overlay.isDestroyed())overlay.setOpacity(1);}}
 async function saveCapture(data){if(!settings.screenshots||!active||typeof data!=='string'||data.length>64*1024*1024||!data.startsWith('data:image/png;base64,'))throw Error('Invalid screenshot.');const image=nativeImage.createFromDataURL(data);if(image.isEmpty())throw Error('Screenshot is empty.');await fs.mkdir(captureDir,{recursive:true});const file=path.join(captureDir,'coaching-'+new Date().toISOString().replace(/[:.]/g,'-')+'.png');await fs.writeFile(file,image.toPNG());return {saved:true};}
 const command=async input=>{await ready;switch(input?.action){case 'toggle':return toggle();case 'exit':stop();return status();case 'settings':return save(input.settings||{});case 'shortcut-capture':return captureShortcuts(input.active);case 'state':return status();case 'captures':await fs.mkdir(captureDir,{recursive:true});await shell.openPath(captureDir);return status();default:throw Error('Unknown coaching command.');}};
 ipcMain.handle('coaching-draw',async(e,input)=>{if(!overlay||e.sender!==overlay.webContents||e.senderFrame!==overlay.webContents.mainFrame)throw Error('Untrusted overlay caller.');switch(input?.action){case 'state':await ready;return {...status(),annotations};case 'annotations':{const next=validateAnnotations(input.objects);annotationWrite=annotationWrite.catch(()=>{}).then(async()=>{await fs.mkdir(directory,{recursive:true});const file=path.join(directory,'coaching-annotations.json');await fs.writeFile(file+'.tmp',JSON.stringify(next));await fs.rename(file+'.tmp',file);annotations=next;});await annotationWrite;return {saved:true};}case 'exit':stop();return status();case 'settings':return save(input.settings||{});case 'frame':return captureFrame();case 'save':return saveCapture(input.image);default:throw Error('Unknown overlay action.');}});
 const displayRemoved=()=>{if(active)stop();},displayChanged=()=>{if(active&&target)position(target);};screen.on('display-removed',displayRemoved);screen.on('display-metrics-changed',displayChanged);
 return {command,status,destroy(){if(destroyed)return;destroyed=true;clearTimeout(captureKeyTimer);main?.removeListener?.('blur',endShortcutCapture);stop(false);for(const key of registered)globalShortcut.unregister(key);registered=[];ipcMain.removeHandler('coaching-draw');screen.removeListener('display-removed',displayRemoved);screen.removeListener('display-metrics-changed',displayChanged);overlay?.destroy();overlay=null;}};
}
module.exports={createCoachingOverlay};
