'use strict';
const {Worker}=require('node:worker_threads');
const path=require('node:path');
function createRocketLeague({directory,window,app}){
 const accounts=require('./accounts.cjs').createAccounts({directory,safeStorage:require('electron').safeStorage});
 const setup=require('../core/rocket-league-setup.cjs');let setupFiles=[],setupBusy=false;
 async function configure(input){if(setupBusy)throw Error('Setup is already checking.');setupBusy=true;try{
 if(input.action==='setup-check')setupFiles=await setup.discover();
 if(input.action==='setup-browse'){const {dialog}=require('electron');const result=await dialog.showOpenDialog(window,{title:'Choose your Rocket League installation folder',properties:['openDirectory']});if(!result.canceled){const file=await setup.configAt(result.filePaths[0]);if(!file)throw Error('Choose the Rocket League folder containing Binaries and TAGame. No Stats API config was found there.');setupFiles=[file];}}
 let result;if(input.action==='setup-enable'){const index=input.index;if(!Number.isInteger(index)||!setupFiles[index])throw Error('Check the installation first.');result=await setup.enable(setupFiles[index]);await request({action:'settings',value:{port:result.port,tracking:true}});}
 const installations=[];for(const file of setupFiles){try{installations.push(await setup.inspect(file));}catch(e){installations.push({file,ready:false,error:e.message});}}
 if(!result&&installations.length===1&&installations[0].ready)await request({action:'settings',value:{port:installations[0].port}});
 return {installations,...(result?{result}:{})};
 }finally{setupBusy=false;}}
 let worker=null,failure='',pageVisible=false,id=0,lifecycle='idle';const pending=new Map();
 try{worker=new Worker(path.join(__dirname,'../core/rocket-league-worker.cjs'),{workerData:{directory}});worker.on('message',m=>{if(m.event==='lifecycle'){lifecycle=m.value;return;}if(m.event==='state'){if(!window.isDestroyed()&&!window.isMinimized()&&pageVisible)window.webContents.send('rocket-league-state',m.value);return;}const job=pending.get(m.id);if(job){clearTimeout(job.timer);pending.delete(m.id);m.error?job.reject(Error(m.error)):job.resolve(m.value);}});worker.on('error',e=>{failure=e.message;for(const j of pending.values()){clearTimeout(j.timer);j.reject(Error('Rocket League tracker unavailable.'));}pending.clear();});worker.on('exit',()=>{failure='Tracker stopped. Restart Dropzone to retry.';});}catch(e){failure=e.message;}
 function request(input){if(failure||!worker)return Promise.reject(Error(failure||'Tracker unavailable.'));if(pending.size>=16)return Promise.reject(Error('Tracker is busy. Try again.'));return new Promise((resolve,reject)=>{const key=++id,timer=setTimeout(()=>{pending.delete(key);reject(Error('Tracker request timed out.'));},10000);pending.set(key,{resolve,reject,timer});worker.postMessage({id:key,input});});}
 async function detectIdentity(){if(process.platform!=='win32')return;try{const {execFile}=require('node:child_process'),{promisify}=require('node:util');const {stdout}=await promisify(execFile)('reg.exe',['query','HKCU\\Software\\Valve\\Steam\\ActiveProcess','/v','ActiveUser'],{windowsHide:true,timeout:3000});const value=stdout.match(/ActiveUser\s+REG_DWORD\s+(0x[0-9a-f]+)/i)?.[1];if(value&&BigInt(value)>0n)await request({action:'local-identity',identity:'Steam|'+(76561197960265728n+BigInt(value))+'|0'});}catch{}}
 async function applyHistoryPolicy(){const policy=await accounts.command({action:'account-history-policy'});return request({action:'history-policy',days:policy.days});}
 const policyReady=applyHistoryPolicy();policyReady.catch(()=>{});
 void detectIdentity();const identityTimer=setInterval(detectIdentity,60000);identityTimer.unref();
 async function avatar(){const {dialog,nativeImage}=require('electron');const picked=await dialog.showOpenDialog(window,{title:'Choose your profile picture',properties:['openFile'],filters:[{name:'Images',extensions:['png','jpg','jpeg','webp']}]});if(!picked.canceled){const fs=require('node:fs/promises');if((await fs.stat(picked.filePaths[0])).size>10*1024*1024)throw Error('Choose an image smaller than 10 MB.');const image=nativeImage.createFromPath(picked.filePaths[0]);if(image.isEmpty())throw Error('This image could not be opened.');const size=image.getSize(),edge=Math.min(size.width,size.height);const data=image.crop({x:Math.floor((size.width-edge)/2),y:Math.floor((size.height-edge)/2),width:edge,height:edge}).resize({width:128,height:128}).toPNG().toString('base64');const avatar='data:image/png;base64,'+data;await request({action:'settings',value:{avatar}});const account=await accounts.command({action:'account-state'});if(account.user)await accounts.command({action:'account-profile',avatar});}return request({action:'state'});}
 let syncing=false;async function syncCloud(){if(syncing)return {message:'Sync already in progress.'};syncing=true;try{const account=await accounts.command({action:'account-state'});if(!account.user)return {message:'Sign in to sync your history.'};const rows=await request({action:'cloud-records'});for(let i=0;i<rows.length;i+=100)await accounts.command({action:'account-upload',owner:account.user.id,matches:rows.slice(i,i+100)});const local=await request({action:'state'});if(local.settings.avatar)await accounts.command({action:'account-profile',avatar:local.settings.avatar});return {message:rows.length+' matches synced.'};}finally{syncing=false;}}
 const cloudTimer=setInterval(()=>syncCloud().catch(()=>{}),300000);cloudTimer.unref();
 function visibility(){request({action:'visible',value:pageVisible&&!window.isMinimized()&&window.isVisible()}).catch(()=>{});}
 window.on('minimize',visibility);window.on('restore',visibility);window.on('hide',visibility);window.on('show',visibility);
 return {isActive:()=>lifecycle==='active',async command(input){await policyReady;if(input?.action==='history-policy'||input?.action==='account-history-policy')throw Error('Unsupported request.');if(input?.action==='account-sync')return syncCloud();if(input?.action?.startsWith('account-')){if(input.action==='account-upload')throw Error('Unsupported request.');const result=await accounts.command(input);if(['account-signin','account-verify','account-signout','account-delete'].includes(input.action))await applyHistoryPolicy();if(['account-signin','account-verify'].includes(input.action))void syncCloud().catch(()=>{});return result;}if(input?.action==='local-identity')throw Error('Unsupported request.');if(input?.action==='avatar')return avatar();if(['setup-check','setup-browse','setup-enable'].includes(input?.action))return configure(input);if(input?.action==='visible'){pageVisible=input.value===true;visibility();return {ok:true};}if(input?.action==='performance'){const metrics=app.getAppMetrics();return {cpu:metrics.reduce((n,m)=>n+(m.cpu?.percentCPUUsage||0),0),ramMB:metrics.reduce((n,m)=>n+(m.memory?.workingSetSize||0),0)/1024,uptime:Math.round(process.uptime())};}return request(input);},destroy(){clearInterval(identityTimer);clearInterval(cloudTimer);worker?.terminate();for(const j of pending.values()){clearTimeout(j.timer);j.reject(Error('Tracker closed.'));}pending.clear();}};
}
module.exports={createRocketLeague};
